### ISSUE TITLE
cancel button works only sporadically during isotope portion of peak detection

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#100]
If I process a database with isotope detection enabled, then during the second portion ("calculating isotopes") it's often the case that I'm unable to cancel the process (hitting cancel multiple times has no effect).

Sometimes it does work, so I guess something to do with the exact timing.

Not a huge deal if it's a complicated matter.

**Comment by GeorgeSabu** [comment]
@chubukov This issue is resolved and updated on the develop.
