### ISSUE TITLE
Autosave not working on Windows platform

### ISSUE THREAD

**Issue by saifulbkhan** [ElucidataInc/ElMaven#1007]
**Describe the bug**
For every peak bookmarked or curated as good/bad, El-MAVEN is supposed to maintain a session state in the form of an `emDB` file. This file is named using a timestamp string. The format of this string is ISO 8601 date-time format (_"yyyy-MM-ddTHH:mm:ss"_). While the colon (':') character is allowed for filenames on UNIX (Linux and MacOS) platforms, valid filenames on Windows OS cannot contain this character. Therefore, request for creating autosave files with such names are being silently rejected, and no checkpoints of user activity is currently being saved.

**Expected behavior**
Marking a peakgroup as good or bad, or bookmarking a peak should cause creation of physical autosave (emDB) files.

**System (please complete the following information):**
 - OS: Windows 10 (but should also be reproducible on Windows 7 as well).
 - Version: 0.6.1

**Comment by shubhra-agrawal** [comment]
This has been fixed and will be part of the v0.7 release.
