### ISSUE TITLE
The OBI-Wrap algorithm for alignment took a long time to process 6 samples

### ISSUE THREAD

**Issue by KMaheswari** [ElucidataInc/ElMaven#1017]
The data that I was processing was a GC MS data, and the samples were in CDF format.
It took around 1.5 hours to process 6 samples of 64 MB each.
Link to dataset: https://www.metabolomicsworkbench.org/data/DRCCStudySummary.php?Mode=SetupRawDataDownload&StudyID=ST000054

**Comment by KMaheswari** [comment]
@shubhra-agrawal

**Comment by saifulbkhan** [comment]
OBI-Warp has been coupled with segmented alignment and should now be considerably faster for heavy datasets.
