### ISSUE TITLE
understand peak->group assignment in EIC window vs automated search and unify parameters

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#103]
I've seen this several times now: When manually picking peaks in the EIC window, I get one set of peaks grouped together. But doing DB search, I get a different set of peaks grouped. I would like to get a better handle on what causes this difference, what the relevant parameters are, and whether it's possible to get consistent behavior, or whether that's undesirable for some reason.

I think this requires several of us to look at the code together and talk about what the differences are and why it may have been written the way it was.

PS. This is anecdotal, but in general I feel like I get "better" grouping when doing manual picking in the EIC window.

**Comment by chubukov** [comment]
I looked at this code a little bit today.

1) The function that selects which peak is highlighted in the EIC widget is a ridiculously simple heuristic (`EICLogic::selectGroupNearRt`). It finds any groups within 2min of expectedRt and takes the one with the highest intensity.  Was this always like this or was it a recent addition? For some reason I thought it did something smarter. In any case, it's clear to change this to using the groupRank formula (with the weights determined by the user as in #90 

2) I can't figure out any reason why grouping would be different between the EIC window and the automated peak detection. It looks like they both call `EIC::groupPeaks` and the parameters are taken from `settings`. Let me know if you have any guesses as to why they might produce different behaviors, and I will keep thinking about this also

**Comment by sahil21** [comment]
- Highlighting groups on the basis of group rank is implemented. Currently, the user can use Peak’s Dialog group rank user Interface for manual peak detection/compound database widget. Shifting the group rank UI Interface into Options Dialog will be added as a new issue. 

- Identifying the difference in grouping between Automatic Peak Detection and Manual Peak Detection will be added as a new issue and will be resolved in the coming sprint.

**Testing for the feature:**

1. **Default Parameters:** 

![image](https://user-images.githubusercontent.com/21240516/27337247-71e97e5c-55ef-11e7-843c-741487ea25d6.png)

![image](https://user-images.githubusercontent.com/21240516/27337257-77c90af4-55ef-11e7-9b8a-37fc6051fa56.png)

2. **Grouping Parameters changed**

![image](https://user-images.githubusercontent.com/21240516/27337302-a595579e-55ef-11e7-9b98-50a15c0d2e48.png)

![image](https://user-images.githubusercontent.com/21240516/27337310-ab547e4e-55ef-11e7-9601-681a1c985629.png)

**Comment by chubukov** [comment]
@sahil21  probably part of #217 but right now if you don't have "match retention times" enabled in the automatic peak detection dialog box, then the RT weight also doesn't get used in the grouprank formula for choosing the peak in the EIC window

**Comment by sahil21** [comment]
@chubukov We'll make the visibility of "DeltaRt Weight" slider independent of "Match Retention Times". This fix will be part of #217.

**Comment by chubukov** [comment]
@sahil21 great. i played with this feature a fair bit today, and I concluded that

1) as far as I can tell the code is working properly
2) the grouprank formula needs some fine tuning

I was playing around with the weights looking at two peaks:
1) intensity ~1e8, quality ~0.85, delta RT ~0.35
2) intensity ~5e5, quality ~0.5, delta RT ~0.03

I think that having group 2 (right on for RT but very poor peak) selected by default is fine. But it should be possible to shift the parameters so that group 1 (great peak a little bit off RT) is chosen. With the current formula, I have to set the intensity or quality weight to about 15. Of course we can accomodate this by just changing the slider limits, but I do think the log I think that the log in the intensity coefficient is too much attenuation, and I also think that we should add a small constant to the deltaRT coefficient so that even if it's very close to zero, it could be outweighed by intensity if the weights are right.

So I guess I propose

1) change (deltaRt)^2C to ((deltaRt^2)+epsilon)^C
2) let the sliders go up at least 10 or maybe 20 instead of 5 (if we make them log scale, even better, but not a big deal)

and eventually
3) I think that changing (log(intensity)+1)^B to something like (intensity+1)^0.1B would be a good idea. But since this would make the old behavior unrecoverable, we don't have to do it (I think having two different grouprank formulas is option overload)

**Comment by chubukov** [comment]
@sahil21 I think something changed related to this in the latest release. It looks to me like no matter what I set the weights to (or the "consider Rt" flag), the deltaRt is not being taken into account in the grouprank calculation. As a test, if I set QualityWeight and IntensityWeight to 0, then I get groupRank=1 for every group. This is true both with bookmarking from the EIC window, and with automatic compound search.

**Comment by shubhra-agrawal** [comment]
@chubukov This functionality was working fine before refactoring the code for Group Rank tab [efdae1f](https://github.com/ElucidataInc/ElMaven/commit/efdae1f). The consider Rt flag was not being set every time the checkbox was selected/deselected. This issue has been fixed in [a0127ff](https://github.com/ElucidataInc/ElMaven/commit/a0127ff)

**Comment by chubukov** [comment]
@shubhra-agrawal @sahil21 I don't believe this is fixed. Here is what I can reproduce:

If I slide dRT Weight, I can indeed select the group closer to the expectedRt vs the group with higher intensity. I would expect that unchecking the "consider retention time" box is equivalent to setting the "dRT weight" to zero. But that's not what happens -- it seems to have no effect whatsoever on what group is selected in the EIC window.

It would also be good to check if it is being initialized properly -- by default for me, it is unchecked, but it actually is being used (because the selected group is the one I would get only if "dRt Weight" was >0)

**Comment by shubhra-agrawal** [comment]
@chubukov I've opened a separate [issue](https://github.com/ElucidataInc/ElMaven/issues/422) for this.

**Comment by shubhra-agrawal** [comment]
> 1. The function that selects which peak is highlighted in the EIC widget is a ridiculously simple heuristic (`EICLogic::selectGroupNearRt`). It finds any groups within 2min of expectedRt and takes the one with the highest intensity.  Was this always like this? (Edit: just checked 776, it was the same, as expected). For some reason I thought it did something smarter. In any case, it's clear to change this to using the groupRank formula (with the weights determined by the user as in #90

Resolved

> 2. I can't figure out any reason why grouping would be different between the EIC window and the automated peak detection. It looks like they both call `EIC::groupPeaks` and the parameters are taken from `settings`. Let me know if you have any guesses as to why they might produce different behaviors, and I will keep thinking about this also

Resolved as part of #265

>  I would expect that unchecking the "consider retention time" box is equivalent to setting the "dRT weight" to zero.

Filed as #422. It seems to be working on latest develop

The only unresolved conversation in this thread is around tweaking the rank formula to cover certain cases:

> 1. change (deltaRt)^2C to ((deltaRt^2)+epsilon)^C. Some fraction (0.05?) of the peak width would be a good value for epsilon, that way if RT units change from minutes to seconds or something like that, we don't have to worry about our hard-coded value.
> 2. let the sliders go up at least 10 or maybe 20 instead of 5 (if we make them log scale, even better, but not a big deal)
> 3. I think that changing (log(intensity)+1)^B to something like (intensity+1)^0.1B would be a good idea. But since this would make the old behavior unrecoverable, we don't have to do it (I think having two different grouprank formulas is option overload)

Let's move this conversation to #90 and close this thread? @chubukov
