### ISSUE TITLE
Ability to detect labeled metabolites when unlabelled population is low.

### ISSUE THREAD

**Issue by paopaocui** [ElucidataInc/ElMaven#1046]
**Is your feature request related to a problem? Please describe.**
The current El-Maven algorithm fails to pick up a metabolite when the unlabeled population is really low. For example, if I use fully labeled glucose as my substrate, it won't pick up the correct glucose peaks. This is really frustrating, being able to use labeled substrate is really important. 

**Describe the solution you'd like**
I would expect the El-maven to be able to pick up a metabolite when the unlabeled population is low, as the oldest Maven software enables. 

**Describe alternatives you've considered**
I don't see any alternatives that can solve this specific problem. 

**Additional context**

**Comment by shubhra-agrawal** [comment]
@paopaocui Thanks for filing this issue. It helps us prioritize features based on the needs of the community. 

It seems like there is an existing issue ( #687) that is very similar. I'm closing this one as a duplicate and marking you on that one.
