### ISSUE TITLE
EL-MAVEN crashes on uploading my mzXML files but does not crashes on demo files

### ISSUE THREAD

**Issue by metabonucleotide** [ElucidataInc/ElMaven#1048]
Hi, 
I converted my raw files collected from LC-MS Themo QE instrument using MSconvertGUI (64bit) into mzML or mzXM (tried both extension). When uploading my files on EL-MAVEN, it crashes. I downloaded EL-MAVEN yesterday from [here] (https://elucidatainc.github.io/ElMaven/Downloads/) for Windows 7.0. 
When I upload the MAVEN demo files, it does not crash and works pretty well. Can anyone help me solving this issue?

This is the error message I am getting: 

> EL-MAVEN has encountered a problem and needs to close. We are sorry for the inconvenience.We have created an error report that you can send to us.

I sent the report multiple times, but no feedback so far.

![image](https://user-images.githubusercontent.com/50248030/57160641-f8f42e00-6dae-11e9-91ba-f69ad04b953a.png)

Thank you for your help! 
Best,

**Comment by shubhra-agrawal** [comment]
@metabonucleotide MSConvert GUI uses a compression technique to reduce file sizes when converting between formats. El-MAVEN is currently unable to decompress those files and is frequently the reason for such crashes. Could you try converting the files again but with the 'Use zlib compression' box unchecked? It is switched on by default in the MSConvert GUI. Please let us know if this works!

We have been able to resolve this crash in one of our internal builds and we hope to have it out by the next release of El-MAVEN.

Note: We have noticed some issues on Windows 7 when large sample files (>2 GB individual sample file) are imported into El-MAVEN. Please let us know if you run into that problem.

**Comment by shubhra-agrawal** [comment]
@metabonucleotide We received a new crash report from a Windows 7 system (~12 hours ago) for zlib compressed files. 

If that was you, please try and uncheck the 'zlib compression' option _or_ drop us a mail at elmaven@elucidata.io and our support team will do the conversion for you.

**Comment by metabonucleotide** [comment]
Dear Shubhra Agrawal,

Thank you for your help. It is working fine now.
I will inform my lab about the uncheck zlib compression trick.

Kind regards,

Issam

**Comment by shubhra-agrawal** [comment]
Great! I'll let you know when this functionality is available in El-MAVEN. Closing this thread.
