### ISSUE TITLE
Unable to do correct peak picking in automated peak detection (untargeted)  

### ISSUE THREAD

**Issue by sunil20dhakad** [ElucidataInc/ElMaven#1053]
I am doing untargeted peak picking in ElMaven. I noticed that the intensity values of the samples are not correct as dots are not shown at their proper place. 
![Screen Shot 2019-05-13 at 3 55 07 PM](https://user-images.githubusercontent.com/31559038/57614889-f73d1e00-7597-11e9-8850-9a71ad3672c6.png)

The ideal behavior should be like the following figure. 
![Screen Shot 2019-05-13 at 3 59 15 PM](https://user-images.githubusercontent.com/31559038/57614961-2784bc80-7598-11e9-9cc6-7598e34fd0e7.png)

**Comment by sunil20dhakad** [comment]
@shubhra-agrawal FYI

**Comment by saifulbkhan** [comment]
@sunil20dhakad This (mis)behavior should not occur anymore (thanks to your slice "adjustment" suggestion), if peaks are visualized at the correct mass tolerance value, with v0.10.0. Closing this.
