### ISSUE TITLE
_index.js.xxx file does not get deleted on Windows platform

### ISSUE THREAD

**Issue by rish9511** [ElucidataInc/ElMaven#1062]
**Describe the bug**
On running El-MAVEN from file explorer, the _index.js.xxxx file that gets downloaded during the start of the session does not get deleted after the session is over. However, this is not the case when the session is started from `msys shell`.  

**To Reproduce**
1. Start El-MAVEN from Windows file explorer
2. Keep note of the of the name of _index.js.xxx file
3. Close session using th GUI  

**Expected behavior**
_index.js.xxx that gets downloaded should get deleted after the session ends

**System (please complete the following information):**
 - OS: Windows 10
 - Version: v0.7.1-beta

**Comment by shubhra-agrawal** [comment]
Index.js is now downloaded as a temporary file and deleted when the app closes.
