### ISSUE TITLE
Maven tests crashes with SIGBART

### ISSUE THREAD

**Issue by rish9511** [ElucidataInc/ElMaven#1065]
**Describe the bug**
Maven tests crashes with SIGABRT when dependencies like `libmaven` etc are compiled with 
_debug_, _ftest-coverage_ etc flags. 

According to stack trace, the crash happens because one of the test function times out:

```
  #0  0x00007fe9f5562428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux  /raise.c:54
  #1  0x00007fe9f556402a in __GI_abort () at abort.c:89
  #2  0x00007fe9f665790d in qt_message_fatal (context=..., message=<synthetic pointer>) at global/qlogging.cpp:1842
  #3  QMessageLogger::fatal (this=this@entry=0x7fe9ef6cbda0, msg=msg@entry=0x7fe9f6d06e83 "Test function timed out") at global/qlogging.cpp:880
  #4  0x00007fe9f6ce88d1 in QTest::WatchDog::run (this=0xefdb2b0) at qtestcase.cpp:1010
  #5  0x00007fe9f6685727 in QThreadPrivate::start (arg=0xefdb2b0) at thread/qthread_unix.cpp:367
  #6  0x00007fe9f63c16ba in start_thread (arg=0x7fe9ef6cc700) at pthread_create.c:333
  #7  0x00007fe9f563441d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

[According to Qt](https://bugreports.qt.io/browse/QTBUG-52402), there's a hard limit of 5 minutes on test functions, beyond which the application will crash with the "Test function timed out" message.  

To be able to bypass the hard limit, we can use `QTEST_FUNCTION_TIMEOUT` environment variable, introduced in this [patch](https://codereview.qt-project.org/c/qt/qtbase/+/155473), and set it to a value that's sufficient to run the test case. 

Ideally,  any of our test function should not take this long to execute. 

**To Reproduce**

1. Checkout to branch `ElMaven-CI`
2. export TRAVIS=1
3. Compile in debug mode 
4. Run: bin/MavenTests -xml

**Expected behavior**
MavenTests should not crash 

**System (please complete the following information):**
 - OS: Linux(Ubuntu 16.04) and Windows 10

**Comment by saifulbkhan** [comment]
CI no longer faces this particular crash.
