### ISSUE TITLE
Add check for index.js before starting a new EPI process

### ISSUE THREAD

**Issue by shubhra-agrawal** [ElucidataInc/ElMaven#1077]
We recently made a change in Polly integration where we host the JS integration file in a separate GitHub repo to make it more maintainable, and added custom error messages if an API breaks and general error messages when the integration breaks otherwise.

Since none of the EPI process will work without the JS file, users should be informed if El-MAVEN could not successfully fetch the integration file and prevent any process from starting.

**Comment by saifulbkhan** [comment]
This issue will be fixed with upcoming release v0.8.0.
