### ISSUE TITLE
manual integration does not record expectedRtDiff

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#108]
If you pick a compound from the compound widget and manually integrate the peak (double click/shift-drag/mark good), expectedRtDiff does not get calculated (or at least it doesn't get exported when you export the bookmarks table).

I think this may have been this way in all Maven versions, but it seems like a clear bug to me and should be straightforward to fix.

**Comment by GeorgeSabu** [comment]
@chubukov This issue is resolved and updated on the develop.
