### ISSUE TITLE
Crash on changing mass cutoff type

### ISSUE THREAD

**Issue by shubhra-agrawal** [ElucidataInc/ElMaven#1088]
**Describe the bug**
Changing the resolution to mDa leads to a crash in automated search sometimes

**To Reproduce**
1. Change mainwindow resolution unit to mDa
2. Change mainwindow resolution to desired value
3. Go to Peaks dialog
4. Select Automated search
5. Click on Find Peaks
6. Application crashes

**Comment by saifulbkhan** [comment]
This will be fixed in the upcoming v0.8.0.
