### ISSUE TITLE
make behavior consistent between manual bookmark and automated peak finding when no isotopes are checked

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#109]
If nothing is checked for isotope detection and you bookmark a peak manually, you will still get the parent group and the "C12 PARENT" child group. If you do automated peak picking with the "detect isotopes" checkbox disabled, you don't get any child group. Let's make these consistent.

I prefer the version with no child group, so basically manual bookmarking would need to check for the special case when there are no isotopic peaks to integrate. Or it can be a global checkbox on the options dialog.

**Comment by chubukov** [comment]
This is actually still unchanged in the latest version. The one thing that did happen was that the parent peak is not exported to CSV. But it's still mildly inconsistent to me.

**Comment by saifulbkhan** [comment]
I don't think that the inconsistency described is possible anymore. We have a global "Isotopes Dialog" whose settings apply to both manual and automated detection. Please feel free to re-open this if I am mistaken.
