### ISSUE TITLE
Update build instructions in README.md

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#1095]
**Describe the bug**
The build instructions in the `README.md` file are incomplete or incorrect (at least for linux, perhaps for other OS's).

**To Reproduce**
1. Follow build instructions

**Expected behavior**
Compile a working ElMaven executable

**System (please complete the following information):**
 - OS: Ubuntu 16.04
 - Version: 0.7.1+

See https://github.com/ElucidataInc/ElMaven/issues/1063 and #1002

**Comment by shubhra-agrawal** [comment]
@lparsons The README has been updated with fresh build instructions for all platforms. Please take a look when you can and re-open this thread if needed
