### ISSUE TITLE
Polly UI stays frozen if internet connectivity is lost before upload

### ISSUE THREAD

**Issue by shubhra-agrawal** [ElucidataInc/ElMaven#1109]
**To Reproduce**
1. Create a peak table
2. Login to EPI
3. Switch off your internet connection
4. Click upload
5. UI elements apart from 'upload' are frozen
6. Switch on wifi
7. I cannot change the table/project name before clicking 'upload'

**Expected behavior**
User should be able to modify project details till 'Upload' is in progress

**System (please complete the following information):**
 - OS: Ubuntu
 - Version 0.7.1

**Comment by saifulbkhan** [comment]
Fixed in v0.9.0. Closing.
