### ISSUE TITLE
Allow database search along with untargeted detection

### ISSUE THREAD

**Issue by shubhra-agrawal** [ElucidataInc/ElMaven#1113]
**Is your feature request related to a problem? Please describe.**
Say, I get 200 peaks from a targeted search and 1000 from untargeted search. I would like to be able to merge these results together so I only have 800 unknowns remaining.

**Describe the solution you'd like**
Provide an option to select a database within untargeted search. The final peak table should have the 200 "annotated" groups as well as the other 800 groups that have mz@rt info

**Describe alternatives you've considered**
Merging to CSVs and using a python script to find matches

**Comment by saifulbkhan** [comment]
Starting v0.9.0, we are allowing an option to assign targets to features detected using untargeted detection mode. It should satisfy the use case described here.
