### ISSUE TITLE
isotope barplot -- legend is out of order when multiple elements are enabled

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#112]
We observed that the names of the isotopes in the legend entries sometimes are incorrect. This appears to only happen when multiple elements (e.g. C+N or C+D) are enabled.

**Comment by GeorgeSabu** [comment]
@chubukov This issue is now resolved. It was a problem related to sorting the labels according to intensity.

**Comment by chubukov** [comment]
@GeorgeSabu Great, seems to be working fine.
