### ISSUE TITLE
Crash on opening mzXML files

### ISSUE THREAD

**Issue by bookwormhyj** [ElucidataInc/ElMaven#1132]
ElMaven always crashes when opening my mzXML files. These mzXML files were generated by MSConvert without using zlib compression or gzip. I have no trouble opening the demo files.

Does anyone know why this would happen? Here is the dropbox link to two of the sample files that I cannot open with ElMaven. Thanks!

https://www.dropbox.com/sh/ira4eemf3pbzy68/AACtssreGZQ3lDotRDO2E3q5a?dl=0

**Comment by shubhra-agrawal** [comment]
@saifulbkhan Has this been resolved?

**Comment by saifulbkhan** [comment]
I downloaded the two files shared above. I can load them fine with v0.9.1. Closing the issue since it's no longer reproducible with the latest release.
