### ISSUE TITLE
No label isoptope peak table getting pushed to PollyPhi

### ISSUE THREAD

**Issue by Shreya-crypto** [ElucidataInc/ElMaven#1138]
**Describe the bug**
I am being able to push the peak table without any labelled isotope on PollyPhi 

**To Reproduce**
1. Open El-Maven and upload mzXML files 
2. Click on  "Peaks" and select "Compound database search"'
3. Tick the checkbox "Report isotopic peaks" 
Don't select any isotopic labels from Isotopic detection options (uncheck the selected ones)and click on "Find peaks"
4.Push the Peak table on PollyPhi 

**Expected behavior**
The table should not be pushed on PollyPhi

**System (please complete the following information):**
 - OS: windows 8

**Comment by shubhra-agrawal** [comment]
@Shreya-crypto Starting v0.9.1, 'Report Isotopic peaks' gets unchecked if no tracer has been selected. Can't think of any other way to create a Peak Table with C12 Parent but no other label for any group. This should resolve your issue.
