### ISSUE TITLE
Good Peak number greater than total number of peaks

### ISSUE THREAD

**Issue by skg1721** [ElucidataInc/ElMaven#1142]
The number of good peaks [is](url) more than the total number of peaks in some of the metabolites.
![Screenshot from 2019-08-29 13-18-34](https://user-images.githubusercontent.com/47272362/63922328-1df96480-ca62-11e9-9860-d645388c6ac2.png)

**Comment by saifulbkhan** [comment]
@skg1721 This is clearly a bug. But can you elaborate a little more on how you had performed peak-detection, or whether you had done anything unusual when you ran into this? I am trying to reproduce this on v0.9.0 with a few different datasets and detection settings, but have been unsuccessful so far.

**Comment by saifulbkhan** [comment]
@skg1721 This has been fixed with release v0.10.0.
