### ISSUE TITLE
Synchronise peak quantitation type from main window with peak detection dialog

### ISSUE THREAD

**Issue by vindev0106** [ElucidataInc/ElMaven#1149]
I'm always frustrated when El-MAVEN doesn't synchronize the peak quantitation type from peak detection dialog with main window.

The peak quantitation type from peak detection dialog with main window should synchronise, one always have to remember to go to the main dialog to change it while exporting the table and values, this is a non essential thing that need to be remembered every time. There are times after doing the whole analysis, I find my analysis was wrong because of exporting different values from what values I expected from peak detection.

**Comment by saifulbkhan** [comment]
Done in v0.11.0. Closing.
