### ISSUE TITLE
checkSrmList feature causing some issues with ms/ms data

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#115]
I had to disable the checkSRmList() functionality. It seemed to be causing a lot of problems with ms/ms data.

The main problem was when I load samples from two different experiments (which may well have quite different sets of transitions), Maven always crashed while trying to bring up the dialog box with the list of missing SRMs.

I uploaded some data to dropbox.

(Edit: originally had something about too many transitions not found, this is a separate issue, #116)

Finally (minor point just to keep in mind when implementing future dialog boxes), the text was very large and it was not possible to resize the box. Had to select/copy/paste to notepad for the message to be usable.

I simply commented out the functionality for our build -- this is a neat but not critical feature, so we can just temporarily move it out of the develop branch, and fix it eventually.

**Comment by GeorgeSabu** [comment]
@chubukov I am not able to reproduce the crash. I tried uploading 3 sets of data from folder 2017_01_25_multiple_msms_datasets. But it did not crash. 
But have added the feature that message box can be resized by the user in the commit https://github.com/ElucidataInc/ElMaven/commit/fb2133202b6a6fc90d84ca33af50fcd09f22b2be

**Comment by GeorgeSabu** [comment]
@chubukov I was not able to reproduce the crash. But I made some optimizations to code so that loading a large text should not be a problem. Can you confirm if it helped to resolve crash?

**Comment by chubukov** [comment]
I think jury is still out on this feature, but I haven't run into this particular issue in a while.
