### ISSUE TITLE
naming SRMs when reading mzML

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#116]
when I load the data in the 2016_01_25/set1 folder on dropbox, I get multiple entries (one for each sample) for each SRM.

What's happening is that msconvert is naming the transitions in the mzML like this:

`<chromatogram index="1" id="SRM SIC Q1=107 Q3=62 sample=6 period=1 experiment=1 transition=0" defaultArrayLength="174">`

the `sample=6` bit is unique to each sample (not sure exactly what the other parameters mean). So ideally in this case maven should pull out just Q1, Q3, period, and transition out of this). We need to look at the mzML format spec to figure out what else to include/exclude.

**Comment by GeorgeSabu** [comment]
@chubukov We have resolved the issue you pointed out. The new SRM list looks like this.
![new_srm_list](https://cloud.githubusercontent.com/assets/22674403/22427147/fe2e8bdc-e727-11e6-82e8-09c6d5937be8.png)
Its on the commit https://github.com/ElucidataInc/ElMaven/commit/33dbe4b55f7e729bd66e5cc36fd464f20a14a637. If "sample=xx" is present it will remove it and replace by "". If  "sample=xx" is not present nothing will be done.

**Comment by GeorgeSabu** [comment]
@chubukov This change is now merged to the develop.

**Comment by GeorgeSabu** [comment]
@chubukov understanding of mzML format spec remaining.

**Comment by chubukov** [comment]
I suspect that this could be made more robust, but it's mostly working fine for now....

**Comment by chubukov** [comment]
It would be great to reopen this. We made a quick fix to deal with the files that we had at that point, but this is going to come up again as we try other formats.

Right now I'm dealing with mzML produced by msconvert from waters qtof data. MS1 only data right now. The ids look like this

```
<spectrum index="0" id="function=2 process=0 scan=1" defaultArrayLength="146">
<spectrum index="1" id="function=1 process=0 scan=1" defaultArrayLength="7042">
<spectrum index="2" id="function=1 process=0 scan=2" defaultArrayLength="6549">
```

I think these should be grouped by function, and the index should be ignored. But I'm not claiming that's going to solve all the other cases.

**Comment by sahil21** [comment]
@chubukov What about giving the option to cluster chromatograms ids on the basis of any attribute (sample number, index, function or multiple of them). 

Although, I would suggest not to put this option on the UI itself and rather give some kind of editable configuration file (These type of options are generally not changed by the user)

**Comment by chubukov** [comment]
That would probably be fine. I'm guessing that the best solution might be to try to guess the right grouping based on the vendor and format.

**Comment by sahil21** [comment]
@chubukov Agreed that will be the ideal solution but not sure if vendor and format information will be accessible in all the files.

**Comment by chubukov** [comment]
@sahil21 let's try it the way you suggest. As the default, I would recommend ignoring `scan`, `index`, and `sample`. Those are the ones that seem to come up the most.

**Comment by sahil21** [comment]
@chubukov Makes sense. 
@sunil20dhakad FYI.

**Comment by shubhra-agrawal** [comment]
@chubukov "sample", "start", "end" and "index" will be automatically removed from the SRM Id on develop. Will be available in v0.5.

Let us know if you run into more such qualifiers and we'll add it to the list unless we have a better way to handle this.

**Comment by shubhra-agrawal** [comment]
@chubukov `scan` has also been added to this list in v0.8.0-beta. And we are pulling out `filterString` from `chromatogramList` and `spectrumList` both. Earlier, we were using `id` from `spectrumList` in mzML files, instead.

Let us know if you run into any other such naming issues. Closing the thread till then!

**Comment by chubukov** [comment]
@shubhra-agrawal thanks, looking forward to testing it.
