### ISSUE TITLE
Popup fit issue

### ISSUE THREAD

**Issue by ramoss15** [ElucidataInc/ElMaven#1161]
I have Lenovo E480. My laptop has screen size of 14 inches. When I click on the 'Peaks' button. Popup won't auto fit and 'find peaks' button goes outside of the screen (refer [image](https://drive.google.com/file/d/1duryF1ch-7XCmWe4Ndxy-9YvNs1IPrVi/view?usp=sharing))

**Comment by saifulbkhan** [comment]
We have made sure that the detection dialog can now fit in 1366x768 resolutions, without any part being excluded from the visible window. Available with v0.10.0.
