### ISSUE TITLE
Use the same settings file for both GUI and CLI

### ISSUE THREAD

**Issue by shubhra-agrawal** [ElucidataInc/ElMaven#1163]
**Is your feature request related to a problem? Please describe.**
If I want to double-check some of my peaks from the CLI output in the GUI version of El-MAVEN, I will have to configure every setting manually in the GUI. Even though I have a config file with this information that I used for the CLI run.

**Describe the solution you'd like**
It would be great if the Settings file from the GUI can be used as config for CLI

**Comment by saifulbkhan** [comment]
You should now be able to do this, with v0.10.0. Closing.
