### ISSUE TITLE
Allow exporting metadata file template

### ISSUE THREAD

**Issue by shubhra-agrawal** [ElucidataInc/ElMaven#1171]
**Is your feature request related to a problem? Please describe.**
Manually entering cohort information in El-MAVEN is difficult, especially if I have 20+ samples. Creating a metadata file from scratch is also a lot of manual work since the sample filenames need to be entered in Excel.

**Describe the solution you'd like**
Once the user has imported their samples, allow exporting a metadatafile template with the correct file structure and all sample names filled in. Once the user has entered cohort, scaling or injection order information using Excel, El-MAVEN should read this file and assign the correct information to samples. 

Maybe there can be a sync button?? with a list of all exported templates in this session so the user can switch between different cohort definitions.

**Comment by saifulbkhan** [comment]
Available with v0.10.0.
