### ISSUE TITLE
Allow JSON File to be uploaded in ElMaven

### ISSUE THREAD

**Issue by sunil20dhakad** [ElucidataInc/ElMaven#1188]
ElMaven has a feature to save the whole EICs of the metabolites in a json file but there is no way to use it to look at the peaks that are picked. This option can be useful to share the json file with colleagues so that they can look at the peaks without loading whole data into ElMaven.

**Comment by sunil20dhakad** [comment]
@saifulbkhan FYI

**Comment by saifulbkhan** [comment]
@sunil20dhakad If you want to simply visualize your peak-groups as it were in El-MAVEN, then you can select (multiple) groups and export them as "PDF" option in export section of the peak table. This will generate an HTML file containing snapshots of each selected peak-group.

Closing this as resolved.
