### ISSUE TITLE
Allow RT restriction for untargeted+db search

### ISSUE THREAD

**Issue by shubhra-agrawal** [ElucidataInc/ElMaven#1203]
Since targeted detection has the option to set a tolerance for delta RT, the same should be available when the user is using a db with untargeted detection since it has been introduced to avoid separate targeted and untargeted runs.

**Comment by saifulbkhan** [comment]
Available with v0.10.0. But, I think, maybe our "Peaks" dialog UI needs some refactoring - elements seems to be duplicated and there's too much conditional enable/disable logic across the three sections.
