### ISSUE TITLE
Handle spaces in compound formula 

### ISSUE THREAD

**Issue by shubhra-agrawal** [ElucidataInc/ElMaven#1213]
**Describe the bug**
I tried using a Compound DB where the formula had spaces in between. Observed that some compounds had wrong m/zs in El-MAVEN. On further inspection, it looks like El-MAVEN is able to calculate the correct m/z if the spaces are between two different elements (C6 H12O6) but fails when the space is between an element and its number (C 6H12O6)

**Expected behavior**
El-MAVEN should ignore all spaces and calculate the correct m/z based on the formula

**System (please complete the following information):**
 - OS: MacOS
 - Version v0.9.1

**Comment by saifulbkhan** [comment]
This might get fixed with #1168. Although I had not specifically tried spaces, it is supposed to filter out all non-alphanumeric characters.

**Comment by saifulbkhan** [comment]
This should not be a problem anymore in v0.10.0.
