### ISSUE TITLE
unable to start concurrent sessions on version 0.9 and above

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#1215]
Starting another instance when one is already running leads to the following error. This happens to me on both 0.9 and 0.9.1 that I installed using the packaged installer, but not with 0.8 which I compiled myself.

This is on windows server 2016. 

Seems like a permissions issue with the log file.

![image](https://user-images.githubusercontent.com/13080968/73194734-a6a42b80-40fa-11ea-978e-f44e3d5601ad.png)

**Comment by saifulbkhan** [comment]
@chubukov Sorry about this. We are aware and have identified the cause of this issue. It will be fixed this with v0.10.0 (expected mid February).

**Comment by saifulbkhan** [comment]
Should no longer be an issue in v0.10.0. Sorry about this mishap.
