### ISSUE TITLE
Values in Isotope Widget should depend upon the peak table selected and not the global settings

### ISSUE THREAD

**Issue by avijitzutshi** [ElucidataInc/ElMaven#1225]
Currently, the values in the Isotope Widget depend upon the global settings and not individual peak tables. This leads to confusion wherein people shifting from one peak tale to another do not see a change in the values in the isotope widget.

**Expected Outcome**
The values for different parameters within the Isotope Widget should change with the selection of the peak table to avoid this confusion.

**Comment by saifulbkhan** [comment]
Should be available with v0.11.0. Closing.
