### ISSUE TITLE
Crash on El-Maven stable release

### ISSUE THREAD

**Issue by sajalagarwal-el** [ElucidataInc/ElMaven#1230]
El-Maven (v0.9.1) is crashing

**Steps to reproduce:**
1. Launch El-Maven (v0.9.1)
2. Click on icon "Sync EIC with current global mass tolerance"
3. See crash

**Expected behavior**
It should not crash

**Screenshots**
![Screenshot from 2020-02-13 11-11-42](https://user-images.githubusercontent.com/60999892/74405615-88a52d80-4e53-11ea-891b-b6bf91c88cb1.png)

**Environment**
 - Ubuntu 18.04.3

**Comment by saifulbkhan** [comment]
Fixed in v0.10.0.
