### ISSUE TITLE
Fragmentation events disappear if Mass tolerance lock is on

### ISSUE THREAD

**Issue by shubhra-agrawal** [ElucidataInc/ElMaven#1234]
**Describe the bug**
If I switch on the Mass tolerance lock from the EIC widget toolbar for targeted DDA peak table, the EIC stops showing the fragmentation events under the EIC. Switching off the lock brings back the MS2 markers.

**To Reproduce**
1. Import DDA data
2. Targeted peak detection with match fragmentation
3. Click on a peak from the table. The MS2 markers are visible
4. Click on the Mass tolerance switch. The MS2 markers disappear

**System (please complete the following information):**
 - OS: MacOS
 - Version: develop (cf17be29)

**Comment by saifulbkhan** [comment]
Fixed in v0.11.0.
