### ISSUE TITLE
Fix the issue where peak bubbles are floating when you perform alignment after peak detection.

### ISSUE THREAD

**Issue by sakshikukreja14** [ElucidataInc/ElMaven#1257]
When alignment is performed after peak detection, the values for the peak groups do not change accordingly. This leads to the peak bubbles which are left floating in the area.
This is a bad user experience. Thus, these peak bubbles need to align no matter alignment is performed after peaks detection or vice versa.

**Comment by saifulbkhan** [comment]
Shipped as part of v0.11.0. Closing.
