### ISSUE TITLE
Retention time line disappears on zoom out

### ISSUE THREAD

**Issue by danolson1** [ElucidataInc/ElMaven#1266]
**Describe the bug**
When I am viewing a peak, I can see the vertical dashed red line that indicates retention time. When I zoom out to see the whole time scale, the retention time line disappears. Occasionally, it seems like I do something and the screen redraws and the line is back. 

**To Reproduce**
1. View a peak
2. Zoom out

**Expected behavior**
I would expect the retention time line to be visible at all times, unless I turn it off (although in version 0.10.0, it doesn't look like retention time can be turned on and off)

**Screenshots**
See attached
![RT line not showing up](https://user-images.githubusercontent.com/5619720/78180927-80b84180-7431-11ea-87d3-ff8a14e3dcc3.png)
![RT line ok](https://user-images.githubusercontent.com/5619720/78180898-75651600-7431-11ea-91c3-42d1dc13bc52.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Version v0.10.0

**Additional context**

**Comment by saifulbkhan** [comment]
Confirmed bug. Thanks for reporting. We will fix this soon.

**Comment by saifulbkhan** [comment]
Was done in v0.11.0. RT line will stay even on zoom out.
