### ISSUE TITLE
export with RT of earliest and latest peak per group

### ISSUE THREAD

**Issue by YasinEl** [ElucidataInc/ElMaven#1305]
**Is your feature request related to a problem? Please describe.**
Regarding the "Groups Summary Matrix Format Comma Delimited" it would be great to be able to see the retention times of the earliest and latest eluting peak of each group. This would allow wo see the range over which a compound was eluting in the final table.

**Describe the solution you'd like**
Would it be possible to add that?

Thank you

**Comment by saifulbkhan** [comment]
Hi @YasinEl. Sorry, but we like to keep the "Group Summary" export for group-specific information only.

You can find values for individual peaks in the "Peak detailed" export. The two reports can be combined on the basis of "groupId" identifier, which you will find in both files (peaks having groupId=1 in peak detailed report belong to the group in group summary with groupId=1).
