### ISSUE TITLE
feature: export groups from scatterplot

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#136]
Something Gina tried to do the other day, and I was surprised it was not possible.

- Do peak picking (targeted or untargeted, but makes more sense on untargeted)
- Assign samples to sets 
- Make a scatter plot or volcano plot from your peak table, and filter groups based on log fold change or p-value
- Export just the remaining (filtered) groups.

I think best would be if you could copy the currently filtered groups to a new peak table, then you could export them to CSV from there?

Not particularly high priority, but if it's easy enough, it would be a nice feature. In terms of philosophy: I don't necessarily want to put a lot of effort into making Maven into a super intricate statistical analysis package, but I think the rudimentary features it has are very useful and should continue to be supported.

**Comment by shubhra-agrawal** [comment]
@chubukov this feature has been merged to develop. Let us know if this is what you had in mind. We will also add a "How-to" in the Wiki section for other users.

**Comment by chubukov** [comment]
@shubhra-agrawal holy cow this was from over a year ago, i'd basically forgotten about it. Anyway, it's a nice feature, thanks. I'll take a look.

**Comment by shubhra-agrawal** [comment]
@chubukov Closing this issue. [Here's a link](https://github.com/ElucidataInc/ElMaven/wiki/Introduction-to-ElMaven-UI#statistics-module) to the Statistics module intro in the Wiki.
