### ISSUE TITLE
El-Maven-v0.12.0.app can't be opened because Apple cannot check if for malicious software

### ISSUE THREAD

**Issue by lashmore** [ElucidataInc/ElMaven#1362]
Action: Tried to open unzipped EL-MAVEN app
Response:
![Screen Shot 2020-12-10 at 8 15 05 PM](https://user-images.githubusercontent.com/8303867/101848972-bebf4680-3b24-11eb-84d7-30eeef00f350.png)

Required fix: Software should be updated such that it is notarized.
Mac OS version : Catalina v. 10.15.5

Apple Support link:
https://support.apple.com/en-us/HT202491

Relevant part of article (screenshot):
![Screen Shot 2020-12-10 at 8 15 19 PM](https://user-images.githubusercontent.com/8303867/101848938-abac7680-3b24-11eb-9f1e-b4d6fa557294.png)

**Comment by saifulbkhan** [comment]
@lashmore Thank you for adding all the details. We will follow these steps for our next release.

Maybe you already know this, but you can still execute the installer (El-MAVEN.app) by right-clicking on the item and selecting "Open" from there. A second dialog with the same warning will appear but this time with an option to run it anyway.

**Comment by lashmore** [comment]
Looking forward to the next release. 

Just for information, I did the right click-->Open, but it didn't change the behavior and didn't give me the option to run the installer anyway.

**Comment by lashmore** [comment]
I found a way around this issue. Catalina has higher permissions requirements that previous Mac versions. Once I added EL-MAVEN to the list exceptions, I could install the application.
