### ISSUE TITLE
request access to old versions of ElMaven

### ISSUE THREAD

**Issue by redbluewater** [ElucidataInc/ElMaven#1364]
Version 0.11 worked quite well on my computer (Windows 10). However, upgrading to version 0.12 caused a massive slowdown in performance (try to delete one peak found .... wait a few seconds), so I would like to go back to version 0.11. In addition to providing the latest version, I would appreciate access to older version so I can backtrack as needed.

**Comment by saifulbkhan** [comment]
Sure. We put the latest builds on our official website, but you can always find any of the older releases the "[Releases](https://github.com/ElucidataInc/ElMaven/releases)" page of this repository. At the bottom of each release's notes, you will find some "Assets" attached. The "exe" is the installer for Windows and the "zip" contains the installer for macOS. You will find the same on the [page for v0.11.0](https://github.com/ElucidataInc/ElMaven/releases/tag/v0.11.0).

**Comment by redbluewater** [comment]
Excellent. I am sorry that I missed that. I looked at the 'releases' page, but I missed the link to 'assets'. This is my mistake. Thanks for providing them.
