### ISSUE TITLE
feature idea (very low priority): allow delta m/z in mDa as well as ppm

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#137]
It happens a lot when I'm looking at issues related to mass accuracy or isotope separation that I'm more interested in using a cutoff that's a specific mass delta than a relative (ppm) measure. I'm imagining a version where near the ppm box you can have a dropdown to choose "ppm" or "mDa". 

Would affect every place that a mass slice is calculated, so it would be a pretty big time-consuming (but probably not particularly challenging) effort.

**Comment by chubukov** [comment]
@sahil21 Just curious, whatever happened to this feature? I seem to remember a pull request that almost finished it. Maybe it was further away than I thought.

We're going to be using Maven for TOF data in the very near future, so this would be a nice feature. Still not critical, but I'd say a low/medium-priority enhancement.

**Comment by sahil21** [comment]
@chubukov This feature was not implemented completely. There were a couple of issues in that branch. We can include this in the next sprint if it is a higher priority.

**Comment by shekhjha** [comment]
I would suggest including this in the sprint as soon as possible. @sahil21

**Comment by sahil21** [comment]
@shekhjha I'll include this in the current sprint then

**Comment by chubukov** [comment]
@sahil21 @shekhjha ok, that's great. Let's make sure we get this right though -- don't rush to get it in you're not sure.

**Comment by sp-eldata** [comment]
@sahil21 Lets be careful about adding features in the same sprint - hot fixes are fine.

**Comment by sp-eldata** [comment]
@chubukov, @shekhjha Just checking if this feature is important right now. @chubukov has started working with TOF data now (we discussed in last meeting) - so this might have moved up in priorities.

**Comment by IpankajI** [comment]
@chubukov @sp-eldata @shekhjha @sahil21 
mDa mass cutoff unit is added along with ppm unit which can be chosen from dropdown.
1. ppm primitive type (float) is replace with one custom type (MassCutoff) which can be used for mass  cutoff type that could be either in ppm or mDa
2. Based on user selection of ppm or mDa from GUI, this class (MassCutoff) method can give value of mass cutoff- mDa/10^3 for selecting mDa and mz*ppm/10^6 for ppm selection
3. mDa support is not enabled for CLI version of ElMaven

Idea for replacing float type with custom type came while thinking about adding another unit for mass cutoff in future, which can be done very easily.

**Comment by chubukov** [comment]
@IpankajI mostly sounds good, thanks!

What does it mean that this feature is not supported in csv export? I'm thinking of the info in the csv and I don't see how it would depend on this. Are you thinking of the ppmDist value? Totally fine if that remains unchanged. Same question for mzroll I guess.

Any plans to enable it for the CLI?

**Comment by IpankajI** [comment]
@chubukov 
Yes we're thinking to give info in csv that can help to check whether ppm or mDa has been used to calculate ppmDist value. It will make more sense to user of this file.We want to add info in mzroll such that used mass cutoff unit for this file can be identified.

we've not decided if we're adding mDa support for CLI yet. We'll keep you updated.

**Comment by chubukov** [comment]
@IpankajI I would recommend implementing #237 and then you can just include the actual slice bounds in the mzroll instead of trying to recalculate them based on the cutoff and type.

In the csv, if the column stays as ppmDist (which is fine) then I don't see why it should change with how the slice was calculated.

**Comment by shubhra-agrawal** [comment]
@chubukov I've created a new issue for mDa in CLI. Closing this one!
