### ISSUE TITLE
Edits are not saved in Peak Editor for certain compounds

### ISSUE THREAD

**Issue by kehj215** [ElucidataInc/ElMaven#1393]
**Describe the bug**
When I'm working through a batch, certain compounds that definitely, absolutely have a peak are not integrated. When I manually select the peak in the peak editor, change the thresholding, alter the integration window, then click apply edits, the edits don't save. This only happens for certain compounds- others in my batch are totally unaffected.

**To Reproduce**
1. Bookmark a compound
2. Click peak editor
3. press "C" to create a peak
4. change threshold and RT window to encompass peak
5. click apply edits
6. Click peak editor again, see that no edits have been applied.

**Expected behavior**
Edits to my peak I created are saved after clicking "apply edits"

**Screenshots**
attached.

**System:**
 - MacOS Big Sur 11.2.3
 - I've been using the developers build for Big Sur: https://elmaven-installers.s3-us-west-2.amazonaws.com/Mac/El-MAVEN-develop.zip

**Additional context**
I am totally new to El Maven and trying to learn so it could very well be that I am the one causing the issue, however because I am able to apply edits for other peaks I'm less inclined to think so.
<img width="779" alt="Screen Shot 2021-03-30 at 11 35 38 AM" src="https://user-images.githubusercontent.com/80782500/113016574-9ea3a980-914c-11eb-8710-136fe4268f87.png">
<img width="776" alt="Screen Shot 2021-03-30 at 11 35 57 AM" src="https://user-images.githubusercontent.com/80782500/113016575-9ea3a980-914c-11eb-8ba0-0bec036c0854.png">
<img width="826" alt="Screen Shot 2021-03-30 at 11 36 20 AM" src="https://user-images.githubusercontent.com/80782500/113016577-9ea3a980-914c-11eb-8f50-8c67b8eef1ce.png">

**Comment by saif-el** [comment]
@kehj215 I suspect this may not be a bug. Looking at this peak, it seems to me that it is likely being classified as a "bad" peak and being discarded even if you manually integrate it and "Apply edits".

To check whether this is the actual issue, you can turn down your quality threshold in "Peak filtering" settings tab:
![Screenshot 2021-03-31 at 11 12 16 AM](https://user-images.githubusercontent.com/77447361/113096174-5cdd3680-9212-11eb-8e1e-c7fe7f45bd3f.png)

After doing that, if you are still unable to get these to show up after editing integration, then this is something we should look into.

**Comment by saif-el** [comment]
@kehj215 One more thing, you might have to re-integrate the entire peak-group, after reducing quality thresholds. This is because once a peak-group is created, it gets frozen with its own copy of settings - which for your original peak-group would have the original quality threshold and changing the global peak-filtering settings will have no effect on its peak-editing.

You can get a log of what settings a peak-group has been integrated with by selecting that peak-group in the table and clicking the "Settings log" button:

![Screenshot 2021-03-31 at 11 31 32 AM](https://user-images.githubusercontent.com/77447361/113097667-f4dc1f80-9214-11eb-8ec3-5c18b095ac00.png)

**Comment by kehj215** [comment]
Unfortunately my minimum peak quality was already set to 0 so it doesn't look like that's it.

I'm also realizing that if I apply edits for a peak that is recognized, that also deletes the peak.

**Comment by saif-el** [comment]
In that case, would it be possible to share that one sample's mzML/mzXML file over email? This will allow us to narrow down on the issue faster than making guesses.

**Comment by kehj215** [comment]
Yup you got it! Thanks!

**Comment by saif-el** [comment]
@kehj215 The fix has been deployed. You can use the same link to download a newer build, or wait for it land in the main v0.12.1 release (which we are trying to send out within this month).

**Comment by kehj215** [comment]
Great! I downloaded the newer build and it's working. Can't wait for the main release. Thanks so much!
