### ISSUE TITLE
Mac version does not open

### ISSUE THREAD

**Issue by jiwoon-hwang** [ElucidataInc/ElMaven#1408]
Hello, I just downloaded El-MAVEN on to my MacBook Pro (macOS Big Sur Version 11.4). After installation, El-MAVEN doesn't open at all- it just gives me a spinning beach ball and "Application is not responding".

**Comment by saif-el** [comment]
Hi @jiwoon-hwang. The last release of El-MAVEN version does not work on Big Sur. Please see issue #1376 for more information. I am closing this as duplicate.
