### ISSUE TITLE
El Maven will not open in MacOS Monterey

### ISSUE THREAD

**Issue by grangel0955** [ElucidataInc/ElMaven#1412]
The software does not open when using MacOS Monterey. Is there a beta version accessible that has been developed for Monterey?

**Comment by ShawnWx2019** [comment]
same issue. 
It works on MacOs Monterey 12.0.1! pls download this version:
[El-MAVEN-develop.zip](https://elmaven-installers.s3-us-west-2.amazonaws.com/Mac/El-MAVEN-develop.zip)
