### ISSUE TITLE
Looking for a documentation of areaTop value

### ISSUE THREAD

**Issue by sorenwacker** [ElucidataInc/ElMaven#1417]
Hi, 

I would like to know who El-Maven defines the `AreaTop` value. I looked in the [documentation](https://elmaven.readthedocs.io/en/documentation-website/search.html?q=areatop&check_keywords=yes&area=default), but could not find that information.

**Comment by shubhra-agrawal** [comment]
AreaTop is the smoothened maxima of a peak. Mean value of the actual peak maxima and 1 neighbouring point on both sides of the maxima.

**Comment by sorenwacker** [comment]
Thank you!

**Comment by sorenwacker** [comment]
When I try to reproduce these values, I find this phenomenon:
![image](https://user-images.githubusercontent.com/3391614/207148195-b1e07967-ae0a-451e-8a30-61a0a27f546c.png)
It looks like El-maven applies baseline correction as well. Is the reason for this behaviour? 
What you see here is the reimplementation of your areaTop score, but in some cases a constant value is removed for a set of files resulting in smaller values as compared to blindly applying the algorithm. Often the value is very similar for groups of files. Sometimes, there are multiple steps even for different groups of files.

**Comment by sorenwacker** [comment]
Actually, it only looks like a linear offset in log-scale. Linear it looks like this:
![image](https://user-images.githubusercontent.com/3391614/207437318-71246acf-d4a1-47b2-bbf9-72fbc05960b1.png)

**Comment by sorenwacker** [comment]
Do you have any idea where this discrepancy might come from? Is it a baseline correction? But why then this linear dependency on the areaTop value? It looks like El-Maven always divides by 3, even if there are only 2 or 1 datapoints in the extraction window.

**Comment by shubhra-agrawal** [comment]
Baseline correction happens before any peak detection in El-MAVEN. Just to correct for technical noise across samples. 
We use a simple quantile method for baseline correction, where we smoothen the peak and set the baseline based on the user-set threshold.
PeakAreaTop by default shows the corrected intensity. There is another option for AreaTopNotCorrected that can be used to get the true PeakAreaTop value without the basline correction.

> It looks like El-Maven always divides by 3, even if there are only 2 or 1 datapoints in the extraction window.
That might be a bug, will have to check.
