### ISSUE TITLE
Versioning and Release Notes

### ISSUE THREAD

**Issue by sp-eldata** [ElucidataInc/ElMaven#142]
We need to start maintaining release versions and release notes for each release we make. Please see standard practices for doing both. Open Source projects typically have both. Please take this up as a priority.

**Comment by sahil21** [comment]
@sp-eldata @chubukov @shekhjha We have merged the develop branch to the master branch and tagged the master with the new release tag (v0.1.0-Beta). We'll add the release notes soon. Changes requested in the current sprint are made and merged to the master branch. Master branch can be pulled and is ready for testing. We will be testing the tool in coming two days extensively.

**Comment by suresh-surampudi** [comment]
@sp-eldata @chubukov @shekhja v0.1.1 release information is updated.
