### ISSUE TITLE
marking group good/bad in peaktable currently does not affect export

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#143]
If you do automatic compound search with isotopes enabled, and then go through and curate the peak table, marking an entire group good/bad currently doesn't really do anything -- when you do "export good", nothing gets exported, because the children aren't marked.

I think that the right default behavior should be: if the user marks a group "good", don't do anything to the children (this is fine as is). But, if the user then does "export good" and the child group is not marked good or bad, then assume it takes on the same state as the parent.

An alternative would be that marking is immediately propagated to all the children, or to just the C12 parent.

CCing @myasteadman in case she has an opinion on how this should work.

**Comment by MyaSteadman** [comment]
Hi all,
I think I would prefer the first option, if I mark the parent as good and do nothing to the children, assume that they are all good during the export. If one of the children is bad, I will mark it as such separately and then I can be excluded. Make sense?
Mya
