### ISSUE TITLE
Crash: Deleting peaks from Peaks table leads to crash

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#148]
There are few cases to reproduce this behavior:

1. Delete the peak from peaks table for the compound which has not RT in the compound database.
2. Delete any peak without marking peaks good/bad. 

The problem is in the PeakGroup.cpp file at line number 581. (if (compound) tag = compound->name;) while accessing compound->name. Both the cases are producing the error at the same line number. I confirmed this using debugger.

**Comment by chubukov** [comment]
Haven't had problems with this in a while.
