### ISSUE TITLE
why does peak finding happen without baseline subtraction?

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#153]
I'm trying to understand why Maven finds so many "peaks" within the noise of the chomatogram baseline, and if there's a parameter that controls this.

Something doesn't make sense to me about the logic of `EIC::getPeakPositions`. Currently, it simply calculates the spline, and then finds the positions of all the local maxima. Then it calculates the baseline (average of bottom x% of values) but it doesn't do anything with it as of yet.

It would make more sense to me if the baseline was computed first, and either subtracted directly, or peaks that were below baseline were at least filtered out.

Curiously, Height/AreaTop calculations do not actually take the baseline intensity into account (no idea if this is on purpose or not).

**Comment by chubukov** [comment]
I guess what I would like to try here is: in peak picking options, include a few parameters like `minSignalBaseLineRatio` and maybe `minSignalBlankRatio` that can be used to restrict peak picking (the filtering would probably be in `EIC::getPeakPositions()`?) The default values would be much more liberal than what would be typical for compound search, but it would provide some control for users that don't want a lot of spurious peaks.

**Comment by chubukov** [comment]
Since the way we calculate baseline often results in baseline=0, maybe allow minSignalBaseLineDifference instead of minSignalBaselineRatio or something along these lines

**Comment by sahil21** [comment]
@chubukov We see three issues in this, essentially :-
- Adding baseline correction to other quantitation types
- Removing peaks which are beneath the baseline level
- Use `minSignalBaselineDifference` instead of `minSignalBaselineRation`

We received a PR from you regarding the baseline correction of Area top. We are yet to review it. 
Once we have reviewed and merged your code we will get into resolving the remaining issues

**Comment by sahil21** [comment]
@chubukov I have reviewed your branch (fix_baselin). The team needs to test it before we merge it to develop. 

The "minSignalBaselineDifference" parameter is added in the code but UI is left out for now. There are lots of UI changes going on in different branches. So to avoid conflicts in .ui file we'll add the UI for this parameter at the end of the sprint when all things are merged.

**Comment by chubukov** [comment]
@sahil that sounds fine. I have a local version that merges the current develop with my branch if that's helpful (but it was pretty straightforward to sort out the conflicts)

**Comment by sahil21** [comment]
@chubukov I don't quite understand what you meant by adding peak detection options into the main options? Are you talking about "Peak Scoring and Filtering options"? 
![image](https://user-images.githubusercontent.com/21240516/28075359-e19897f8-6678-11e7-9814-92d1302dcc45.png)
These parameters are for filtering groups from a set of groups. How can we use this for manual peak picking where there is only one group? Am I missing something here? 
We have already moved "EIC Processing: Baseline Calculation and Smoothing" parameters to Options Dialog.

Are you talking something like multiQuant where we can integrate peaks with different parameters?  Even in that case how can we use "Peak Scoring and Filtering options"?

**Comment by chubukov** [comment]
@sahil What I had in mind was some functionality that doesn't really exist yet. It would basically be some options for what would be called a peak at all. The filtering would happen in `EIC::findPeaks()` or `EIC::getPeakPositions`. Currently the only parameter that affects that process is the EIC smoothing window, and after that, the reported peaks are simply all the local maxima of the smoothed EIC. It would be nice to be able to say that only some of those local maxima should be called "peaks". This can help with eliminating very small noisy peaks, which can in turn improve grouping.

Does that make sense?

**Comment by sahil21** [comment]
@chubukov Got it. Thanks. I was thinking more in the sense of group filtering rather than peak filtering. Indeed, it would be a nice feature to have.

**Comment by chubukov** [comment]
@sahil21 For what it's worth, `SignalBaselineDifference` is essentially just `heightCorrected` right? (I think we don't calculate the latter either). Just in case that helps. I think i wrote the original comments before we fixed up the baseline calculation and added `AreaTopCorrected`, etc.

**Comment by saifulbkhan** [comment]
> It would make more sense to me if the baseline was computed first, and either subtracted directly, or peaks that were below baseline were at least filtered out.

At least the latter option has been implemented to some extent. Closing this as resolved for now.
