### ISSUE TITLE
peak table disabled after minimize/restore

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#155]
At least on windows, minimizing and then restoring the Maven window causes peak tables to become disabled. Easy to bring them back, but it's a little disorienting.

Doesn't happen with bookmarks table.

@myasteadman

**Comment by chubukov** [comment]
This still happens in the QT5 version.

**Comment by chubukov** [comment]
@sahil21 As far as I can tell, this is fixed? At least it works fine for me.

**Comment by sahil21** [comment]
@chubukov Yes, it has been fixed with #154. Closing this one.
