### ISSUE TITLE
Clang in macOS (by default) doesn't support openmp

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#16]
Add instructions to install OpenMP for clang.

**Comment by GeorgeSabu** [comment]
@sahil21 Have to make it compile in Mac too.

**Comment by rish9511** [comment]
To make the code compile on Mac Os lib opnenmp has been disabled for mac. 
The commit 5a53a1fcce4f685f0f12da2f1cce5a5ba4f74ac6 has fixed this
