### ISSUE TITLE
marking in peaks table: enable "unmark" and also "export good+unmarked"

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#171]
Some additional features that might be nice:

- be able to remove a good/bad mark
- be able to export good+unmarked 

As suggested by Swetabh, the second one could be part of a massive overhaul where you can filter the table however you like before export, but I think this simple fix would be useful.  In a sense, setting the peak picking parameters is how you pre-filter the table by mass, intensity, etc.

Suggested by @myasteadman

**Comment by lparsons** [comment]
This would be very useful for us as well. It's quite annoying when one accidentally marks a peak as good/bad but in reality I haven't made a decision (it's an undecided or unclear peak). Having peaks unmarked is the only way to keep track of that situation at the moment.

**Comment by saifulbkhan** [comment]
@chubukov Both your requests - unmarking a marked peak and exporting all peaks excluding the bad ones - are now available in v0.10.0.
