### ISSUE TITLE
Crash: Bookmarking group from Automatic peak detection table and then going back to isotope of the same group (in automatic peaks table) leads to crash

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#174]
Steps to reproduce:
1. Do Automatic peak detection
2. Select any group from the peaks table
3. From the EIC widget, bookmark the group by double clicking.
4. Go to the same group in the peaks table (Obtained from the automatic peak picking).
5. Iterate through the isotopes of that same group. This step will lead to crash.

This crash is there in build 776 and elMaven but not in build 682.

**Comment by chubukov** [comment]
@sahil21 This seems to work fine for me -- not sure who reported the original issue, so up to you to close if you want.

**Comment by sahil21** [comment]
@chubukov This has been fixed. Closing it.
