### ISSUE TITLE
Crash: Changing options when no groups are present

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#18]
Reported by @chubukov on Trello board.

Here's one I was able to reproduce and partially debug.
1. Load some files and manually pick a peak
2. Delete the peak in the bookmarked table
3. Hit options and change an isotope lableling checkbox

This will crash because it tries to call pullIsotopes on the currently displayed group, except that the group has been deleted, so some of the pointers are now invalid.

I think this just needs better checking on what's currently being displayed.

**Comment by GeorgeSabu** [comment]
@sahil21 I am not able to reproduce this on the updated develop can you please confirm this.

**Comment by sahil21** [comment]
@GeorgeSabu It was crashing some days ago. Previous changes fixed the issue. We can close it now.
