### ISSUE TITLE
Data output: Maintaining sample order and "not detected"

### ISSUE THREAD

**Issue by smd10** [ElucidataInc/ElMaven#183]
It would be helpful if the sample order was maintained in the output and also if there were a string or possibly a negative integer used for placeholders when metabolites are detected in some samples but not others (currently, MAVEN output drops the sample from the data output).

**Comment by chubukov** [comment]
I'm just curious what kind of output we're talking about. In my experience, in the .csv output, the sample order is maintained, and 0 is put for metabolites that are not detected in particular samples.

**Comment by shubhra-agrawal** [comment]
@smd10 as @chubukov mentioned, CSV output has both the features you have mentioned. In addition, we have recently changed the .CSV to output 'NA' if a sample has not been used, 0 if the metabolite is not present in a sample and the intensity if there is a peak in that sample.

Are you still facing this issue in CSV output? If not, we'll close it. Help us understand if you meant something else though.
