### ISSUE TITLE
no isotopes in barplot or bookmark if checkbox is disabled in peak detection dialog

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#185]
You don't get any isotopic species bookmarked or showing up in the barplot if the "report isotopic peaks" checkmark is disabled in the peak detection dialog.

Is this intentional? I thought the idea was that the options in the peak detection dialog box would only affect the automated search, and everything related to GUI behavior would be in the main options.

I'm working off the develop branch as of 3/22.

**Comment by sahil21** [comment]
@chubukov Yes, this feature was intentional. But having another option in the "Options" Dialog to disable isotope detection makes more sense. We'll fix it as soon as possible.

**Comment by chubukov** [comment]
Probably irrelevant if this is being fixed, but just wanted to note that there's also an initialization bug here. When you first open Maven, you have to uncheck and recheck the box to get isotopes to show up in the barplot and manual bookmarking.

**Comment by shubhra-agrawal** [comment]
@chubukov The initialization bug has been resolved and merged. We will look into moving the option out of Peaks dialog in the next release.

**Comment by shubhra-agrawal** [comment]
@chubukov Just wanted to note that the barplot is independent of the checkbox now. (v0.4.0 and above). 

With respect to moving Report isotopic peaks out of the "Peaks" dialog, we have decided on a design for it. Should be out in the next few releases once we do a feedback session on the new designs. I'm leaving this open till then.

**Comment by saifulbkhan** [comment]
Closing this since all issues discussed here have been resolved. A dedicated dialog has been added to the main toolbar in El-MAVEN v0.9.0.
