### ISSUE TITLE
feedback button doesn't do anything

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#186]
At least for me (on Windows), clicking on the bottom right button (the one that used to be a bug and now looks like a diagonal hourglass) doesn't have any effect.

**Comment by sahil21** [comment]
@chubukov What do you mean by "doesn't have any effect"? Is it not showing the below Dialog box

![feedbackdialog](https://cloud.githubusercontent.com/assets/21240516/24235830/027fb97a-0fc5-11e7-849b-d779ceb630c6.PNG)
 
This screenshot is from a Windows machine.

**Comment by chubukov** [comment]
Correct, nothing pops up.

Is this because I didn't put in an AWS key at the beginning?

**Comment by sahil21** [comment]
@chubukov In your /bin folder, is there an executable with the name CrashReporter.exe ? If that is not there then this feedback button won't work.

**Comment by chubukov** [comment]
@sahil21 Ah, didn't realize that. Now I see that there was an error during build. Will open a new issue.
