### ISSUE TITLE
crashReporter build error

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#188]
cause of #186 

`cd CrashReporter/ && ( test -e Makefile || C:/Users/victor.chubukov/msys2/mingw64/bin/qmake.exe -o Makefile C:/users/victor.chubukov/Documents/ElMaven/CrashReporter/CrashReporter.pro CONFIG+=release ) && make -f Makefile
make[1]: Entering directory '/c/users/victor.chubukov/Documents/ElMaven/CrashReporter'
make -f Makefile.Release
make[1]: *** [Makefile:34: release] Segmentation fault
make[1]: Leaving directory '/c/users/victor.chubukov/Documents/ElMaven/CrashReporter'
make: *** [Makefile:523: sub-CrashReporter-make_first-ordered] Error 2
`

**Comment by sahil21** [comment]
@chubukov I tried reproducing this error but I was not able to do so. I used both Linux and Windows to do so. Could you try compiling the code in a new directory or just remove the Makefiles from the current directory?

**Comment by chubukov** [comment]
@sahil21 Deleting all the makefiles fixed the problem. Thanks for the hint!
