### ISSUE TITLE
Automatic Crash Reports

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#19]
Right now there is nothing like automatic crash reports in El Maven which can provide crash reports like stack trace of that crashed instance.

**Comment by GeorgeSabu** [comment]
@chubukov some form of automatic crash reporting is now in place. Now its working fine in ubuntu system. The same code should work without much problem in windows. Will update you soon on that progress. The wording that is shown is copy paste from another tool, we have to modify it for our usage.
![el-maven crashreporter_005](https://cloud.githubusercontent.com/assets/22674403/20851158/adc213ea-b904-11e6-8987-bd9d27dda9a7.png)

**Comment by chubukov** [comment]
@GeorgeSabu Cool, this will already be useful. Are you able to capture the stacktrace in any useful way?

Let's fix the typos (discrition should be description). And presumably we are not yet in a position to restore the last session (nor is it clear to me that it's necessarily a good idea to try to do this automatically).
