### ISSUE TITLE
Isotopomer analysis

### ISSUE THREAD

**Issue by reidme** [ElucidataInc/ElMaven#191]
If I don't have an isotopomer list, will the "Isotope Detection Options" select the Mn (i.e. M1, M2, etc.) based solely on formulas submitted?
 
Can you explain "Minimum Isotope-parent correlation?" What does this setting do to the data search?
 
In the "Isotope Detection Options," under the "Libraries" tab should I select the same library used in the initial compound search?

In the "Isotope Detection Options," does the "Peak Detection" tab over write the "EIC Processing and Filtering" tab in the master "Peak Detection" window?

In the "Isotope Detection Options," what does enabling multiprocessing do to the data?

**Comment by chubukov** [comment]
Let me try to answer to see if I can help, and hopefully some of this stuff can go into the docs.

1. Yes, exactly.

2. Minimum isotope-parent correlation: basically it's the correlation of the intensities of the parent ion and the isotopomer ion. It's supposed to help assess how likely it is that the presumed isotopomer ion is in fact an isotopomer of the parent. So it takes the left and right edges of the peak, takes all the scans between them, calls the intensities for the parent ion for those scans vector1 and the intensities for the presumed isotopomer ion vector2, and calculates the correlation of those two vectors. If it's below the threshold, the isotopomer is discarded. Personally I do not rely heavily on this setting.

For 3-5 I think what's you're missing is that clicking the "isotope detection options" actually just brings up the same dialog box as hitting "options" in the main window. The reason that's not obvious is that it defaults to the wrong tab -- should default to the isotope detection options tab (and maybe even have the other tabs disabled? I dunno).

3. As far as I know the "Libraries" tab in the main options doesn't have any functional effect -- just the default location for searching for files.

4. The main options window set the initial parameter values for the "Peaks" dialog box, and setting them in the "Peaks" dialog box is supposed to just affect that round of peak picking, I believe. But yeah, I don't know if the behavior is carefully defined: what if you open the main options box while the Peaks box is open, and change something (e.g. smoothing window). I think the interface design could be better here.

5. As far as I know, the only place where that checkbox is relevant is for initial loading of files. If it's checked and you have a multi-core computer, it will parallelize the file loading.
