### ISSUE TITLE
Match retention time concerns

### ISSUE THREAD

**Issue by reidme** [ElucidataInc/ElMaven#192]
At what point does retention time get incorporated into identification?

Are IDs initially based on the formula or "Match Retention Times?"

What does "Match Retention Times" do with the optional time frame set?

**Comment by chubukov** [comment]
This should really be in the introductory docs, or maybe there should be some context help menus or mouseover help?

Fundamentally, the thing to realize is that by default there is almost no backward-annotation being done -- the standard mode is to take specific analytes and try to find the peaks corresponding to them.

In detail, what it does is this: 

For each compound in your list, it figures out the m/z or transition to look for (based on formula if you provide one), pulls out the EIC, and finds all the "peaks", considering all the samples. It then merges those into "groups", where each group consists of one peak per sample.

Then it tries to figure out which group is the right one. First, if you have "match retention times" enabled, it throws out anything where the peak is more than X minutes away from the expected retention time (you set X in the box next to the "match retention times" checkbox). Then, if there are still multiple groups, it ranks them according to a formula that takes into account the maximum (across samples) intensity, the maximum peak quality, and the mean difference between the observed retention time and the expected retention time. One recently added feature allows you to modify the relative weights of those three factors.

After the ranking, it retains the top X groups, where X is set at "Limit Number of Reported Groups per Compound" and discards the rest.

**Comment by suresh-surampudi** [comment]
User manuals will be updated for clear understanding the workflows. Thank you for the comments.
