### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by shekhjha** [ElucidataInc/ElMaven#194]
More details on Readme. Minimal information right now.

**Comment by suresh-surampudi** [comment]
Readme document currently being updated and next version will have detailed information.

**Comment by shubhra-agrawal** [comment]
@shekhjha @chubukov @sahil21 Following elements have been added to README.md:
- updated installation instructions for Windows, Ubuntu and Mac OS
- travis build status
- updated contributors list
