### ISSUE TITLE
crash if database file is malformed

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#2]
When I accidentally had fewer than the expected number of fields in one line of the database file, Maven crashed when trying to load it. Probably need to fail more gracefully here, or accept the incomplete entry in some way.

To reproduce, put in just the compound name as the only field.

**Comment by GeorgeSabu** [comment]
@chubukov Sorry for the delayed reply we will look into this and solve.

**Comment by GeorgeSabu** [comment]
@chubukov We were able to reproduce the error only when the compound name was present and it didn't have a comma at the end. If comma was present at the end of the compound name it didn't crash. Is this the crash that you saw? We will make this crash handling gentle.

**Comment by GeorgeSabu** [comment]
@chubukov This error was due to a spelling mistake. This was there all the version of MAVEN. "formula" was spelled as "formala" in the database.cpp file under the function loadCompoundCSVFile()

**Comment by GeorgeSabu** [comment]
@chubukov segfault cannot be handled by try..catch if you are thinking in that line. And it's not generally suggested to do so. Exceptions can be caught with try catch statements. So the only way is to resolve the bug causing segfault.

**Comment by GeorgeSabu** [comment]
@chubukov Another way to look at this crash is, it came because there was no check if the heading field in .csv matches the fields we are checking for in the .cpp code. So I will add a check for the same.

**Comment by chubukov** [comment]
@GeorgeSabu Of course you're right -- I wasn't talking about catching segfault, but rather checking the input before attempting to populate the database.

Ideally the program would never segfault regardless of how degenerate an input file the user passes in (should generate message that file was malformed). Given that this is niche software, that's not the most critical priority though.

**Comment by GeorgeSabu** [comment]
@chubukov Got your point. Checking header will be one form of check.

**Comment by GeorgeSabu** [comment]
@chubukov We have added a check to see if the headers in the compound database are what is desired.
