### ISSUE TITLE
Discrepancy between the mass shown in the EIC window and the part where all metabolites are shown

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#20]
Victor:
This bug is due to the following behavior:

The way that the group mz is calculated is that it's an average of the mz value for each peak, which in turn is the mz of the scan with the highest intensity for that peak (within the mz and rt window). However, if for a particular sample there are no scans with intensity>0 (after baseline correction), the mz reported for that peak will be zero. That zero will be averaged with the correct mz values for the other peaks, leading to the nonsensical result.

To reproduce the behavior, load some samples with extremely low intensity and some with normal intensity, set "drop top X baseline intensities" to 0 in the options, and integrate a few peaks. I bet you will see some of them reported as mz=0 for the blank samples. (If it doesn't work right away, I'll make up a minimal working example).

The faulty code as far as I can tell is in EIC\* mzSample::getEIC(float mzmin,float mzmax, float rtmin, float rtmax, int mslevel) (though I suspect that the SRM or MS/MS versions also have similar problems). You can see that the innermost for loop is structured such that if there are no scans with intensity > 0, __maxMz will remain zero.

I believe that a trivial fix will be to initialize __maxIntensity to a negative number instead of zero. Another solution, which would also handle the degenerate case of no scans at all, would be to leave that part as is, but in the code that computes the average for the group, ignore the zero values. I believe that happens in void PeakGroup::groupStatistics() but I'm not 100% certain.

I was waiting to fix this until we had a better write-up of the workflow of the algorithm when it might be easier to understand any unintended consequences of this. I would be ok with just implementing a fix if we had a good set of tests to run.

**Comment by GeorgeSabu** [comment]
@sahil21 Can you try reproducing this issue. I am sure it will be there.
Make sure that we have a dataset and the procedure to reproduce this issue captured here.

**Comment by sahil21** [comment]
@chubukov I'm not able to reproduce this bug. Could you provide me the dataset to reproduce this bug?

**Comment by chubukov** [comment]
@sahil21 Yes, I will try to do this asap. 

But if you look in the code I'm referring to, it should be clear that there is a logic flaw, so perhaps you can anyway start looking at how best to fix it. It should be possible either to fix the loop so that __mzintensity is properly set, or to fix the code that calculates the group mz.

**Comment by sahil21** [comment]
@chubukov I think the safer way to fix this would be to change the way mzMean is being calculated in groupStatistics function. Fixing the code further upstream can affect other processes also.

**Comment by sahil21** [comment]
@chubukov Are you able to reproduce the bug?

**Comment by chubukov** [comment]
@sahil21 Sorry I forgot about this.

I just tried, and I was not able to reproduce this behavior.

Did you already make the changes to mzMean? If they look logical I think we should keep them anyway.
