### ISSUE TITLE
bookmarked peaks disappears

### ISSUE THREAD

**Issue by collinhill** [ElucidataInc/ElMaven#203]
The bookmarked peaks window will disappear when you try to merge it with other widgets, i.e. merging it with the samples/compounds tabs.  The bookmarked peaks cannot be retrieved after this.  Oddly, it only happens with the bookmarked metabolites identified through the peak detection feature.

**Comment by GeorgeSabu** [comment]
@collinhill This issue is there because peak tables are created dynamically after peak detection is done. This issue will be resolved in the coming release.

**Comment by chubukov** [comment]
Just noting this is duplicate of #154.

**Comment by chubukov** [comment]
I believe this is working fine now? -- maybe @sahil21 can confirm.

**Comment by sahil21** [comment]
@chubukov @collinhill This is working in the current develop. I'm closing this issue.
