### ISSUE TITLE
Y-axis scaling

### ISSUE THREAD

**Issue by collinhill** [ElucidataInc/ElMaven#205]
As displayed below, ElMaven has some issue with y-axis scaling

![maven scaling](https://cloud.githubusercontent.com/assets/26555162/24881419/b2b5ff12-1e0b-11e7-801a-5dbc304f12b0.png)

**Comment by GeorgeSabu** [comment]
@collinhill Thanks for reporting. This issue is a duplicate of #135. We are working on it and it will be resolved in the coming release.

**Comment by sahil21** [comment]
@collinhill Closing this one. Duplicate of issue #135
