### ISSUE TITLE
Picked peaks( good and bad ) are not showing from autosaved files.

### ISSUE THREAD

**Issue by sonu-jun3** [ElucidataInc/ElMaven#206]
Steps to reproduce
1. Load autosaved files( xyz-autosave.mzroll, xyz-autosave_bookmarked.mzroll )
2. Loads files
3. Click on peaks icon

**Comment by sahil21** [comment]
@sonu-jun3 Click on the "Bookmark" Icon on the right-hand side.
The icon looks like this : 
![showbookmarks](https://cloud.githubusercontent.com/assets/21240516/24893408/1a91fb14-1ea1-11e7-88b8-312f3e62b90e.png)

**Comment by sonu-jun3** [comment]
@sahil21 thanks for your help figuring it out.
closing this issue.
