### ISSUE TITLE
Table 2 wants a better name :) 

### ISSUE THREAD

**Issue by sp-eldata** [ElucidataInc/ElMaven#208]
PFA the screenshot. Table 2 has been unhappy about this for some time :( 
![table 2](https://cloud.githubusercontent.com/assets/22666033/24893574/13798de6-1ea2-11e7-9cef-b7ab8bbbe5dd.png)

**Comment by sp-eldata** [comment]
Also, how does one get this back once it has been hidden?

**Comment by rkdahmiwal** [comment]
@sp-eldata  At present, table titles follow a generic naming conventions provided by the application. Custom titles will be featured in future sprint where user will be able to custom the title of the table
To hide or view a table, please click on the desired table icon again in the right side panel (side bar on right side of the application).
