### ISSUE TITLE
Need onboarding and quick tip

### ISSUE THREAD

**Issue by sonu-jun3** [ElucidataInc/ElMaven#209]
As I was unable to figure out how to recover autosaved peaks. It would be helpful to have something like quick-tip and user onboarding which helps you understand features of El-Maven.

**Comment by suresh-surampudi** [comment]
Thank you for the comment. Elmaven will have quick start examples and  detailed work flows in coming sprints. Please watch this space for more exciting features.

**Comment by sahil21** [comment]
@sonu-jun3 Refer to [Github Wiki](https://github.com/ElucidataInc/ElMaven/wiki)
