### ISSUE TITLE
Store or link compound database in mzroll file

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#21]
Right now loading an mzroll file into Maven will not load/display the peak integration information unless you have the right compound list preloaded. This information should really be stored together with the mzroll file (it's reasonably small relative to the rest of the file, so could even be embedded). This would dramatically improve the utility of storing the mzroll file.

**Comment by GeorgeSabu** [comment]
@sahil21 I have added this feature on the branch  ftr_CompoundDBMZroll. Please see if I have all the fields exhaustively.
