### ISSUE TITLE
Exporting from .mzroll file to (peaks detailed) .csv format gives a constant value in the 'quality' column 

### ISSUE THREAD

**Issue by shefalilathwal** [ElucidataInc/ElMaven#215]
I am working with an LC-MS/MS dataset. When I open a saved .mzroll file and export the data into Peaks Detailed Format Comma Delimited (.*csv) format, the column titled 'quality' shows a fixed value of 0.306 for every fragment in every sample.
If I work with the sample files directly, i.e., upload the sample files, perform peak picking and export them in the peaks-detailed .csv format, the above issue does not occur.

**Comment by suresh-surampudi** [comment]
Thanks for reporting this and we have identified the cause for this issue. We are fixing it now and will be sent for testing, after fixing.

**Comment by shubhra-agrawal** [comment]
@shefalilathwal Unable to reproduce this in v0.8.0-beta
