### ISSUE TITLE
Peak EIC plot incorrect

### ISSUE THREAD

**Issue by Raghavdata** [ElucidataInc/ElMaven#219]
While, going through peak picking I came across a couple of peaks which were looking as if they had been abruptly chopped off or some data was missing. Interestingly, the peak seems to be fine when seen via SRM. Attaching both the screens
![peak after automatic peak selection](https://cloud.githubusercontent.com/assets/16893466/25382528/a75ce39e-29d5-11e7-9576-d605892ef130.png)
![peak as seen in srm](https://cloud.githubusercontent.com/assets/16893466/25382530/a7bf8d0a-29d5-11e7-8545-e06c36e7ff28.png)

**Comment by collinhill** [comment]
What is the difference between the two plots shown? It appears as if they are both SRM data (149--> 131).

I've seen this behavior before... was this acquired on a SciEx instrument perhaps?  My guess is you only see this on "low abundance" peaks?  We have discovered that SciEx stores zero intensity values in an interesting way, that when converted, gives rise to the jagged peaks you witness. I haven't tried it, but you may want to play around with the "zero samples" filter in MSConvert.  I believe you need to add flanking zeroes, but I'm not certain about this.

I don't believe this has anything to do with Maven at all, but the way in which your file is being interpreted and converted.

**Comment by shekhjha** [comment]
@collinhill I believe, you are right.  Need to dig deeper.
This data was acquired on SciEx instruments. And you are indeed the master of MSConvert!
