### ISSUE TITLE
Pick isotopic peaks even when parent abundance is zero

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#22]
It's come up a few times now that we do a labeling experiment and end up with 100% labeling of one or more metabolites. In this case, when you're doing automated peak picking with a database, you won't pick the parent peak and therefore the labeled peak is lost. It would be kind of nice to be able to specify that maven should look for the isotopes even if the parent isn't there. It would probably have to be a compound-specific option I think -- otherwise, the number of potential peaks completely explodes.

**Comment by GeorgeSabu** [comment]
@chubukov Can you share with the dataset with which we can reproduce this issue?

**Comment by chubukov** [comment]
This was originally my idea, but upon reflection, it's a sufficiently unusual case that it's not worth the effort to cater to it. Closing.
