### ISSUE TITLE
Blank samples do not load

### ISSUE THREAD

**Issue by shekhjha** [ElucidataInc/ElMaven#222]
A colleague pointed out that the blank samples from the mc89 vs wt.zip file [http://genomics-pubs.princeton.edu/mzroll/index.php?show=download] does not load in El Maven. 

![image001](https://cloud.githubusercontent.com/assets/4898928/25457853/b22b46c8-2aa5-11e7-8228-6cc038a0deb7.png)

**Comment by chubukov** [comment]
Other people have brought up concerns like this. It's not at all obvious that this box is only a warning.

**Comment by shubhra-agrawal** [comment]
@shekhjha @chubukov From what I understand, this warning showed up when the same runs had not been performed on all samples. For eg, if there was a run for 180/79 in sample 1 but not in samples 2, 3 and 5, El-MAVEN would warn the user against making the assumption that 180/79 was not found in these samples. Rather, this data was not collected in the first place.

I'm not sure how often this happens or how useful this warning was for users. If either of you think this case should be handled, we can come up with a better UX around it. For now, this warning has been suppressed.
