### ISSUE TITLE
Can we do MS/MS/MS for El Maven?

### ISSUE THREAD

**Issue by singleton-christopher** [ElucidataInc/ElMaven#223]
Are we limited to MS/MS for our experiments?  We can fragment multiple times through a variety of ways:

1. using in-source frag and then regular CID for MS/MS on the Q-TOF and QE
2. on the Thermo Fusion
3. Using EI on the GC-MS to fragment in-source before proceeding to MS/MS

Curious if this is a simple add or if this is more intensive.  I'd like to try it sometime if Maven has the tools to process it.

**Comment by chubukov** [comment]
Short answer is that this would be a pretty major change/rewrite. But if it keeps coming up, maybe it's worth doing.

If you're monitoring a limited number of transitions, then it may be possible to coerce the data into something that looks sort of like MS/MS, in which case we could use the existing tools.

I'm curious about something though: do you know of any good tools to visualize or interactively process MS/MS/MS data? I don't have a clear idea in my head of what it should even look like to process MS/MS/MS with Maven. If you know of some software that does it well, or if you even can sketch out what would be useful to you, it would be a good starting point (and I'd have the same exact comment for ion mobility or other 2-d separation techniques).

**Comment by singleton-christopher** [comment]
Well, I usually use the vendor software for doing anything more than MS/MS, but that was before I had access to tools like Maven.  If it is something significant, than it is most likely not worth the effort;  I can continue to use vendor software where necessary if I'm the only one doing it (though I haven't done it here yet, I'm just seeing what tools I will need to use if we can get to that point).  

But let me think about this and determine what the best way is for this.  For the insource CID followed by MS/MS, that would actually be pretty easy, since you would simply have the first fragment mass as your 'parent' in Maven, and your second fragment as your '1st fragment' in Maven.  Maven wouldn't know that you already fragmented in-source, and could just be told to look for the 1st fragment as the parent.  Similar issue with the GC-MS as well, since EI is a hard source that tends to fragment anyway.

If we do multiple fragmentations in the actual mass analyzer/rail (like an Orbi  or a Q-Trap), then that would be a different matter...
