### ISSUE TITLE
CI using Travis

### ISSUE THREAD

**Issue by sp-eldata** [ElucidataInc/ElMaven#226]
Team, I think we should start doing CI. I know we had tried it earlier but stopped using it for some reasons. Can we discuss why we stopped and how can we start doing it again?

**Comment by sahil21** [comment]
@sp-eldata Travis is already integrated with this repo. But it just compiles the code and doesn't run the tests. I have to make changes in *.yml file to do so. 

We were earlier using Jenkins for CI. But when we moved to Github we stopped using Jenkins. 

You can see Travis status [here](https://travis-ci.org/ElucidataInc/ElMaven)

**Comment by sp-eldata** [comment]
Our integration should also make the latest build available on Github or our git website right?

**Comment by sp-eldata** [comment]
Is the tick next to the PR for Travis?

**Comment by sahil21** [comment]
> Our integration should also make the latest build available on Github or our git website right?

No. CI won't make builds.

> Is the tick next to the PR for Travis?

Yes.

**Comment by sp-eldata** [comment]
Then how do we make automatic builds? Might not be a priority right now.

**Comment by sahil21** [comment]
@sp-eldata We don't make automatic builds. We use some package builder to make windows installers. That package builder allows us to configure the installer. It allows configuring installer using scripts also (which will make it automatic) but that feature is paid.

**Comment by sahil21** [comment]
@sp-eldata Closing this one. Check the Travis builds here: https://travis-ci.org/ElucidataInc/ElMaven
