### ISSUE TITLE
Formula column in Peak Table

### ISSUE THREAD

**Issue by shekhjha** [ElucidataInc/ElMaven#229]
An option to have the formula column (when possible) in any given export of peak table.

**Comment by shekhjha** [comment]
Related to #190

**Comment by shubhra-agrawal** [comment]
@shekhjha @chubukov 
We have added a default formula column to CSV and JSON exports. When chemical formula is available, formula is exported to CSV and JSON
If not, the column is left blank.
#190 will be resolved in future sprints.

**Comment by shubhra-agrawal** [comment]
@shekhjha Can we close this? The issue around the columns being optional is part of #190 .
