### ISSUE TITLE
Be able to provide tolerance on expectedRt

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#23]

**Comment by GeorgeSabu** [comment]
@chubukov Could you please provide us a little description of the problem?

**Comment by chubukov** [comment]
This was from a long time ago when I was making some wishlists. The idea would be that you could specify for instance that compound A has rt 10 +/- 0.1 minutes, while compound B is 5 +/- 0.5 minutes. Right now there is one single RT tolerance option for all compounds when doing automatic pick picking.

I think upon reflection this is too high a ratio of complexity/utility.
