### ISSUE TITLE
Update Peak Detector CLI

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#230]
- CLI version of El-Maven not actively developed as El-Maven GUI version
- Sync all the new feature additions and bug fixes in GUI version with the CLI version
- Write test cases

**Comment by chubukov** [comment]
@sahil21 I haven't tried using the CLI since you made the major changes to it. Is it basically ready to go at this point or are there major features that aren't working?

Is there either a spec or an example I can reference for what the config file should look like?

**Comment by sahil21** [comment]
@chubukov The CLI version is ready to use. 

To create an example config file:
`peakdetector --defaultXML`
 This will create a "config.xml" file. You can use this as a reference file.

`peakdetector --xml /path/to/xml`
This command to use the xml file at a desired path. By default it will take "config.xml" if path is not provided.  

I'll update the help command as soon as possible. 
`peakdetector --help`

**Comment by chubukov** [comment]
@sahil21 super, that seems to work.

**Comment by sahil21** [comment]
@chubukov Closing this one.
