### ISSUE TITLE
ppm of labeled peaks

### ISSUE THREAD

**Issue by shekhjha** [ElucidataInc/ElMaven#235]
the ppm for labeled peaks are being computed using the parent mass. Can we change it to compute the ppm for the corresponding labeled form?

**Comment by chubukov** [comment]
@shekhjha can you elaborate? I'm not sure what you mean actually.

**Comment by shekhjha** [comment]
@chubukov The exported csv has a column of ppm diff which I believe is getting calculated using the parent mass as a reference even for the labeled peaks. For example,
![image](https://cloud.githubusercontent.com/assets/4898928/25870565/7dcf58c4-34d2-11e7-8cfa-08b29fee86e3.png)

the ppm difference for labeled metabolites is using the reference mass of the parent mass. I am suggesting it should use the corresponding m+n mass.

**Comment by chubukov** [comment]
@shekhjha gotcha, now I see what you mean. Yeah, that's a clear bug.

**Comment by shubhra-agrawal** [comment]
@shekhjha @chubukov  This issue has been solved and merged to develop.
