### ISSUE TITLE
peakGroup object should include pointer to mzSlice

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#237]
I can't think of an instance when a peakGroup is generated from multiple different slices. So instead of copying the compound and srmId information over from the slice object, why don't we just include the whole object (it's tiny). 

Or at the very least include sliceRtMin, sliceRtMax, sliceMzMin, sliceMzMax in PeakGroup.

This came up rethinking #234

**Comment by chubukov** [comment]
@sahil21 Nice, I see you've implemented at least part of it. That's super.

Question for discussion. Say a user bookmarks a peak with a 10ppm cutoff. Then they change the cutoff to 5ppm in the main window. What should happen when they click on the bookmarked peak?

Currently (correct me if I'm wrong), we re-pull the EIC based on the expectedMz (or averageMz) of the old peak, but with a 5ppm cutoff, because that's all we _can_ do. With the new change, it seems clear to re-pull with the 10ppm cutoff so that they see the peak that was actually bookmarked, right? What should happen to the options setting in the main window at this point, should we change it to 10 again? If so, Should we flash something to make it clear this happened (maybe a color change of the box, not like a popup).  Maybe we shouldn't change it at all. It might be a little confusing if they now bookmark a different peak from the same EIC view -- presumably they'll get the 5ppm window now.

I guess I'm leaning towards not changing the main window option in this case.

**Comment by sahil21** [comment]
@chubukov Agreed, we should re-pull the EIC using the older ppm (In the mentioned example -- 10ppm). But we should try to make it visible on the UI that we are not using the current ppm (but the older one). Something like highlighting the title text on EIC widget. Changing the value of the mainwindow ppm option doesn't seem intuitive.

**Comment by chubukov** [comment]
It looks like some work was done on this about a year ago: #686 . Were there some fundamental problems with the approach, or did it just get lost in the shuffle?

**Comment by shubhra-agrawal** [comment]
@chubukov From what I remember, there were no real blockers with this approach. @sahil21 was working on this issue at the time and it got lost during his transition out of this project. I'll take a look at his implementation and figure out a timeline for this.

**Comment by shubhra-agrawal** [comment]
@surbhipoddar Adding this to v0.9

**Comment by saifulbkhan** [comment]
The changes proposed here have been added and merged in El-MAVEN v0.9.0. All `PeakGroup` objects will contain a copy of the slice that were created from. And it is this slice that will be shown in the EIC (at the original PPM). Moreover, a tolerance sync switch has been added that allows switching between a "locked mass-cutoff" mode for peak-groups in EIC (showing the original slice and ignoring global EIC setting) and the default EIC experience.

Closing this.
