### ISSUE TITLE
Using the up/down keys in the compound widget no longer updates the EIC window

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#247]
Using the up/down keys in the compound widget or tabledockwidget no longer updates the EIC window.

Assuming that this is a result of https://github.com/ElucidataInc/ElMaven/commit/6fee2b3af6aeea8e10ad79c0c97236a807d558a4 (from #169 )

If it's hard to have both working, my preference would be to roll it back to the original behavior.

**Comment by sahil21** [comment]
@chubukov This issue has been resolved in the current develop.
