### ISSUE TITLE
mzroll sometimes doesn't populate peak table properly

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#249]
See this a lot. Not all the time, so not sure what causes it. Happens with both named and unnamed compounds.

![image](https://cloud.githubusercontent.com/assets/13080968/26649156/f0eec096-4612-11e7-88b6-fefdec1f0417.png)

**Comment by suresh-surampudi** [comment]
@chubukov Thanks for reporting the issue. Team will look into this and revert to you at the earliest possible.

**Comment by sahil21** [comment]
@chubukov We are not able to reproduce this bug. Could you please provide us more information like what are steps you followed to get this?

**Comment by chubukov** [comment]
@sahil21 emailed you one mzroll file that causes the issue for me.

I have also seen this if you have peaks in the bookmarks table and then try to run alignment with peak picking from database (it makes new entries in the bookmarks table, which have that format).

**Comment by suresh-surampudi** [comment]
@chubukov Thanks for sharing the mzroll. We are looking into the issue and will update as soon as possible.

**Comment by sahil21** [comment]
@chubukov Metabolites (groups) are clustered by their metagroup ID. If metagroup ID is 0, metabolites (groups) do not cluster together. Would you let us know the workflow you followed in creating this mzroll? This would help us understand where the metaGroupID is modified?

**Comment by chubukov** [comment]
@sahil21 a bug that erroneously sets metagroupID=0 has been around for as long as I can remember (maybe we even discussed it on the old trello board?). I'll try to find it again if I have a chance.

I think this file came from autosave, but I'm not 100% certain.

**Comment by chubukov** [comment]
@sahil21 yeah if you look through the code the metagroupId never gets incremented during peak picking or during bookmarking. It only gets incremented during the output process (and not in all output functions).

So that would suggest that any file with child groups would break the import. But I just did a quick test, and with two metaGroups with childGroups, with all the metaGroupIds equal to 0, it imported fine. So I think there might be someting else going on also.

**Comment by sahil21** [comment]
@chubukov Two functions where metaGroupId is incrementing are:
1) Cluster Groups  
2) Export/Save JSON

When a project is saved/exported in .mzroll format after clustering groups, metaGroupID incrementing is desired. In JSON export/save, metaGroupID incrementing is undesired behavior (leads to clustering of groups). 

To fix this, a new variable named "clusterId" can be used to cluster groups together and metagroupId won't be used in the clustering of groups. After fixing this issue, issue with metaGroupId being zero all the time can be addressed.
Let me know where it doesn't make sense

**Comment by chubukov** [comment]
@sahil21 Ok, I see what's going on -- metaGroupId is being used in two different ways. I thought metagroup was supposed to group isotopic species of a compound (and then that can also be used to set up the clusters in the table). But if you run clustering, then metaGroupId gets used for cluster number. Perhaps I was the one abusing metaGroupId.

I think you're right that it makes sense to separate these variables. Unless you have something else in mind, I will continue to think of metaGroupId as the parent-children grouping variable (and we should then fix the peak integration code to actually assign this variable). Feel free to suggest an alternative -- I guess the way that it's intended now is that you simply check for existence of `grp->parent`, and I guess I can assign a separate id based on this during export.

**Comment by sahil21** [comment]
@chubukov We came up with a new id **clusterId** that signifies the parent-child relationship in clustering. Thus, leaving the metaGroupId solely to represent the Isotopes in a peak group. The issue related to metaGroupId being zero during peak detection will be added as a new issue.
