### ISSUE TITLE
Handle uploading of Samples if mzroll is being generated from one computer and being used in another computer

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#25]
If mzroll is being generated in one computer and being used in another computer, El Maven doesn't handle the uploading of mzXml samples very well. It will only check the path of real mzxml files or the directory in which mzroll is present.

There should be a pop-up in case ElMaven doesn't detect mzXml samples after uploading the mzroll. It should ask for change of path where mzXML samples present.

**Comment by GeorgeSabu** [comment]
@chubukov This is done. Is updated in the latest develop.
