### ISSUE TITLE
multithread mass slicing

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#250]
It seems like some aspects of untargeted peak picking (at least the mass slicing part) would be very amenable to multithreading. Would be great to see if this is viable.

**Comment by suresh-surampudi** [comment]
@chubukov We would consider this as a possible enhancement in near future sprints, in Elmaven.

**Comment by chubukov** [comment]
Btw I was just going through some old code in our local git repo and it looks like this was worked on two years ago back in Maven++ days. No idea if it was finished. @shekhjha might know more

**Comment by shekhjha** [comment]
@chubukov Can you tell me the dates/month? I can speculate better then. :)

**Comment by saifulbkhan** [comment]
@chubukov The most time consuming step (merging) of the new slicing method is now multi-processed. The other two steps are hard to parallelize since they perform comparisons in positive and negative directions within a vector and delete elements, if required.
