### ISSUE TITLE
file selection dialog box slow to appear

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#252]
Sometimes when I click the "Open" button on the main toolbar, it takes a really long time (>2 minutes) for the file selection dialog box to appear. Has anyone ever seen this? Any ideas?

**Comment by sahil21** [comment]
@chubukov We have not experienced this issue earlier on our test systems (both Windows & Linux). Could you provide us more information about hardware and software environment you are using?

**Comment by chubukov** [comment]
@sahil21 this was on windows (and other processes were running fine during this time), but no need to troubleshoot this right now, it's difficult to reproduce. Was just curious if someone else had seen it.
