### ISSUE TITLE
Mzroll file doesn't populates Peak EIC Plot of isotopes for LCMS data

### ISSUE THREAD

**Issue by tushar-chhabra** [ElucidataInc/ElMaven#255]
On uploading Mzroll file MAVEN doesn't populates peak EIC plot of the isotopes for LCMS data.
![screenshot from 2017-06-14 12-15-41](https://user-images.githubusercontent.com/24760657/27118964-67fbdd48-50fb-11e7-8f05-eaa7d03f9b91.png)

**Comment by shubhra-agrawal** [comment]
@tushar-chhabra @chubukov This issue was not present in Maven. We need to find the commit where the bug was introduced in ElMaven and fix it.

**Comment by chubukov** [comment]
@shubhra-agrawal @tushar-chhabra looks like expectedMz is not being correctly written to or read from the mzroll file?

**Comment by shubhra-agrawal** [comment]
@chubukov @tushar-chhabra There is a flag to check if isotope detection has been performed. The default value is false. This flag was not getting updated when reading group data from mzroll so it defaulted to false and EICs for the isotopes were not being pulled. This issue has been fixed and merged to develop.
