### ISSUE TITLE
export to csv: deleted groups and unchecked samples

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#261]
Possibly related to fixing #196 

- if you delete a child (isotope) group, it still gets exported when you export to CSV, though all the intensities are zero
- if a sample is unchecked, it still gets exported to CSV, with all zero values. (i mean unchecked when the peakgroup was generated, i haven't checked the behavior of unchecking after).

I think both of these are pretty misleading.

**Comment by rish9511** [comment]
@chubukov 

I wanted to understand when should the sample be exported to csv?

* should it be exported if it was used to generate peak groups?

* or should it be exported only if the sample is checked irrespective of the fact whether it was used to generate peak group or not

**Comment by chubukov** [comment]
The only behavior that I 100% want to avoid is that a group gets exported with intensity zero for particular sample when in fact that peak does not have zero intensity in that sample.

You're right that this all leads to some stupid corner cases -- check, do peak detection, uncheck in done random order will make

**Comment by chubukov** [comment]
Don't know why I can't edit comment on phone, continuing above:

You're right that this all leads to some stupid corner cases -- check, do peak detection, uncheck or the reverse will lead to some messy results. See it you can come up with something reasonably consistent, and if not, I will think about it more and comment here. I think the option of using check/uncheck for display only is a reasonable option.

**Comment by sahil21** [comment]
@chubukov @rish9511 I think we should pass "NA" in case a sample is unchecked while peak detection/grouping. Right now the user is not able to understand the difference between zero intensity of a sample or unchecked sample (they both are zero in the output CSV/TAB file). 

This will also take care of the corner case when different groups have different samples in same peaks table. This corner case can happen when the user is bookmarking peaks manually and checking/unchecking samples or in the case of merging of peaks tables.

**Comment by chubukov** [comment]
@sahil21 @rish9511 That sounds fine to me

**Comment by rish9511** [comment]
@chubukov 
There were two sub issues  in this:
- Unchecked samples should not not be exported to csv
To solve this we keep track of the samples that were used while peak detection. 
While exporting we check if the sample was used or not. If it was used we give the correct intensity, otherwise we display NA


- Deleted isotopes should not be exported to csv
The problem with this was, the isotope was not deleted from the actual list that holds the isotopes but was only  deleted from the treewidget. Hence on exporting, all the isotopes were exported
This was solved by deleting isotopes from 'deque<PeakGroup> children' , but we are currently experiencing a crash because of the new changes.Hence it  won't be pushed

**Comment by chubukov** [comment]
@rish9511 Ok. Where does it crash? Let me know if I can help.

**Comment by rish9511** [comment]
@chubukov 

Upon removing the child from the 'deque children' it crashes whenever it tries to access the compound name.
Here is the [link](https://pastebin.com/Zy8SKnAZ ) to the back trace. Hope it will be of some help 

I have been unable to understand why it's happening(why it crashes when accessing compound name). Will continue to debug this

**Comment by saifulbkhan** [comment]
Both major issues mentioned in this thread have been dealt with. Most recently, child groups (isotopes) being exported even after being deleted has been fixed in v0.9.0. Closing this.
