### ISSUE TITLE
Difference in grouping between Automatic Peak Detection and Manual Peak Detection 

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#265]
Reported by @chubukov 
I can't figure out any reason why grouping would be different between the EIC window and the automated peak detection. It looks like they both call `EIC::groupPeaks` and the parameters are taken from `settings`. Let me know if you have any guesses as to why they might produce different behaviors, and I will keep thinking about this also

**Comment by sahil21** [comment]
@chubukov 
Possible cause for this issue:
1) Parameters are duplicated in the Options Dialog and Peaks Dialog.

Peaks Dialog
![image](https://user-images.githubusercontent.com/21240516/27482331-a6932d5a-583e-11e7-81b4-49a859d886b8.png)

Options Dialog
![image](https://user-images.githubusercontent.com/21240516/27482365-cbdeb6b0-583e-11e7-8940-87a9e6071636.png)

Possible Solution:
1) Reproduce this issue by changing parameters in Options Dialog and Peaks Dialog.
2) Make parameters consistent by solving issue #217
3) If problem still persists check grouping algorithm.

**Comment by sahil21** [comment]
@chubukov I'm not able to reproduce this issue. I used same parameters for baseline calculation in Peaks Dialog & Options Dialog. Could you please try reproducing it while using same parameters in Options Dialog & Peaks Dialog?

**Comment by chubukov** [comment]
@sahil21 we discussed this last time on the phone -- I think we concluded that most likely the original issue was due to parameters not being the same between the two? Let's just make sure that we have all the parameters only in one place and logically organized, and wait to see if the issue pops up again.

**Comment by sahil21** [comment]
@chubukov Makes sense. I'll close this issue for now. If it still happens after resolving #217 then we'll reopen this issue.
