### ISSUE TITLE
MetaGroupId is zero while exporting the csv or mzroll

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#266]
In earlier versions of Maven, metaGroupID was used to group isotopic species of a compound. Right now it is not being modified in the peak detection algorithm.

**Comment by r-el-maya** [comment]
@sahil

We will have to go through the code and find where the data is being exported and where exactly, the metaGroupId is being written/read

Then we have to increment the metaGroupID accordingly.

**Comment by r-el-maya** [comment]
@sahil21 
We will have to go through the code and find where exactly the metaGroupId is being written/read.

Then we have to increment the metaGroupId accordingly.

**Comment by sunil20dhakad** [comment]
@sahil21  I am also facing same problem. I am working on LCMS data and doing isotope peak detection. There are many metabolites which are assigned to multiple peaks but when I save this in Group summary format I am not able to distinguish between these different peaks for same metabolite. If we can solve this issue then it becomes easy for us to separate peaks for same metabolites (including their isotopes).

**Comment by mayankmtg** [comment]
@sahil21 @shubhra-agrawal I have not yet seen why metagroupID has changed. It seems to be corrupted on the way being exported to the csv. However getting the isotopic parent groupID essentially performs the same role as the metagroupId. This is also in reference to an issue @lparsons mentioned #693. Please refer to pull request #707. The csv has been updated with updated metagroupId.

**Comment by shubhra-agrawal** [comment]
@sahil21 @sunil20dhakad This has been resolved and shipped out as part of v0.4-beta. Closing the issue. Re-open if needed.
