### ISSUE TITLE
Add quantile value for every filtering option

### ISSUE THREAD

**Issue by shubhra-agrawal** [ElucidataInc/ElMaven#267]
Reported by @chubukov :  I think it also makes sense to have a quantile value for every one of the peak filtering options.

**Comment by shubhra-agrawal** [comment]
We will add quantile value option for Min Signal/Blank ratio and Min Signal/Baseline ratio filters in the Peak detection dialog.
The UI will look as shown below:
![image](https://user-images.githubusercontent.com/28925846/27482508-6ab0f23a-583f-11e7-9c8a-11533344c67d.png)

**Comment by shubhra-agrawal** [comment]
@chubukov @sahil21 We have added quantile filters for signal/baseline ratio and signal/blank ratio and refactored the related code for modularity. The functions have also been documented and unit tested. UI changes will be made soon and then merged with develop.

**Comment by shubhra-agrawal** [comment]
@chubukov  Some code changes were requested during review. They have been fixed and the branch has been merged with develop. The feature seems to be working as expected. Here is what the Peak Detection dialog looks like now:

![mockup](https://user-images.githubusercontent.com/28925846/28217737-c14e4f44-68d3-11e7-99d9-ff8b821e429e.png)

Suggestions for further UI changes are welcome.

**Comment by chubukov** [comment]
@shubhra-agrawal @sahil21 Just a uithing: is it still the case that setting the quantile slider to zero means "at least one peak above the threshold?" Assuming that's true ((It seems like it from testing), maybe we can make that clear somehow in the slider description. I admit I don't know exactly how to do it in 1-2 words, I'll think about it too.

**Comment by shubhra-agrawal** [comment]
@chubukov @sahil21 Yes, setting the slider to 0% still checks for at least one peak per group. We admit this is confusing. 

This is how we are planning to change it:
![screenshot from 2017-09-19 17-31-50](https://user-images.githubusercontent.com/28925846/30591768-c3d31368-9d61-11e7-8b59-ec711fb6beb1.png)

If the slider value is zero, the UI will be as shown above. In all other cases, the corresponding percentage will be displayed.

Let us know if you have any better suggestion for getting this information across to the user.

**Comment by chubukov** [comment]
@shubhra-agrawal @sahil21 sneaky. looks fine to me

**Comment by shubhra-agrawal** [comment]
@chubukov The UI change has been merged to develop. I'm closing this issue now.
