### ISSUE TITLE
Injection Order

### ISSUE THREAD

**Issue by shekhjha** [ElucidataInc/ElMaven#275]
An interesting feature would be to keep track of injection order of the samples. Perhaps the user can import this information while uploading the samples.

**Comment by chubukov** [comment]
@shekhjha This feature (at least the part of storing the injection time and putting it in the output) was actually on my list of things to do. I agree sorting by it could be useful.

The mzXML format does not contain the injection time information. But mzML does. (At least for Thermo .raw files)

**Comment by rish9511** [comment]
@chubukov @shekhjha 

We now have the feature that allows user to keep track of injection order

For this the user will have to upload the meta csv file containing the injection order for the uploaded samples. Once the user uploads the meta csv file, samples widget will show the injection order

User will also be presented  with a warning in case if there are two or more samples with the same injection order

**Comment by chubukov** [comment]
@rish9511 @shekhjha One thing I'm not grasping: is there something special about injection order here? It seems that what you've allowed is for the user to upload some integer-valued data for each sample and sort by it, right?

Is there a plan to grab the injection timestamp from the mzML?

V

**Comment by shekhjha** [comment]
Agree with @chubukov. Grabbing injection time stamp from mzML would be the desired solution.

**Comment by sp-eldata** [comment]
@shekhjha, @chubukov: That would probably be the ideal solution. At this point can we live with this one? Let some users come back and tell us if they are using this feature heavily.

**Comment by shubhra-agrawal** [comment]
@shekhjha Please close the issue if you think it has been resolved.
