### ISSUE TITLE
Value of n in "M+n" isotope options 

### ISSUE THREAD

**Issue by shekhjha** [ElucidataInc/ElMaven#276]
Can we please make the default value of n to be 10?

**Comment by chubukov** [comment]
FWIW I would suggest default=infinity

**Comment by sahil21** [comment]
@shekhjha @chubukov We'll add this in the current release (v0.1.3).

**Comment by shubhra-agrawal** [comment]
@shekhjha @chubukov This has been merged to develop. We're closing this issue.
