### ISSUE TITLE
eic window display when there are no peaks

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#285]
I think that implementing the filtering on peaks has exposed a bug that was always present but fairly uncommon. 

I think that the EIC window y-axis is set based on the intensities of the peaks. If there are no peaks found, the y-axis gets set to [0,1], which just looks awful. I would suggesting setting it to some factor (1.2 or whatever it usually is for peaks) of the largest intensity scan in the window.

Sample screnshot:
OK:
![image](https://user-images.githubusercontent.com/13080968/28330276-f7593a10-6bba-11e7-8aee-524299e070b4.png)

Bad:
![image](https://user-images.githubusercontent.com/13080968/28330289-0674f804-6bbb-11e7-80dc-c90df10ce8ba.png)

**Comment by chubukov** [comment]
Strangely, this seems to happen even if there are peaks, but they are only barely over the threshold.

**Comment by IpankajI** [comment]
@chubukov 
The plot bounds were dependent on the highest intensity peak and the y axis was being set from 0 to 1 when there were no peaks. The plot bounds are now dependent on the highest intensity in that rt range even if it has not been detected as a peak.

**Comment by chubukov** [comment]
@IpankajI Seems to be working well, great.
