### ISSUE TITLE
peak filtering and isotopes

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#286]
Perhaps someone has an alternative view, but I think that when pulling isotopes, the peak filtering minimum intensity (aka minimum signalBaselineDiff) parameter should be either disabled or dramatically lowered. I get lots of cases where I would want to quantify the signal, but it's far below what I would expect for a parent peak.

Perhaps allowing signalBaselineRatio instead (or in addition) would allow the best of both worlds.

**Comment by IpankajI** [comment]
@chubukov 
Min Signal Baseline Difference in the Peak detection tab is used for all non-isotopic peaks. We have added Min Signal Baseline difference as a new parameter in the Isotope detection tab which can set this threshold for isotopic peaks specifically.

**Comment by IpankajI** [comment]
@chubukov  have you been able to test this fix?
