### ISSUE TITLE
peak picking/grouping with data-dependent MS2

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#287]
To keep in mind for the MS/MS sprint:

One thing I've noticed is if I load data from a method that does data-dependent MS2 acquisition, then even if I'm just trying to identify MS1 peaks, I basically never get any useful grouping at all.

I assume that this has to do with the scan numbers, either a) it's confused by the fact that MS1 scans that are consecutive in time are actually many scans apart in terms of scan number or b) between different samples, the relationship between scan number and retention time is not preserved (or both (a) and (b)).

This is a mildly unusual workflow, but it's one we like to use occasionally. It would also be the start of sort of general refactoring of Maven treats MS/MS data outside of a basic MRM method.

Eugene's version actually seems to do a much better job on this.

**Comment by chubukov** [comment]
I think I excluded explanation (b). When I load two MS1-only files that were run at different resolution (so one has twice as many scans), they load/group fine.

**Comment by sahil21** [comment]
@chubukov Could you provide us some data-dependent MS2?

**Comment by chubukov** [comment]
@sahil21 as discussed on the phone, the proteomics data in MAVEN/bug_reports/2017_02_09_proteomics_multicharge_sample_data should work well

**Comment by shubhra-agrawal** [comment]
@chubukov We used v0.1.4 to test this issue and as you mentioned, there was no useful grouping. Every peak was grouped separately even though we can clearly see they all belong in one group. This is one example for [K].LSGLSFK.[R]:
![bad-2](https://user-images.githubusercontent.com/28925846/30367254-5f8c4da0-988b-11e7-9ad4-049d9b15f4ae.png)

As mentioned in the #314 thread, there was a bug in eicMerge that was setting the minimum RT for every EIC to 0. It has recently been fixed and merged to develop. Grouping is significantly better after this fix. Here is the same compound as above [K].LSGLSFK.[R]:
![dd2](https://user-images.githubusercontent.com/28925846/30367640-5f8cda1c-988c-11e7-9926-0bf539bdf6ad.png)

Another example,
v0.1.4
![bad-3](https://user-images.githubusercontent.com/28925846/30367822-0512e65c-988d-11e7-89f2-1be6c8366d29.png)
develop
![dd3](https://user-images.githubusercontent.com/28925846/30367843-0f23ad0c-988d-11e7-8a17-985ca1a48844.png)

I am still trying to figure out why grouping in data-dependent ms2 is getting affected so much more than any other dataset. But apart from some obvious alignment issues, I'm getting good grouping in develop.

**Comment by shubhra-agrawal** [comment]
@chubukov Did you get an opportunity to test this?
