### ISSUE TITLE
keep red vertical line at expectedRt

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#288]
Now that we properly record expectedRt for bookmarked peaks, can we keep the red vertical line at expectedRt? Currently it gets repositioned to the average Rt of the peak, which is just not useful information.

**Comment by shubhra-agrawal** [comment]
@chubukov I checked the focus line for bookmarked peaks with and without isotope detection. I also checked it for bookmarked peaks loaded from mzroll file. The focus line was positioned at the expectedRt for all the peaks I checked. I'm attaching one example here:
![screenshot from 2017-07-31 12-11-29](https://user-images.githubusercontent.com/28925846/28766288-9a7c98c8-75ec-11e7-8a89-ba7789640512.png)
The focus line is at 8.1, the expectedRt for orotate.

Can you tell me help me reproduce this?

**Comment by chubukov** [comment]
@shubhra-agrawal I'm sorry, you're totally right, that part works fine. The only weird thing that happens is that if you manually bookmark a peak, the red line jumps over. But then when you click on the peak in the bookmarks table it's back at expectedRt. 

I think this might have been present in an old version and fixed with #108? Not sure, and doesn't really matter.

**Comment by chubukov** [comment]
@shubhra-agrawal this seems to be working. I was reminded of a related feature -- will open a new issue
