### ISSUE TITLE
responsiveness with peak filtering

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#289]
There's some weird performance issue happening when peak filtering is enabled. If I load ~200 samples, set the peak minimumSignalBaselineDifference to 1e4, and click on a compound with no peaks above that level, Maven basically freezes up to the point of unusability. If I click on a compound that has peaks, it works fine, and same if I set the filter to 0. Now that I'm looking for it, I see a slowdown effect also with fewer samples and the same conditions.

I have a sneaking suspicion it's related to #285 .. maybe something screwy about constantly updating the y-axis? Complete guess, might be way off.

Edit: it seems to be particularly bad for compounds/slices with a lot of scans, but no peaks above the threshold. Selecting a compound with few non-zero scans doesn't cause any problems.

**Comment by sahil21** [comment]
@chubukov This issue is resolved with #285.
