### ISSUE TITLE
use weighted average for averageMz of a group when EIC is summed over mzs

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#290]
From the last comments of #187 

I noticed that when "Sum" is chosen, the EIC mz value at each timepoint is being calculated as the average of all nonzero mzs in the window. I think that something like a weighted average (weighted by intensity) would make more sense.

**Comment by r-el-maya** [comment]
@chubukov yes that makes more sense.

In the case of '_sum_', we changed the calculation of eic's mz (eicMz) from simple summation to a weighted sum, weighted by their intensities.

Initially,
`eicMz = (sum of all MZs) / (number of MZs)`
Now,
`eicMz = (sum of all (MZ * Intensities) )  /  (sum of intensities)`

the same has been implemented and merged to develop

**Comment by shubhra-agrawal** [comment]
@chubukov @r-el-maya Closing this. Re-open it if there are any remaining issues in this thread.
