### ISSUE TITLE
allow user to zoom in/out on y-axis

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#292]
It would be nice if the user could just set the y-axis limits. The fixes from #135 are pretty decent, but not perfect. And anyway, sometimes it's really hard to look at a small peak next to a big peak.

It seems natural to allow this through the existing zoom functionality (which currently has no effect on the y-axis even though you're drawing a rectangle).

Would need to make sure reset zoom works properly.

**Comment by IpankajI** [comment]
@chubukov 
Zooming in/out along both axes has been enabled. Now by dragging a rectangle, that area can be zoomed in/out.

**Comment by chubukov** [comment]
@IpankajI This seems to be working nicely.
