### ISSUE TITLE
crash if peak picking is cancelled

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#3]
I can semi-reliably get Maven to crash if I hit "cancel" after initiating peak picking (while it's running). This happens most reproducibly if you do untargeted analysis, but sometimes also with targeted.

**Comment by GeorgeSabu** [comment]
@chubukov This is a bug we know and we are trying to solve this. This happens only in Windows machine, not on a ubuntu machine. We are working on this.

**Comment by GeorgeSabu** [comment]
@chubukov This problem is resolved. We had used a method called terminate() to stop the thread. That was the reason it was crashing. Now we used a method called stop() to do the same and used a flag to break the process that is happening inside the El-MAVEN-core.

**Comment by chubukov** [comment]
That's great.

Just a thought, I think it will be useful if we can put the code on GitHub
so that we can point directly to the affected code when resolving issues. I
think that rates to be very helpful for anyone coming on to the project in
the future. I know that was in the plans at some point, not sure about the
status.

On Oct 21, 2016 9:05 AM, "GeorgeSabu" <notifications@github.com> wrote:

@chubukov <https://github.com/chubukov> This problem is resolved. We had
used a method called terminate() to stop the thread. That was the reason it
was crashing. Now we used a method called stop() to do the same and used a
flag to break the process that is happening inside the El-MAVEN-core.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ElucidataInc/ElMaven/issues/3#issuecomment-255371436>,
or mute the thread

**Comment by GeorgeSabu** [comment]
@chubukov Yes we are planning to do so, we are making documentation of guidelines that has to be followed when reporting crashes , fixing crashes etc. We will share the documentation on the website as soon as we are done with it.
