### ISSUE TITLE
barplot/boxplot missing

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#316]
In the current develop, I can't get the intensity barplots or boxplots to show up at all.  And the isotopes barplot is blank no matter what I do.

Did something get updated regarding the QT libraries? I'm still using the same dlls from my QT5 install.

Edit: this only happens when selecting EIC based on compound widget. If I bookmark a peak and click on it in the peaks table, then I get the barplot. (though the isotopes plot is still blank).

**Comment by IpankajI** [comment]
@chubukov this has been resolved so closing this.
