### ISSUE TITLE
Directory structure of source code

### ISSUE THREAD

**Issue by rish9511** [ElucidataInc/ElMaven#319]
At present  our code does not follow any proper directory structure. All the files are mixed up and since the code base is huge, it all looks very messy. 

For this we need to

1. separate out the 3rd party libraries code from  our code base
2. separate build, bin and source code directories

This and issue #318  are important because it will allow new contributors to get acquainted with code base easily

**Comment by rish9511** [comment]
The work related to this issue is being carried out in a new [branch](https://github.com/ElucidataInc/ElMaven/tree/new_dir_structure)
The initial commit dd1d25a4f328905d4a6b4024ba5ca92c01eb171b has changed most of what was required but there are still changes needs to be done , hence not closing the issue ATM

**Comment by chubukov** [comment]
@rish9511 @sahil21 It would be great if you could ensure that building with QTCreator is also working as intended.

**Comment by rish9511** [comment]
The changes have been pushed to Develop with commit ae4f5c060f857a68ee7ce6f504f9cee0ccb0424c
@chubukov  QtCreator issue has been fixed now. Please report back if it fails to work for you
