### ISSUE TITLE
Undo alignment and Cancel alignment not working

### ISSUE THREAD

**Issue by Raghavdata** [ElucidataInc/ElMaven#329]
The undo alignment tabs and the cancel alignment buttons are not working in the alignment tab. Refer issue #39

**Comment by shubhra-agrawal** [comment]
@Raghavdata Undo alignment restores the original RT for all algorithms. Cancel works for obi-warp at all stages and for Poly and Loess fit during the grouping stages (which make up the majority of the process)

**Comment by shubhra-agrawal** [comment]
@Raghavdata Closing this one. Re-open if there are issues with the behavior.
