### ISSUE TITLE
shift-drag integration doesn't properly refresh bookmarked peaks table

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#33]
Copied from Trello board
1. load some samples
2. pick a compound
3. shift-drag in the EIC window -- this should integrate the peak and all isotopes for the selected RT window.
4. the peak shows up in the peaks table but without the + icon to expand isotopes.
5. do this with another compound, and now the expansion is available for the first compound.

Internally, it's there immediately, because if you do export to csv, all isotopes wil be present. It's just the table in the gui that's not properly being populated.

This bug is present in all versions of Maven that I've used. Double-clicking to bookmark based on the suggested peak does refresh the table properly.

**Comment by chubukov** [comment]
This bug is really confusing to new users, and I am hoping it's a really simple fix.

**Comment by GeorgeSabu** [comment]
@chubukov This problem is happening because pullIsotopes is happening inside a worker thread and its updated before the worker thread finishes. Now I have done a fix that the bookmark table will get updated after worker thread gets finished. I am not merging this with the develop as this could be taken care in a better way while refactoring isotopes.

Fix could be seen in https://github.com/ElucidataInc/ElMaven/commit/2ebd0d8faaedfc330c4120738f3b9f17f5824d57.

**Comment by chubukov** [comment]
@GeorgeSabu not sure I follow -- I think this is a little independent of the refactoring and we would still end up doing some almost identical fix after the refactoring. I would vote to merge this in if you think it's fixed in a reasonable way.

**Comment by chubukov** [comment]
Ok, I think I understand some of the issues involved (I admit that I don't really follow some of the logic in https://github.com/ElucidataInc/ElMaven/commit/2ebd0d8faaedfc330c4120738f3b9f17f5824d57 )

Can we simply wait for the workerthread to finish before bookmarking the peak? I assume that something similar is also the root cause of @ #37

**Comment by GeorgeSabu** [comment]
@chubukov Now I am waiting for the workerthread to complete, that is the way I have done it. And you are right #37 is because of the same reason. 

Now the problem is when user integrates it will always look for isotopes. There is no way to disable integration of isotopes. And one more effect that I am seeing is that when you click on the peak it will compute isotopes if isotope bar plot is enabled. This will start the same workerthread and on the finish, will update bookmarks table. So now, on click on a peak bookmark table is populated rather than on double click. It is because of this reason I am not merging this to the develop.

**Comment by chubukov** [comment]
It seems to me that what you have now is that you've moved the `bookmarkPeakGroup` functionality from the main thread to the `isotopeWidget` thread. And you're absolutely right, that's not a good fix, for the reasons you describe. What I was thinking is that the main thread (`EicWidget::integrateRegion`) could monitor when the worker thread has finished. Is that possible?

It seems to me that some version of that will have to happen no matter what we do with the refactoring. Somehow the logic has to be something similar to this

When user selects a peak (single click or hover):
1. all the normal things (e.g. populate peakAarea barplot/boxplot)
2. check what isotopes should be displayed in isotope barplot
3. populate barplot

When user bookmarks a peak (either double click, shift-drag, or "g")
1. check what isotopes should be displayed in isotope barplot
2. add those to the new metagroup
3. bookmark the peak and refresh table

As long as the computation is in a separate thread, we will have all the same issues.

**Comment by GeorgeSabu** [comment]
@chubukov thread is not from isotopeWidget it just initiates the thread. The thread is from BackgroundPeakUpdate class. So we cannot take the control back to EicWidget::integrateRegion. What can be done is to have flags in isotopeWidget class that will help us understand why pullIsotope is been called. This way we can control functionality for pull Isotopes. Like when barplot is been plotted bookmark peak should not be updated.

**Comment by chubukov** [comment]
@GeorgeSabu sure, that could work. 

Do you think it's better than the alternative model where we simply de-multithread this and have the peakupdater simply return the desired object (in this case a compound group) back to the calling function?

**Comment by GeorgeSabu** [comment]
@chubukov Using flags are simple and elegant. It will be less confusing in terms of architecture and readability of code.

**Comment by chubukov** [comment]
@GeorgeSabu ok, go for it. I do wonder how many of the crashes are caused by cases where the main thread expects the background peak update to finish before it does. Perhaps we can flag every case and deal with it.

**Comment by GeorgeSabu** [comment]
@chubukov Till now I have not found a case like that. But I will keep an eye on it. 

I have made the changes with the flag in https://github.com/ElucidataInc/ElMaven/commit/f8f20c945d4fa6428a729d395ff7c7abe3560588. This now has the desired functionality. I will update this branch to the develop after a round of testing.

**Comment by chubukov** [comment]
@GeorgeSabu how would asynchronous requests be resolved? For instance, say I click on one peak, then quickly click somewhere else. Now I might change the flag for backgroundPeakUpdater before the first action is finished, no?

**Comment by GeorgeSabu** [comment]
@chubukov Every action would have a separate flag like flag for integration, flag for barplot etc. So that one flag doesn't affect the other.

**Comment by GeorgeSabu** [comment]
#43 This is now fine.
