### ISSUE TITLE
Maven is grouping low intensity peaks but it is marking them as absent in the barplot and the peaks table

### ISSUE THREAD

**Issue by Raghavdata** [ElucidataInc/ElMaven#332]
We first saw that the present version of develop and alignment branches both were missing out some key peaks in samples. Below are the screenshots of the new and old maven for the same metabolite. As you can see the new maven is missing out on some peaks from samples (samples are greyed out).

Maven new
![maven new](https://user-images.githubusercontent.com/16893466/29360258-bfb612ee-829f-11e7-82fa-f1c35a110978.png)

Maven old
<img width="1279" alt="maven old" src="https://user-images.githubusercontent.com/16893466/29360260-c1795ba4-829f-11e7-82a5-e813a163fa39.png">

Upon further examination we saw the peaks from all the samples are being grouped but only very high intensity peaks are showing in the bar plot as well as in the peaks table.

![bug](https://user-images.githubusercontent.com/16893466/29359531-a9d4674e-829c-11e7-8b50-c4d8ecdf9e6c.png)

**Comment by chubukov** [comment]
@Raghavdata In the last example, is the horizontal dashed line the baseline? If so, those other peaks are below it (and explains the low values for the big peaks).

Agree that a number of things could be improved about this.

**Comment by Raghavdata** [comment]
@chubukov The baseline is the dashed line but on closer inspection you would see each peak has its own base

**Comment by chubukov** [comment]
@raghavdata Yes, sorry, I was being dumb.

**Comment by Raghavdata** [comment]
@sahil21 Just an update on this one. We were able to have a workaround this but this issue still remains.

**Comment by saifulbkhan** [comment]
Does this happen anymore? I am closing this, since I cannot recall seeing this issue before. We can reopen this, if it ever comes up again.
