### ISSUE TITLE
grouping parameters affect mergedEIC?

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#333]
I noted some odd behavior with the new grouping parameters in the last comments here: #151 

I observed something else funny: as I change the grouping parameters, the mergedEIC changes significantly. I don't fully understand why this happens because as far as I can tell the mergedEIC should jus be an average of the intensities of the EICs, having nothing to do with grouping.

**Comment by shubhra-agrawal** [comment]
@chubukov We have not been able to reproduce this in v0.1.4 or v0.1.3. I tried unchecking 'Consider Overlap' and setting distX weight to 0 as suggested in #334. Could you post some screenshots and provide any other settings that might help us see this in effect?

**Comment by chubukov** [comment]
@shubhra-agrawal I'm almost certain this had to do with #388

**Comment by sahil21** [comment]
@chubukov I'm not able to reproduce this issue after removing the static variables in **gaussian1d_smoothing** function. I'll test other issues as well #334 #388

**Comment by sahil21** [comment]
@chubukov Closing this one. Resolved with #412
