### ISSUE TITLE
use expected m/z, not observed m/z when pulling EIC based on peak table entry

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#34]
Copied from Trello, with more detail added.

If you bookmark a peak (or get a table through database search) it will assign an m/z value to the peak group. That value might be a little different from the expected m/z for the compound, depending on the ppm window and the actual MS data. When you now click on the peak in the peaks table, maven will use the "observed" m/z as the center of the mass window, and show you an EIC for the observed m/z +/- ppm window. I think more proper behavior would be to use the original expected m/z value, which should still be stored (since there's a link to the compound in the peakgroup).

If the peak is the result of doing untargeted search or of entering a mass into the textbox at the upper right, then there is no expected m/z, and no compound linked, so then you would use observed m/z. 

I guess the corner case is if the user enters a _formula_ into the text box -- it would be nice if that resulted in a fake compound with the proper m/z being stored with the peakgroup, but honestly I don't care whether that works.

**Comment by sahil21** [comment]
@chubukov Shall we add another column named as "expected m/z" in the peaks table rather than replacing with the "observed m/z"? In the above scenario for automatic feature detection, the "expected m/z" will be given a value NA. Does this makes sense?

**Comment by chubukov** [comment]
Sure, I think that makes sense. We could do it the same way for both m/z and RT (currently for RT we have expected RT and RTdelta).

**Comment by chubukov** [comment]
@sahil21 thanks for adding this feature. It looks like it's not taking the right mass though

- for compounds with formula, looks like it's taking the non-ionized mass
- for compounds without formula, it's showing 0.000
- for isotopes, it's showing the same mass as the parent

**Comment by chubukov** [comment]
@sahil21 After we make sure that expected m/z is being correctly populated, we can fix the original issue, and use it to center the extracted EIC mass window.

**Comment by GeorgeSabu** [comment]
@sahil21 We have to check it again.
