### ISSUE TITLE
Mass Spectra not picking up the right scan

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#341]
When the user clicks on a peak in the EIC window, mass spectra picks up the consecutive scan. Most probably it is an indexing error. 

This issue came up when we were working on the branch **ftr_chooseFilterline**. 
ftr_chooserFilterline branch has a feature in which the user can choose the filterLine (or segments) from a data. We tried to process a data with 3 segments. The data was such that after every scan the segment changes. Every time you choose one segment, the mass spectra show the scan having the consecutive next segment.

**Comment by IpankajI** [comment]
@sahil21 resolved and merger to develop.
