### ISSUE TITLE
shift-drag should restrict rt range for isotopic children

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#344]
If the user bookmarks a peak with shift-drag, they are specifying the RT bounds for the peak. The isotopic children should also be limited to these bounds, even if the minIsotopeScanDiff parameter would take the search outside them. (minIsotopeScanDiff should still be used to restrict the boudns further, if applicable).

reported by @myasteadman

**Comment by saifulbkhan** [comment]
This seems like something that will be taken care of by the "Link isotope peak RT range with parent peak" checkbox in "Isotopes" dialog. Resolved with v0.11.0
