### ISSUE TITLE
Download executables/test files from S3

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#350]
Repo size has increased significantly after adding alignment executable and Integrating tests in travis CI. These files should be present on S3 Bucket.

**Comment by rish9511** [comment]
@sahil21 @chubukov 
Large files (executables, sample files) are now stored using Git lfs. Git hub does not allow to push files that exceed the hard limits set for each file.

**Comment by chubukov** [comment]
@rish9511 I haven't worked with git LFS. What are the practical consquences of this? Do I need to do two separate pulls in order to get all the files? If I need to do something special, it would be great if you could update the ReadMe (or maybe you already have).

**Comment by rish9511** [comment]
@chubukov 
No you won't have to do two separate pulls. Just a simple git pull will get you all the files, like it did earlier
