### ISSUE TITLE
SRM link to EIC of fragments in compound database

### ISSUE THREAD

**Issue by shefalilathwal** [ElucidataInc/ElMaven#355]
When a fragment is selected from the compound database, how does El-MAVEN pick which EIC to show from the SRM list when there are multiple transitions present of the same precursor/product pair?

**Comment by saifulbkhan** [comment]
@shefalilathwal With v0.11.0 the answer this question is - the one that matches the collision energy (CE) for the database entry. If no CE is available for a transition in the database, but is available in the SRM list, then its a mismatch and you probably will not get an EIC. If that answers your question, please close this issue.

**Comment by shefalilathwal** [comment]
@saifulbkhan I haven't worked with SRM data in a while, so won't be able to test this. Will close it for now.
