### ISSUE TITLE
Sample number not showing on popped up window for a particular sample 

### ISSUE THREAD

**Issue by sunil20dhakad** [ElucidataInc/ElMaven#358]
In the sample list, I am looking for only particular sample numbers but I am not able to get the information of sample number inside the ELMaven. 

We get other information like m/z range, rt range, scan #, ionization, filename information for each sample present but no information regarding sample number.
We can have an extra column inside sample widget for sample number.
ElMaven version # El_Maven_v0.1.4-18-g654cfb1

**Comment by saifulbkhan** [comment]
Additionally, I see `-1` values for "sample number", when I hover over a peak in the EIC.

**Comment by saifulbkhan** [comment]
There is now a separate column for sample numbers in the samples widget, in v0.10.0.
