### ISSUE TITLE
Filterline not updated when uploading mzroll file again inside ElMaven

### ISSUE THREAD

**Issue by sunil20dhakad** [ElucidataInc/ElMaven#359]
I was working on some .mzML data, I did peak picking and stored the results in .mzroll format. When I again uploaded the .mzroll file, I found that there is some difference in peaks which I picked before. I issue is that while uploading the .mzroll file, the Fliterline is not getting updated due which I am getting unexpected results.
ElMaven version: El_Maven_v0.1.4-18-g654cfb1

**Comment by saifulbkhan** [comment]
We will no longer be able to maintain the (now deprecated) mzroll standard. Sorry about this.
