### ISSUE TITLE
There should be a close button on every widget

### ISSUE THREAD

**Issue by sunil20dhakad** [ElucidataInc/ElMaven#361]
ElMaven has many widgets and sometimes these pop up while working which might not be required. There should be a closing button on every widget to close that function.

**Comment by shubhra-agrawal** [comment]
Close buttons have been added to the 3 alignment visualization widgets in v0.6.0 and above.
Following are the widgets that do not have a close button yet:

- [ ] SRM widget

- [ ] Isotope plot

**Comment by saifulbkhan** [comment]
Done in v0.10.0. Closing.
