### ISSUE TITLE
Allow users to manually link SRM transitions to a fragment in LC-MS/MS data

### ISSUE THREAD

**Issue by shefalilathwal** [ElucidataInc/ElMaven#364]
During LC-MS/MS peak-picking, MAVEN assigns fragment names to SRM transitions present in the .mzML files. Sometimes when Q1 and Q3 values for two transitions are same, and retention times for these two metabolites are close by, the automatic assignment by MAVEN is often incorrect. Therefore, the user should be able to manually edit any inaccuracies in the SRM list (i.e., manually edit which fragment a given SRM belongs to), otherwise incorrect fragment name gets associated with an EIC in the output file.

**Comment by chubukov** [comment]
@shefalilathwal just trying to understand this better: sounds like you have two peaks in the EIC that should be assigned to two compounds, but the automatic assignment is incorrect? This isn't unique to any particular ms mode, and the way we usually solve this is:
-delete the incorrect peak
-bookmark the correct peak
-merge the bookmarks table

If you have a suggestion for a smoother way do this, it would be great.  Not sure that I follow your current suggestions -- it doesn't sound like an inaccuracy in the srm list...

**Comment by sahil21** [comment]
@chubukov Shefali usually picks peaks from SRM list widget rather than Compound database widget. The compound database widget doesn't pick up right transition when we have more than one transition of same precursor and product pair in the sample file. It picks up the first transition.
So the feature she requested is to change the annotation of transitions in SRM list widget itself.

**Comment by chubukov** [comment]
@sahil21 @shefalilathwal ok can we just fix the compound widget instead? :)

**Comment by shefalilathwal** [comment]
@chubukov the transition information coming from mz(X)ML stays the same. The issue is how to link the transition information to a fragment name. As an example, if the RT of two transitions with same Q1 and Q3 are very close together, they can be incorrectly assigned. The idea is for the user to be able to correct the assignment manually, if needed.

**Comment by shefalilathwal** [comment]
@chubukov to the earlier suggestion about bookmarking peaks and merging tables: You are right that the issue is not specific to an ms mode, but it is particularly relevant in ms/ms. it is because if a transition has been incorrectly assigned, then while bookmarking it, the fragment name corresponding to it will still be the incorrect fragment that it got assigned to. So even if we can pick the right peaks, the fragment id associated with it in the output file still be incorrect. Therefore, it would be good to be able to manually correct the link between a transition and fragment, in case it is needed.

**Comment by sahil21** [comment]
@shefalilathwal @sunil20dhakad This has been resolved and merged to the develop branch.

**Comment by shefalilathwal** [comment]
The issue has been fixed and tested.
