### ISSUE TITLE
fast double click when bookmarking peaks

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#37]
This is one that caused a lot of headaches, and I had some hints as to the issue, but I think I've figured it out.

1. Load some samples and select a compound from the list
2. Quickly (i.e. without hovering) double click on one of the circles

This will bookmark the peak, but will not pick any isotopes. 
- If you first single-click on the peak, triggering display of the isotopes plot, then double click will have the expected behavior. It doesn't seem to matter if isotope plot is enabled or not.
- Even hovering over the circle for a few seconds without clicking seems to be sufficient.

Let me know if you're able to reproduce -- if not, I'll make a video.

**Comment by GeorgeSabu** [comment]
@chubukov We were able to reproduce the issue. We will resolve it as soon as possible.

**Comment by GeorgeSabu** [comment]
@chubukov this bug is resolved with the isotopic refactoring #43.

**Comment by chubukov** [comment]
Confirming that this appears to be resolve with the new barplot.
