### ISSUE TITLE
Bad alignment issue

### ISSUE THREAD

**Issue by MaryPiotrowski** [ElucidataInc/ElMaven#375]
Max retention time between peak set to 0.5min but peaks within 0.5 min were not grouped.

[Bad alignment.pptx](https://github.com/ElucidataInc/ElMaven/files/1303324/Bad.alignment.pptx)

**Comment by Raghavdata** [comment]
@MaryPiotrowski Thanks for reporting the issue. Our understanding is that the issue is caused by bad grouping. We are looking into changing the grouping parameters to take into account such a large variation in RT. Post this alignment should be able to resolve such large grouping variations.

**Comment by shubhra-agrawal** [comment]
@MaryPiotrowski @Raghavdata Obi-warp alignment should be able to resolve such issues now. If you still encounter such alignment issues after using obi-warp, please let us know.
