### ISSUE TITLE
Select/Deselect Isotopes for Isotope barplot from dock widget

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#379]
![image](https://user-images.githubusercontent.com/21240516/30509496-97c6c736-9acf-11e7-9788-0ec72a792e40.png)

The selection of isotopes for bar plot should be from isotope barplot dock widget itself and not from the main options.

**Comment by shubhra-agrawal** [comment]
@sahil21 Shipped as part of v0.4.1
