### ISSUE TITLE
Uploading speed of samples has decreased in the latest develop

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#382]
Uploading of samples is visibly slow in current develop compared to last release 0.1.5. All the cores are being used so I suspect there is some un-intentional computation going on.

**Comment by sahil21** [comment]
@IpankajI The problem is with this commit https://github.com/ElucidataInc/ElMaven/commit/e2d5611b46184ed8c8ac03a1f45d639b1cf4d58c
I guess this code is adding some extra information like debug symbols. Let's make code coverage as part of debug version and not for the release version.

**Comment by IpankajI** [comment]
@sahil21 Yes, we must only use code coverage for debug version.
