### ISSUE TITLE
c12 parent no peak detected

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#386]
This is probably related to #210 and reminscent of #98.

I have seen a number of cases now where the parent peak is integrated fine, but the isotopes, including even the C12 parent daughter peak are not. 

This only happens if I have the baseline calculation enabled. If the baseline "drop top x%" is set to zero, the peak finding seems to be fine.

All the peak filtering parameters (min signal baseline difference) are zero.

On these samples, this happens in every version I've tried, including back to Maven 772

Here's an example. At BaselineDropTopX=0
![image](https://user-images.githubusercontent.com/13080968/30711291-4d410568-9ed6-11e7-961f-5fe2001e19bf.png)

And at BaselineDropTopX=1%. The C12 parent disappears from the isotope barplot. Notice the baseline doesn't even shift all that much (well ok, it shifts, but not down to zero).

![image](https://user-images.githubusercontent.com/13080968/30711200-06c77824-9ed6-11e7-83da-4265c4974ad5.png)

Here is the missing C12 parent peak after bookmarking

![image](https://user-images.githubusercontent.com/13080968/30711337-6ba4eba0-9ed6-11e7-8365-d1fb64d41fa6.png)

**Comment by chubukov** [comment]
a) I have been able to reproduce a case where setting baselineDropTopX to 0 still gave the bug
b) This seems to only happen with very high intensity peaks

**Comment by chubukov** [comment]
Changing the smoothing algorithm to "moving average" completely alleviated the problem, at least in this case. Interestingly, I noticed it also seemed to fix some of the issues similar to #334. 

I am suspecting there may be a bug in the savitzky-golay or gaussian smoothing function. Great time to bring up #348

**Comment by chubukov** [comment]
I have traced this to `mZsample->correlation` returning `nan`. I am having memories of dealing with this a year ago when we were still using Trello for issues.

**Comment by sahil21** [comment]
@chubukov Yes, I agree that we should use double (I'll create a new issue for this). I don't think that changing float to double will increase memory usage drastically unless we are changing datatypes of vectors in Scans.

**Comment by shubhra-agrawal** [comment]
@chubukov An issue to start using double instead of float is already open. Closing this one.
