### ISSUE TITLE
srm widget floating in space

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#387]
Something is funny about the SRM widget in the current develop. It seems to float above everything and can't be moved or resized.

**Comment by chubukov** [comment]
Huh, weird, this only happens on one machine but not another (same QT libraries, same executable). I am not going to lose sleep over it.

**Comment by sahil21** [comment]
@chubukov I once experienced something like this on a Windows machine. Uninstalling/Installing the application worked for me. Also, I think there should be a close button on every widget. #361.

**Comment by saifulbkhan** [comment]
Dockable widgets in Qt can be made to float separately from the main window. This is probably what happened with you @chubukov. If you drag it by the titlebar, you should be able to dock it in the top, left or bottom positions as with other widgets. Double-clicking the titlebar also does the same.
