### ISSUE TITLE
non-deterministic eic pull

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#388]
very similar to #334 but more explicit

I am convinced that there is some initialization or conversion bug in the EIC pulling + smoothing code, or some other bug that creates occasional random results.

You can generate this by just playing with the ppm window in the main window. 

Here I started at 6 ppm. Looks fine.

![image](https://user-images.githubusercontent.com/13080968/30721995-a7b650ae-9efc-11e7-8634-d816e724ef4b.png)

I increased it incrementally and at 10.5 I got some crazy extra peak in the blue sample.

![image](https://user-images.githubusercontent.com/13080968/30722019-c87f9aac-9efc-11e7-9f9c-c48a07e1c148.png)

I went up to 11 and back down to 10.5 and it looked normal again

![image](https://user-images.githubusercontent.com/13080968/30722131-6af264ea-9efd-11e7-81f9-317434be544e.png)

I did the same thing a few more times. Here's the green sample with a crazy rightward shift in the smoothed spline.

![image](https://user-images.githubusercontent.com/13080968/30722120-524b9114-9efd-11e7-97cb-1d8278b27db2.png)

Again, I changed the ppm and changed it back, and got the normal chromatogram again. I can do this all day long :)

Interestingly, I can keep doing it, and I get a lot of the _same_ bad chromatograms appearing over and over. For these two samples, it's always either the green peak shifting over (by seemingly exactly the same amount), the blue peak shifting in a very similar way, or that weird extra peak in the blue samples. The ppm it appears at is completely random, so I really think it's just a matter of me re-pulling the EIC that triggers it, nothing to do with the ppm.

**Comment by chubukov** [comment]
I looked through a lot of this code and haven't found anything yet. I did notice that in a few places the smoothingWindow parameter was interchangeably declared as float or int, with implicit conversion taking place. But I think that's allowed and shouldn't cause any problems.

**Comment by chubukov** [comment]
I believe that this only happens with smoothing type `Gaussian`. (But that is called when the combo box is "Savitzky-Golay", which is the default (#391) )

**Comment by shubhra-agrawal** [comment]
@chubukov I haven't run into something like this in a long time. I believe this was fixed after removing the static declarations last year. Not sure if I understand the source of this bug yet.
If you haven't encountered this bug in the past year, should we close this?
