### ISSUE TITLE
csv export from mzroll

### ISSUE THREAD

**Issue by Nikita1093** [ElucidataInc/ElMaven#389]
NA value appears in the csv exported from mzroll.

**Comment by Raghavdata** [comment]
@sahil21 @IpankajI Can we prioritize this amongst the issues that @IpankajI has?

This is inhibiting Mary from processing data on El-Maven.

**Comment by sahil21** [comment]
@Raghavdata Sure.

**Comment by IpankajI** [comment]
@Nikita1093 it's been resolved and merged to develop.
