### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by GeorgeSabu** [ElucidataInc/ElMaven#39]
This is copied from trello.
Today I looked semi-seriously for the first time at the alignment code. There are actually a few things in there that make me very optimistic, among some that make me less so.

1) The alignment logic in peakdetector.cpp is completely broken and it's not at all surprising that it doesn't work at all. Groups have to be identified first, then doAlignment can be called on those groups. Also, some parameters are set at the end of the alignGroups function which probably break further processing. This is clearly code that was never finished or tested at all.

2) The basic structure of doAlignment() is fairly simple and very conducive to the changes I want to make. It's a fairly modularized function that takes a vector of peakgroups, sets the rt vector to a new set of times, and saves the old times in originalretentiontimes.

2b) What I want to do is have another option at the core of the algorithm, where on each sample, you run processCompounds using a special compound database that's only for alignment. Then fit some kind of spline from the expected (reference) RTs to the observed RTs for all the compounds you find, and use this to interpolate the whole RT vector. This is in many ways much much easier than aligning all samples at once. For the gui, the current dialog box could be reused to a great extent, and the command line version is even easier.
(This development would be in parallel to fixing the existing code.).

3) There's a clear bug in line 44 of mzAligner -- the argument is supposed to be polynomialDegree. Easy to fix but unfortunately this makes me think this code wasn't tested at all. However, this is actually correct in the open source version! (no argument, and polynomialDegree is referenced within Fit()). I did a quick diff of the two versions -- it looks like quite a number of changes were made.

4) At the moment I can get alignment to go through successfully for some sets, but it looks like it works only when there is no alignment needed (maybe it's ok when the algorithm exits after 1 iteration or something like this). Otherwise, I usually get a crash. (even after fixing the one bug I mentioned above)

Maybe the right place to start is to take a look at what was actually changed and perhaps reverting back to the version of mzAligner in the open source code, and trying some alignments to see if we still get crashes? If we do, maybe we can bring back or bring in some of the logging and debugging output and see if we can work this out.

Let me know if that seems reasonable and how it would fall in the timeline.

PS. I'm sure you understand this, but just to emphasize: the way that alignment needs to work is that there should be a single transformation from unaligned retention times to aligned retention times (i.e. you don't want to align mass slices individually -- you want to use the individual mass slices to get an average transformation that would then be applied to the entire RT vector). Ideally this transformation is constrained to be monotonic.

**Comment by chubukov** [comment]
It's not obvious to me whether any sort of alignment is supposed to be working at this point. We talked about it today and you mentioned some issues with large RT shifts, but I don't remember now if you said that you fixed it or are still working on it. I haven't been able to see any effect, but I can't tell if the algorithm is just not doing anything, or if it's just failing to align these samples. 

If we're serious about including this, we need to come up with a good way to display the results of the alignment. Simple version would be just a curve of deltaRT vs RT with one line for each sample.

**Comment by Raghavdata** [comment]
@chubukov As discussed with you, we are planning to implement the Loess fit alignment in Maven. We will be spending time this sprint trying to come up with a framework for easy integration of the Loess fit alignment algorithm and any future algos to the Maven code. To do this we plan to:

- Explore options to link C to Python

- Pass dummy data from alignment function to Python

- Check if data passed can be easily manipulated in Python

This approach will help us in:

- Setting a standard template for adding any new alignment 

- Developing mathematical models with ease (Python has a larger community for statistical analysis)

- Unit testing our algos better.

Once done with setting up the basic framework, we will plan to:

- Code the new algorithm

- Add appropriate UI changes to incorporate new algorithm

- Define test cases to compare between present and new algorithm

Our aim in this sprint is to at least setup the C to Python framework and code for the basic algorithm. We will also unit test the Python code to check for the working of the functions defined.

**Comment by Raghavdata** [comment]
@chubukov Just a short update. We have been able to

- call the python interpreter from C

- provide python the data it requires to run the algorithm

We are coding the algorithm now.

**Comment by chubukov** [comment]
@Raghavdata Great. Let me know when you're ready to show off what you've done, I'd love to see how you've organized it.

**Comment by Raghavdata** [comment]
@chubukov The sub issues to alignment in this sprint have been resolved. We are now able to:

- Call the python interpreter and thus the script from C

- Get modified RTs based on the Loess fit algorithm

- Load test the C to python data parsing and python interpreter calling

The issues marked for the next sprint are:

- Creating appropriate UI changes to incorporate alignment

- Test the the effectiveness of the new algorithm

The codebase for the alignment branch will be merged after the UI changes have been done in the next sprint and the code appropriately refactored.

**Comment by chubukov** [comment]
@Raghavdata great

**Comment by Raghavdata** [comment]
@chubukov Loess fit alignment is ready to use. You can pull the branch called alignment from the repo. Our plan is to merge the branch to develop after you have tested it. 

I am also attaching a few screenshots around how the loess is aligning some peaks as compared to Poly. 

Succinate:
![succinate](https://user-images.githubusercontent.com/16893466/28995597-a49ba99e-7a0a-11e7-86c8-bd5a934a5509.png)

Glutamate:
![glutamate](https://user-images.githubusercontent.com/16893466/28995592-933df846-7a0a-11e7-8a21-6856177b0f94.png)

Acetyl-Serine
![acetyl serine](https://user-images.githubusercontent.com/16893466/28995593-9674b2f2-7a0a-11e7-8914-37b246d7b3bd.png)

We will update more on the comparison of Loess to Poly in our next meeting.

**Comment by chubukov** [comment]
@Raghavdata ok great, will do. 

Are the various visualizations that were made last time we worked on alignment also integrated with the results? I'm mostly interested in the plot of rt shift vs rt for each sample.

**Comment by Raghavdata** [comment]
@chubukov There are three visualisations in alignment presently. Out of these two are working essentially,

Single group RT shift
![image](https://user-images.githubusercontent.com/16893466/29059557-c0d5aecc-7c33-11e7-8596-be347e5af00d.png)

All group RT shift
![image 1](https://user-images.githubusercontent.com/16893466/29059576-d8183c44-7c33-11e7-8f03-5304e1035eaf.png)

The visualisation you have mentioned is not working right now. We will file it as a bug and resolve it work in the forthcoming sprints.

**Comment by chubukov** [comment]
@Raghavdata I believe that the second plot is not showing the RT shift but rather the RT variance within a group? @sahil21 can correct me if I'm wrong -- we had some discussion about this when it was first developed.

**Comment by chubukov** [comment]
@Raghavdata I built the alignment branch but when I start the loess fit, Maven finds the groups, and then just stays in an infinite loop with the "aligning samples" message and the circular progress bar.

I suspect that this is because it is not finding the python files. If that's plausible could we
1. Specify the directory structure that it needs/expects. I compile using QT Creator, and I suspect that it results in a different structure. I also need to be able to build on one machine and then transfer to another machine, so I anyway need to know the requirements, even if I use the shell script.
2. Make it error out in the case that something like this goes wrong.

**Comment by Raghavdata** [comment]
@chubukov Loess alignment takes around a min for large number of samples. Did you have to wait for more than a minute?

Moreover, we do know the issue with error handling but as far as the directory issue goes @rish9511  has coded out the relative path (from Maven directory) to the python files. We can try compiling using QT Creator and see whats going wrong there. 

Also, the issue you had mentioned in your previous comment around RT shift vs RT has been filed and will be resolved in the forthcoming sprints.

**Comment by chubukov** [comment]
@Raghavdata I let it run for >6 hours and it was only 20 samples,

Can you be more specific about the correct path relative to the executable> (or is it relative to the working directory?)

**Comment by Raghavdata** [comment]
@chubukov the python_exe should be present in bin/windows or bin/linux depending on the OS. Here the bin folder is present in the El-Maven directory.

**Comment by chubukov** [comment]
@raghavdata ok, I just copied the whole bin directory and that worked fine. 

Seems to work well for small shifts. For bigger shifts, where the grouping isn't collecting the peaks by default, I couldn't get a good alignment. I think fixing some of the bugs in #151 would help (now that I see some of the other recent bugs I posted, I'm not convinced that they are specifically about the grouping parameters, maybe something more general about randomness during eic pull and grouping)

**Comment by Raghavdata** [comment]
@chubukov You are right for bigger shifts this is a problem, we partly resolve it by increasing the grouping window and changing the parameters to get such peaks with large shifts into a single group and then do alignment on them.

**Comment by chubukov** [comment]
@raghavdata can you be more precise about what you mean by increasing the grouping window?

The easiest way would be to increase the eic smoothing window but it would be best to be able to change the grouping, not the smoothing.

**Comment by Raghavdata** [comment]
@chubukov If you go to the peak detection tab in the options dialogue box you will find a parameter called Max Retention time difference between peaks. It is set at 0.5 min by default, we increase this to around 1 min to capture very large shifts.

**Comment by chubukov** [comment]
So that will work well for medium shifts where the peaks still overlap somewhat. If they don't overlap at all, I think that will not be enough to group them. Am I wrong? That was part of the motivation -- see my notes in #151.

**Comment by Raghavdata** [comment]
@chubukov Yes that might be the case. I will have to try it with data with such large shifts. Also, after reading #151 I understand what you mean. Maybe we ought to think more around our grouping parameters.

**Comment by chubukov** [comment]
@Raghavdata I put some badly misaligned data that I've been usign for testing in the egnyte folder.

**Comment by Raghavdata** [comment]
@chubukov On which account have you shared the data?

**Comment by chubukov** [comment]
@Raghavdata I actually have no idea :) We have an "Elucidata" egnyte folder linked on our filesystem, which I assumed you had access to. Maybe that's a bad assumption. What account should I be using?

**Comment by Raghavdata** [comment]
@chubukov I asked around and none of us have access to a folder named "Elucidata" on Egnyte. Is it possible for you to share it with us on my account (credentials sent via mail)? Or I could drop a mail to Mark Pytlik asking him to share the folder on my account.

**Comment by rish9511** [comment]
@Raghavdata 
Is there anything else you feel that needs to be done ? If not, can we close this issue

**Comment by Raghavdata** [comment]
@rish9511  I think we can clone this one. We already have other issues pertaining to this so its fine.

**Comment by rish9511** [comment]
@chubukov @Raghavdata 
Closing this for now as we have opened other issues related to this.
