### ISSUE TITLE
parent slice does not match "c12 parent" slice

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#393]
The mass range that's pulled based on formula for the parent group differs from the one for the "C12 parent" group.

For instance, for C3H7NO2 (alanine) at 10ppm in negative mode, the slices that get pulled are
88.0395 - 88.0413 for the parent
88.0399 - 88.0416 for the C12 parent

Sure, this usually won't matter, but there are a number of critical places where it is assumed that the C12 parent EIC is identical to the parent, so this could be the cause of some hard to trace bugs.

Looks like approximately the mass of an electron but not quite....

**Comment by sahil21** [comment]
@chubukov Are you using Isotope widget to get C12 Parent?

**Comment by chubukov** [comment]
@sahil21 I just put a debug print statement in `getEIC`. This came up debugging some of the other issues.

**Comment by sahil21** [comment]
@chubukov Got it. I guess it has something to do with expected m/z. We'll check this out. In lots of sections of code, m/z is being calculated separately. We should replace all of that with a common function to calculate expected m/z just like we did with charge (getCharge function).

**Comment by chubukov** [comment]
@sahil21 Related to fixing `expectedMz()`, I noticed that this issue #235 was still outstanding -- the problem is the `ppmdist` calculation using the wrong mass in `csvreports.cpp`.

**Comment by saifulbkhan** [comment]
This issue is almost definitely because of an (unintentional) conversion of a less precise (`float`) m/z to a more precise (`double`) m/z. I think I know where the change needs to be done. Adding it to the current release plan.

**Comment by shubhra-agrawal** [comment]
@saifulbkhan check if this is still an issue. Sounds like the same issue we recently fixed where the C12 Parent was getting filtered out. The problem was that the mass used to detect C12 parent was the groupMz of the actual parent group inatead of the compoundMz.

**Comment by saifulbkhan** [comment]
@shubhra-agrawal The reason why I think what I think is because while working on another issue recently (post v0.9.1) I was printing out some m/z values of parent vs C12-parent, and there was some m/z difference (at the 4th - 5th decimal place). I changed the prototype of `Isotope` constructor to take a `double` instead of a `float` mass and the difference vanished.

**Comment by shubhra-agrawal** [comment]
@saifulbkhan got it.

**Comment by saifulbkhan** [comment]
@chubukov This has been fixed, to the best of my knowledge, in v0.10.0.
