### ISSUE TITLE
Maven Windows Installer not working

### ISSUE THREAD

**Issue by rish9511** [ElucidataInc/ElMaven#397]
When trying to install Maven using the Maven Installer, the following error gets displayed  
"This application failed to start because it could not find or load the Qt platform plugin 'windows' "

![elmaven error](https://user-images.githubusercontent.com/10898272/30845389-ccfb6568-a2b0-11e7-80f8-6b62b3c5ce8b.png)

**Comment by chubukov** [comment]
@rish9511 I was able to deal with this by providing a qt.conf file that looks like this:

```
[Paths]
Plugins=./plugins
```
And i have qtwindows.dll in Platforms/Plugins/

**Comment by rish9511** [comment]
@chubukov 
Thanks for pointing that out. This most probably should solve the issue

**Comment by rish9511** [comment]
**Solved**
For us the culprit was the compiler flag "-march=native". With this flag the executable used to work on just windows 10(because we used it for compiling)
Having qt.conf in the same folder as executable is also important. 
```
[Paths]
Prefix = .
```
