### ISSUE TITLE
Explore HTML/JS for UI

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#409]
This will ease up the process of creating/changing UI

**Comment by sp-eldata** [comment]
Deserves some more context no?

**Comment by rish9511** [comment]
At the moment we use  Qt's widgets modules for our UI. We need to explore better/easy to maintain options for UI such as [Electron](https://electron.atom.io/) or [Qt Quick](http://doc.qt.io/qt-5/qtquick-index.html) . Qt quick allows to glue JS with the UI code and Electron allows to make use web techonlogies(html,css, js)

**Comment by shubhra-agrawal** [comment]
Closing this since we have decided to use QML as part of the UI refactoring effort.
