### ISSUE TITLE
Expanding row of buttons in header

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#41]
If you shrink the width of a window such that not all the buttons in the top toolbar are visible, a ">>" button appears that's presumably supposed to expand the list to a drop-down. For me, it has never done anything (in any maven version). 

This seems to be relevant? from https://doc.qt.io/archives/4.6/qtoolbar.html

"When a QToolBar is not a child of a QMainWindow, it looses the ability to populate the extension pop up with widgets added to the toolbar using addWidget(). Please use widget actions created by inheriting QWidgetAction and implementing QWidgetAction::createWidget() instead."

Definitely not high priority if it involves rewriting all the widgets.

**Comment by chubukov** [comment]
Just noting that this is also unchanged in the QT5 version.

**Comment by sahil21** [comment]
@chubukov This has been merged with develop so we are closing this issue. If you see further problems please reopen it.
