### ISSUE TITLE
ElMaven stopped working on Windows 7 64bit

### ISSUE THREAD

**Issue by danielbraas** [ElucidataInc/ElMaven#411]
Hi,

I installed ElMaven earlier today on a Windows 7 64bit system. It started fine initially, and I started to specify the path to msconvert and looked briefly at some mzXML files. I closed the session and tried to open it again a few minutes later, but it wasn't starting. The crash report is attached.

Thanks,
Daniel

![crash-report](https://user-images.githubusercontent.com/20832048/30943829-7d9ee438-a3a8-11e7-93f2-7882b695146e.PNG)

**Comment by Raghavdata** [comment]
@danielbraas Thanks for filing this bug. The version you are using for El-Maven is slightly old and has a few bugs. I would be mailing you information about the latest version. Having said that the El-Maven installer for the latest version works only for Windows 10.  We are soon going to be releasing the installer for Windows 7 as well.
