### ISSUE TITLE
switching isotope settings between bookmarking different peaks leads to wrong groups in table

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#413]
Are isotope children pulled anew when scrolling selecting groups in the peaks table?

Try this:
- select only 13C isotopes.
- bookmark a peak corresponding to a compound with some Cs and some Ns
- switch to only 15N isotopes
- bookmark another peak corresponding to a compound with some Cs and some Ns

Now look at the first peak in the tabledockwidget. You see the C13 children but no EIC is pulled from them. And you have 15N children appearing as well. 

I guess this has to do with the mavenParameters->isotopeAtom being abused... presumably this is due for a refactor at some point anyway.

**Comment by chubukov** [comment]
Somewhat similar/related issue I observed today:

I had an mzroll file where I had bookmarked peaks with both 13C and 15N isotopes. But when I loaded it, I only had "13C" checked in the options. That resulted in none of the 15N peaks being visible when I scrolled through the table. Changing the options to include 15N didn't help -- in fact the 13C peaks disappeared too!

**Comment by saifulbkhan** [comment]
I can not reproduce this with v0.9.1. Maybe it got fixed somewhere along the way. Closing this.
