### ISSUE TITLE
Automatic shortcut for El-Maven on Desktop during installation

### ISSUE THREAD

**Issue by Raghavdata** [ElucidataInc/ElMaven#414]
@rish9511 This is a suggestion made by [@danielbraas](https://github.com/danielbraas). The following is from his email:
"I noticed that the installer doesn't produce a folder in the start menu or a link on the desktop. I think in future version you might want to include a "Do you want a shortlink on your desktop" option checkbox for your installer."

**Comment by sahil21** [comment]
@Raghavdata This feature was there earlier with the previous installer. As we are testing out the new installer builder, this feature was not available with the current installer. We'll try to ship out new installer with this feature.

**Comment by rish9511** [comment]
@Raghavdata  
Noted. Will try to ship this with the newer version of Installer

**Comment by rish9511** [comment]
The new installer for windows creates a desktop shortcut. Get the latest installers from 
https://elucidatainc.github.io/ElMaven/
