### ISSUE TITLE
Crash: segmentation fault when loading mzML samples when zlib is enabled

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#42]
I enabled the zlib in the elMaven code (In mzroll.pri it was commented out) and while uploading the mzML samples it was giving an segmentation fault.

PS: I compiled the libmaven as dynamic library for this specific case as there was some issue when I enable ZLIB in static mode.

**Comment by saifulbkhan** [comment]
El-MAVEN v0.8.0 and later will be able to read (mzML and mzXML) samples containing zlib compressed data.
