### ISSUE TITLE
dump/load settings

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#425]
It would be really nice to be able to dump all the maven settings to a file and to be able to read in settings from such a file.

Super useful for debugging obviously, and also could be good for practical use -- I often change a lot of settings when processing data from different methods.

This could potentially overlap with the command line interface.

**Comment by rish9511** [comment]
@sahil21 @chubukov 

To implement the feature dump and load settings, it was decided to clean-up/refactor every part that controls/updates maven parameters and have a defined way of managing maven parameters. To achieve this, we decided the following things (in a very broad sense):

1. Use a controller class to update mavenparameters when UI changes and vice-versa

2. Do not update mavenparameters from the view (all the widgets ). View should not have the power to                 update mavenparameters

The above has only been implemented for PeakDetection Dialog. Particularly the following things have been done:

1. Use default settings file(default_settings.xml) to load maven parameters
2. Use separate class to store PeakDetection Dialog settings
3. Introduction of new controller class
4. Update mavenparameters when PeakDetection Dialog changes
5. Update PeakDetection Dialog when mavenparameters changes

**Comment by chubukov** [comment]
@rish9511 This all seems very reasonable. So only the main options dialog and the peak detection dialog will have the ability to update parameters?

I think one of the issues that caused some headaches is that the mavenParameters object was really being abused and storing a lot of info that didn't really fall into the parameters (we've talked about this before). I would keep that as part of the focus.

**Comment by rish9511** [comment]
@chubukov  No the dialogs won't have the ability to update the mavenParameters object. Controller class will be used to update the mavenParameters.

Yes there are things that should not be part of mavenParameters. We should definitely look into this

**Comment by chubukov** [comment]
@rish9511 perhaps I'm just not familiar enough with what a Controller class. Are you saying that the options dialog is being replaced by a different type of UI element?

Just making sure that the options in the main options are in fact captured in the dumped/loaded settings -- most of the key ones are there.

**Comment by rish9511** [comment]
@chubukov  
Sorry, I should have explained that before. Well, Controller is just one of the components of  [MVC architectural pattern.](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller) whose main responsibility is to update model (in our case, it's mavenParameters) whenever UI changes(in our case, it's options Dialog, peak detection dialog, alignment dialog ). Our aim is to have just one central point that knows when to update mavenParameters. At the moment, they are updated just from everywhere. 
That central point for us will be the 'Controller' class that will know when to update mavenParameters  

There won't be any change in the UI. 

Every dialog box that contains settings(options, peaks dialog, alignment dialog) will be included in this change

**Comment by chubukov** [comment]
@IpankajI it doesn't look to me like https://github.com/ElucidataInc/ElMaven/pull/543#issuecomment-358381756 actually got implemented. It looks like the lastrun.xml file is still being saved in the application directory. Or am I missing something?

**Comment by rish9511** [comment]
@chubukov 
yes, it's being saved in the applications directory as of now. We wanted to ship this feature out so that the users can test it out as it's mvp
We plan to take up the related issues to it in the upcoming sprints :)

**Comment by sp-eldata** [comment]
@rish9511 Agios uses El-Maven on a common machine which is accessed by multiple users. Is that concern getting addressed in this MVP? 

@chubukov Do you want different users on the same machine to be able to save different settings? Not sure if @rish9511 understood the specific use case.

**Comment by rish9511** [comment]
@sp-eldata @chubukov 
> Agios uses El-Maven on a common machine which is accessed by multiple users. Is that concern getting addressed in this MVP?
I am not sure what the concern is actually

> Do you want different users on the same machine to be able to save different settings? 
The user can still save and load back the settings

**Comment by sp-eldata** [comment]
Should've been more explicit. If multiple users are using the same machine, will the settings for one override the others? I believe that is @chubukov's concern. 

@chubukov please lmk if that's not the case.

**Comment by chubukov** [comment]
@sp-eldata yep, that's exactly right (+ the permissions issue, but that's not a big deal). 

If it becomes difficult, I can just change our branch, but I figured this would be a good idea in general and you can better check the cross-platform compatibility.

**Comment by rish9511** [comment]
@chubukov  @sp-eldata 

El-Maven can't distinguish between a user 'A' and user 'B' , hence it's not possible at the moment to store user specific settings in lastRun file. LastRun is meant to save the settings that were being used just before El-Maven  was shut down  
However, each user can save their settings in their folder of choice and load them back whenever they want . e.g if you want to save ms/ms specific settings , you can just save them by the name "ms_ms_userName" and the load them back when you are processing ms/ms dataset

> the permissions issue, but that's not a big deal

@chubukov yes this is an issue for now. We will solve this asap

**Comment by chubukov** [comment]
@rish9511 @sp-eldata I don't want to make too big of a deal of this. You're right that each user can just save their own settings wherever they want. So it's workable.

But the previous behavior was to remember the last settings and I think you did well to try to maintain that behavior. El-Maven certainly can distinguish between users (it can just ask the OS). In fact previous versions did exactly this (On windows, QSettings stored the settings in the registry (separately for each user), and probably in ~/.config on linux).

**Comment by chubukov** [comment]
@rish9511 it looks like window geometry is not saved in the settings. Is that intentional or an oversight?

**Comment by rish9511** [comment]
@chubukov 
We have solved the issues reported above and the latest version has these changes. 
Just wanted to get some feedback around this.
Have you used it yet ? If yes, then what do you feel is missing from it  and how can we make it better

**Comment by chubukov** [comment]
@rish9511 I tested it briefly in the previous version -- just some spot-checks. It seemed to be working properly other than the issues I mentioned.

Let's try to use this to reproduce buggy behavior and create reproducible test cases. That'll be the real test.

Thanks!

**Comment by lparsons** [comment]
👍 for reproducible test cases

**Comment by rish9511** [comment]
@chubukov @lparsons 
Thanks for the feedback
sure it will be helpful when trying to reproduce buggy behavior 

We plan to include rest of the settings(alignment dialog etc) as part of this

**Comment by shubhra-agrawal** [comment]
@chubukov @lparsons All relevant settings are now saved as part of the El-MAVEN project file (.emDB) as well. Closing this thread now.
