### ISSUE TITLE
Isotopic refactoring

### ISSUE THREAD

**Issue by GeorgeSabu** [ElucidataInc/ElMaven#43]
Things to focus on isotopic refactoring:

1. Special Treatment of C13
- [x] Currently there are two places from where label information is to be taken. One in the peak detection dialogue box and other inside the options button on the mainwindow.
- [x] In El-MAVEN all the Isotopic settings are taken from options button. Peakdetection isotope checkbox is not functional.
- [x] If we select or deselect C13 its always finding isotopes of C13
- [ ] There are two places where compute Isotope function is defined. One in isotopic logic and other as the part of the peakdetector.
- [ ] @chubukov  I remember you had some suggestion on how isotopic detection functionality should ideally be. Could you please share with us those suggestions?

2. Pick isotopic peaks even when parent abundance is zero
- [ ] It's come up a few times now that we do a labeling experiment and end up with 100% labeling of one or more metabolites. In this case, when you're doing automated peak picking with a database, you won't pick the parent peak and therefore the labeled peak is lost. It would be kind of nice to be able to specify that maven should look for the isotopes even if the parent isn't there. It would probably have to be a compound-specific option I think -- otherwise, the number of potential peaks completely explodes.
3. Saving/loading mzroll screws up labeling information
- [x] This is a consequence of the "Feng addition" of the way we handle isotope outputs. Loading the mzroll file does not set the sample._C13labeled etc variables. So if you save a project, then reload it, there is no way to export the labeled species when you save to CSV.
4. parentgroup has no peaks
- [ ]  I was seeing some strange behavior with isotope detection, and I started playing with the options a bit to try to figure it out. I set the option "maxIsotopeScanDiff" to 500. This caused Maven to crash in the mzUtils::correlation function, because an empty vector was passed for y. This in turn was due to the fact that BackgroundPeakUpdate::pullIsotopes was called with a ParentGroup with no peaks.I don't fully understand what's going on yet. Hopefully this will be easier as we write out what actually happens during the peak detection and grouping. Should be easy to reproduce with almost any data. @chubukov We are not able to reproduce this. 

@chubukov I am trying to capture all the isotopic related issues into one place so that we can refactor isotopic detection. I have captured reported isotopic issues also into this. I guess this will help us to coordinate refactoring in a better way. Could you please add suggestions you have in isotopic refactoring in this thread. I will keep on updating this list according to your suggestions.

**Comment by chubukov** [comment]
@GeorgeSabu Great, let's put some of these things together

First off, let's put (2) on hold. This is sort of a corner case, and it can be dealt with with the workaround of simply specifying the labeled species in the compound database. 

Let's see if we run into (4) again, but let's not waste time looking for it specifically.

The big one is getting rid of the confusing way that many of the options are set, which covers (1) and (3). 

What I would like to do first is just get a list together of all the places that isotope abundances are used/referenced. I'll start us off:

- decision of whether to look for isotopic species when bookmarking a peak (and same thing for automated targeted peak detection) and create a new peakgroup for each one.
- whether to display the isotopic species in the bar plot widget
- whether to display the isotopic species in the isotopes widget (table)
- whether to export the isotopic species when exporting the peak table to csv
- when bookmarking a peak (or detecting one through the automated process), Maven can checks whether the correlation across samples for the unlabeled peak and the isotopic peak is greater than some cutoff. If it's not, then it decides that it's not the right compound, and doesn't bookmark it
- again, when bookmarking a peak, Maven can check whether some isotope abundances are within the expected range
- whether to treat the isotopic species as different compounds for the scatter plot (I just thought of this one, I don't know if that's ever been an option)
- whether to correct for natural abundance

You get the idea. Right now most of the first bunch are controlled by the "samples are labeled" options, and the last few have their own options under "filter isotopic peaks based on these criteria" (and also it makes sure not to filter on isotopes used for labeling). But then there are also a bunch of related hard-coded options.

What I propose is an "isotope options" dialog box (maybe one panel of the main options dialog, sort of as it is now). This would have essentially a table, with maybe one row for each of the options above, and corresponding checkboxes for C,N,S, and H (maybe we can also leave room to allow more at some point). So the user could specify that C and N isotopes should be displayed in the bar chart and peaks table, and that nothing should be checked for natural abundance. Or whatever. Some of these options have parameters (like the correlation check has a correlation threshold and probably also a minimum peak area threshold), so these would need to be set in the same dialog (actually right now many of these things are hard-coded). Also, for the options related to finding isotopic species, maybe we should put an option for how far to go. For instance, I have a suspicion that while Maven always considers all the 13C species, it only goes up to some m+N for deuterium (I can't find that in the code, so maybe I'm wrong here).

Now that's probably too many options, so we can collapse some of them. For instance, we can say that what goes into the table and what's exported to CSV is always the same. Maybe some other things could be collapsed too.

Maybe let's start by putting the list together, along with the corresponding options, and also the other relevant parameters, like maxIsotopeScanDiff, and we can see if this is a feasible way to approach things? What do you think?

**Comment by chubukov** [comment]
Another place: untargeted peak picking has an option "auto-detect and ignore isotopes". I don't have a firm idea of how exactly this works. Does it work only on things that match formulas in the database? In either case, how much confidence is necessary in assigning a mass to a formula? I don't actually know, and I haven't used this feature much.

**Comment by GeorgeSabu** [comment]
@chubukov Started isotopic refactoring 
Isotopic interface now looks like this.
![options_002](https://cloud.githubusercontent.com/assets/22674403/20722080/45099ee8-b68b-11e6-8b7b-3f4ded135b90.png)
Removed isotopic flag from peak detection
![peak detection_004](https://cloud.githubusercontent.com/assets/22674403/20722083/4890922e-b68b-11e6-83da-8cb72ee17d41.png)
The code is still being refactored. Latest commit https://github.com/ElucidataInc/ElMaven/commit/68685629fe14411b2bf6536395096ca28c41bc59.

**Comment by chubukov** [comment]
@GeorgeSabu looks like a great start!

**Comment by GeorgeSabu** [comment]
@chubukov Now the Isotopic barplot and the peak picking are separate in logic. Some of the bugs that were reported are also not to be seen. I will tag those bugs in here for reference.

**Comment by chubukov** [comment]
@GeorgeSabu Do you feel like the branch is ready for production level (i.e. general agios) testing?

**Comment by GeorgeSabu** [comment]
@chubukov We have tested it in ubuntu. Windows testing going on. Yes, it should be good to go for production testing after windows testing. I will update you as soon as it's done.

**Comment by GeorgeSabu** [comment]
@chubukov I have to take out isotopicWidget also from the peak detection part. Buts it will be good to test the current version after windows testing as lots of code change has been made.

**Comment by sahil21** [comment]
@chubukov There is a small bug that is coming when you do both peak integration and doubles clicking to add to bookmark table. After solving this bug it would be fine.
