### ISSUE TITLE
loading additional samples causes samples widget to not display old samples

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#44]
1. Load some samples
2. Load some more samples

The first set will not appear in the samples widget.  For all other purposes they appear to be in memory (e.g. peak integration and EIC display shows both the first and second set of samples.

I swear I saw this bug discussed earlier somewhere, sorry if it's a duplicate.

**Comment by GeorgeSabu** [comment]
@chubukov This bug is been resolved in this commit https://github.com/ElucidataInc/ElMaven/commit/89fd1549c745646ee5157501c76d187b792d4752.
