### ISSUE TITLE
fake compound from formula in search box

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#440]
#437 reminded me of a small feature I was thinking about for a long time ago. It would be really nice if when you typed a formula into the search box, there was a compound created for the pulled EIC, so that you could pull isotopes, have the formula output, etc.

**Comment by sahil21** [comment]
@chubukov This feature has been implemented and merged to the develop.

**Comment by chubukov** [comment]
@sahil21 Thanks, looks good
