### ISSUE TITLE
pull injection time out of mzml

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#449]
I still have a use case for pulling the injection timestamp out of the mzML file and making it available for either sorting or export.

Was mentioned briefly in https://github.com/ElucidataInc/ElMaven/issues/275

**Comment by sahil21** [comment]
@chubukov This feature has been implemented and merged with the current develop branch. One thing to note here is that meta file will be given more preference to determine the injection order. Let us know how it works out.

**Comment by chubukov** [comment]
@sahil21 seems to be working (only tested once) but it makes #466 and #527 come up front and center

**Comment by sahil21** [comment]
@chubukov We'll take up the issues #466 & #527 in the coming sprint. Closing this one.
