### ISSUE TITLE
get rid of set name row in csv output

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#45]
When outputting to csv from the maven gui, the column headers are in row 1, and the second row has the set name for each sample. The third row onwards has the compound data.

In our hands the second row is just an annoyance -- we always delete that row before doing any further work. It just makes things awkward for further processing. I'm having a hard time imagining a good use case where it really would help -- I say let's just get rid of it unless you can think of a good reason to keep it.

**Comment by GeorgeSabu** [comment]
@chubukov The second row is used for defining the cohorts right? And I remember that this format is used for statistical analysis in MEDAP R package that elucidata uses internally and [metaboanalyst](http://www.metaboanalyst.ca/) and maven output is directly used in them.

**Comment by chubukov** [comment]
@GeorgeSabu I don't see where metaboanalyst reads in this format directly. And I think part of the vision for MEDAP was that the cohorts would be defined on the fly (sort of how the Maven scatter plot does it).

But this is not a big deal -- if you think it's useful, let's just have it be a global option. That seems easy enough.

**Comment by GeorgeSabu** [comment]
@chubukov Could you please explain what you meant by global option.

**Comment by chubukov** [comment]
@GeorgeSabu I just meant a checkbox in the options dialog box that says something like "Include set names in CSV output".

**Comment by GeorgeSabu** [comment]
@chubukov file export dialog will be a better option. The list is in that is very easily customizable.
