### ISSUE TITLE
Detect dual labeled C13/2H isotopes

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#451]
We are currently generating dual-labeled 13C/2H data. The current `mzMassCalculator::computeIsotopes` method does not pick up any peaks that contain 13C and 2H combined.

This combination of isotopes is simply not scanned: https://github.com/ElucidataInc/ElMaven/blob/5f373ec493de36b3acf6d7ef6e884aa594822a98/src/core/libmaven/mzMassCalculator.cpp#L110-L136

**Comment by sahil21** [comment]
@lparsons Thanks for pointing that out. Seems like a minor fix. We'll include this in the next release of El-MAVEN.

**Comment by sahil21** [comment]
@lparsons Merged your pull request #452 to develop. Closing this issue.
