### ISSUE TITLE
better way of specifying blank samples

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#46]
I don't like the way that Maven currently determines whether a sample is a blank injection:

`if (mystrcasestr(filename,"blan")`

It's accident-prone and not at all documented. Let's make this more explicit somehow. For instance an extra column in the samples widget? Happy to hear other suggestions.

Not sure what the right thing to do is for the command-line version. Actually I think that a prefix string (or even a regexp) is ok (e.g. user can specify that samples starting with "BK" are blanks) as long as the default is to not treat any sample as a blank, and it's all well-documented.

**Comment by GeorgeSabu** [comment]
@chubukov I was also thinking about the same issue yesterday. I was thinking in this way. We can add an input box on the sample widget heading side to "Show/ Hide Selected Sample" where the user can input the blank file name prefix. For command line version we can add an extra flag which does the same. Thoughts/ Suggestions?

**Comment by chubukov** [comment]
I think in the gui, we don't need the complication of a prefix. How about we just have a button that marks/unmarks selected samples as blank (similar to check/uncheck). And show the blank samples as greyed out or in italics or some other distinguishing font.

For the command line, a prefix/flag sounds fine to me.

**Comment by GeorgeSabu** [comment]
@chubukov I am just worried about the number of clicks the user has to perform when the number of blank samples is large. Other suggestions are
1) While uploading the samples a popup can appear asking the prefix of the blank samples.
2) Keep a button similar to delete samples called "mark as blanks" where the user can select multiple samples and marking it as blank.

After the user has marked samples as blank we can keep the EIC plots of blank samples as black in color and Italics those samples in the sample table.

**Comment by chubukov** [comment]
Yes, I was imaging that it would be possible to select multiple samples to mark as blanks (like delete or check/uncheck)

**Comment by GeorgeSabu** [comment]
@chubukov ok. We will keep a button similar to delete sample which will mark the samples as blank.

**Comment by sahil21** [comment]
@chubukov This feature has been implemented. You can select/unselect the blank samples. 

Following are the tests that we manually did to confirm this feature:
1. Marking the blank samples as blank decreased the number of groups.
2. Increasing the Min.Signal/Blank ratio decreased the number of groups. 
3. If there are no blank samples then Min.Signal/Blank ratio doesn't affect the number of groups.
4. When I de-selected the samples that has been marked as blank, we got same number of groups as before(without marking any blank sample)

**Comment by chubukov** [comment]
@sahil21 Awesome. Looking forward to trying it out.

**Comment by chubukov** [comment]
This seems to be working fine, thanks!
