### ISSUE TITLE
Unable to save bookmarked peaks

### ISSUE THREAD

**Issue by raaisakuk** [ElucidataInc/ElMaven#465]
Steps followed:
1. Bookmark peaks using SRM widget
2. Save project using Save as option from file menu.
3. Close ElMaven
4. Use Open widget to open the saved file
5. Samples are loaded but can't see the bookmarked peaks anymore

Screenshots shared on Trello board with @sahil21 
El_Maven_v0.2.1

**Comment by shefalilathwal** [comment]
I have the same issue for version 0.2.0-125-gaed63c2 on Mac. Neither the data in the bookmarks table, nor the data in the peak tables gets reloaded from .mzroll file, only the samples are loaded.

**Comment by shubhra-agrawal** [comment]
@raaisakuk @shefalilathwal This issue is because of a recent change in how we store the samples used for every group. It is a known bug and will be handled when we roll out a new version of mzroll files.

Until that is fixed, please clean up the sample file names before upload. They should not contain any spaces or special characters.

**Comment by shubhra-agrawal** [comment]
@raaisakuk @shefalilathwal We have implemented a fix for this which required some changes in the mzroll file structure i.e. if this change is merged, mzroll files from an older version will not be compatible with v0.3.0 and above. We have decided to hold this fix till a consensus is reached about adding backward-compatibility.

Adding backward compatibility is possible but we would like to hear from our users if it is a priority. Would it be a major issue if older mzroll files are no longer supported in El-MAVEN? We can discuss this over email/call if you prefer. Unfortunately, we cannot release this as part of v0.3.0 but in the meanwhile, we can provide you with an installer for this branch if you'd like.

**Comment by raaisakuk** [comment]
@shubhra-agrawal For me, backward compatibility won't be an immediate issue but it should be done at some point I believe.

**Comment by shefalilathwal** [comment]
Adding @sunildhakkad

**Comment by raaisakuk** [comment]
@shubhra-agrawal What was decided finally? We are planning to on-board more people in the lab to use El MAVEN. Whether or not you guys decided to include this feature would make a difference in the workflow steps.

**Comment by shubhra-agrawal** [comment]
@raaisakuk @shefalilathwal This fix has been merged to develop. Backward compatibility has been implemented as well.
