### ISSUE TITLE
BUG - Copy isotopic detail to clipboard copies incorrect values

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#469]
As an example, when copying NADP+ data, the data for label 21 was instead copied to label 14. The bar plot in the software seems correct, but the table copied is wrong.

**Comment by shubhra-agrawal** [comment]
@lparsons Order of the labels and the data were different. This has been resolved and merged to develop. Let us know when you test it out.

**Comment by lparsons** [comment]
@shubhra-agrawal This does appear to be fixed, at least in my limited testing so far. Thanks!
