### ISSUE TITLE
Option to search for search for adducts of compounds

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#475]
Instead of adding many adducts to the knowns database explicitly, it would be useful to provide common adducts as checkboxes so these are identified automatically. (Suggested by Juan Carlos Garcia Canaveras in the Rabinowitz Lab)

**Comment by saifulbkhan** [comment]
@lparsons El-MAVEN (v0.10.0) can now search for adducts of parent ions. We will add documentation regarding this very soon.
