### ISSUE TITLE
Better control of peak integration

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#476]
It seems difficult to understand (at least visually) how the peak intensity is being calculated. It is often necessary to set some background threshold as well as the width of a peak. It's not clear from the interface what those values are set to (perhaps use shading to make this clear?). It is also not easy/possible to change these values either manually or through the setting of configuration parameters. (Suggested by Juan Carlos Garcia Canaveras in the Rabinowitz Lab)

**Comment by chubukov** [comment]
@lparsons I just wrote this in an email to @sahil21 but maybe I should just comment here

Couple of different things going on here. A) I suspect nobody who's not a classic Maven user knows what AreaTop means (as far as I know Maven is the only piece of software that uses this term). (It's a very slightly smoothed height: the average of the highest intensity scan and the two scans around it). So maybe there’s confusion about how the default intensity is calculated. B) I do think some people expect to be able to integrate peaks the way you would do in a more dedicated software that takes on one sample at a time (click on left edge, click on right edge, click on baseline, etc). I think the shift-drag functionality probably should be documented and shown as some sort of tip (not sure people would guess this on their own). (PS I noticed that shift-drag is inconsistent about calculating Area #528).

In general, I guess it would be nice to be able to isolate a particular peak, and do some much more detailed/careful peak integration (tangent/shoulder baselines, specify bounds, etc, etc). That could turn Maven into a more full-fledged choromatographic analysis program. It also seems like a lot of effort and it's not really the way that we use Maven, so I for one haven't been pushing for it. Of course would be very happy to contribute ideas/test/etc if we decided to take this on.

**Comment by raaisakuk** [comment]
@sahil21 I agree with the visual part completely. In the current plot it is really hard to understand what exactly is being integrated. I think some of my feature requests are around this. Now that we are planning to use El MAVEN across the lab, this will become all the more crucial.

**Comment by saifulbkhan** [comment]
This use-case should now be satisfied using the peak-editor widget introduced in v0.11.0. Closing this.
