### ISSUE TITLE
Wrong expected mz from mzroll

### ISSUE THREAD

**Issue by shubhra-agrawal** [ElucidataInc/ElMaven#479]
v0.2.2

Loading an mzroll gives wrong expectedMz in the peak table. Say, I process some data in negative ionization mode and save the mzroll. Loading this file back into El-MAVEN shows the expectedMz as per positive ionization mode.

**Comment by chubukov** [comment]
@shubhra-agrawal @sahil21 yeah I saw this too: https://github.com/ElucidataInc/ElMaven/issues/366 . For some reason I thought it was fixed -- guess i haven't tried it in a while.

**Comment by shubhra-agrawal** [comment]
@chubukov @sahil21  Missed that one somehow. I'll mark this as a duplicate issue.
