### ISSUE TITLE
reading ms/ms files from qExactive

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#48]
I'm sharing an example of an ms/ms file from the qexactive instrument. Maven has difficulty loading this file properly either in mzML or mzXML format (from msconvert/readw).

[dropbox link](https://www.dropbox.com/sh/e6z0dda5d5cj7jp/AAAhfBvkTrySclsNNID0t9d_a?dl=0)

**Comment by GeorgeSabu** [comment]
@chubukov I was going through the .mzxml and .mzml files both of them are Zlib compressed. That's one of the reasons MAVEN have difficulty in loading .mzxml/.mzmlfiles. MAVEN is not able to do Zlib decompression. Even though the code for the same exists it not working. We are working on this as a separate issue.

In msConvert after Zlib compression option was deselected. I was able to see the spectrum in the .mzxml format through MAVEN. But no spectrum was seen in .mzml format. We will update on the problem regarding .mzml format soon.

**Comment by saifulbkhan** [comment]
El-MAVEN v0.8.0 and later will be able to read (mzML and mzXML) samples containing zlib compressed data.
