### ISSUE TITLE
RT correction

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#480]
Perform RT correction based on the complete m/z_RT matrix. Although this is not strictly necessary if the integration process is improved, it could be a nice feature to add and it is a necessary feature to perform real peak picking for untargeted metabolomics.

From Juan Carlos in Rabinowitz Lab

**Comment by chubukov** [comment]
This is just another word for alignment right? In theory this exists, but in practice it's still very buggy. #39 #328 #377 #312 maybe others

**Comment by lparsons** [comment]
Juan Carlos agrees and we'll track the progress on the issues you mentioned, thanks @chubukov.
