### ISSUE TITLE
Isotopic barplot checkboxes are dependent on bookmark checkboxes

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#489]
There is a dependency issue in checkboxes of Isotope Detection tab [Options Dialog]. Isotope barplot and isotope widget checkboxes are dependent on "Bookmark, peakdetection & export" checkboxes.

**Comment by shubhra-agrawal** [comment]
Can't reproduce in v0.7.1-beta. Closing it.
