### ISSUE TITLE
ms/ms files in mzML format

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#49]
Here's an example where it looks like Maven is not correctly processing an mzML file created by msConvert. The mzXML created by the deprecated mzWiff utility works fine, however.

dropbox maven/bug_reports/2016_11_09_ms_ms_mzML_from_abi4000

**Comment by GeorgeSabu** [comment]
@chubukov In this .mzxml file is not Zlib compressed but .mzml is Zlib compresed. I guess now this is similar to issue #48.

**Comment by GeorgeSabu** [comment]
@chubukov I converted the .wiff into .mxML files with msConvert the following settings.
<img width="960" alt="msconvert" src="https://cloud.githubusercontent.com/assets/22674403/21688062/757474c0-d339-11e6-836d-b39f9beec7b9.PNG">

I am able to load the files properly(**with Zlib compression disabled**) and also able to get the same EIC plots as in SeeMS.

Here are some of the screenshots from SeeMS(**using the .wiff file**) and El-MAVEN (**using the converted .mxML files**)


<img width="960" alt="1_maven" src="https://cloud.githubusercontent.com/assets/22674403/21688201/ea4be2a6-d339-11e6-8827-4912c3680d1d.PNG">
<img width="960" alt="1_msee" src="https://cloud.githubusercontent.com/assets/22674403/21688202/ea4ed2c2-d339-11e6-908e-06816abb2907.PNG">
-----------------
<img width="960" alt="2_maven" src="https://cloud.githubusercontent.com/assets/22674403/21688235/12afefc6-d33a-11e6-8c53-4cac8bdb0429.PNG">
<img width="960" alt="2_msee" src="https://cloud.githubusercontent.com/assets/22674403/21688236/12b035b2-d33a-11e6-814a-36e206b615e5.PNG">
---------
<img width="960" alt="3_maven" src="https://cloud.githubusercontent.com/assets/22674403/21688237/12b0acea-d33a-11e6-966c-608d09cbce61.PNG">
<img width="960" alt="3_msee" src="https://cloud.githubusercontent.com/assets/22674403/21688238/12b52892-d33a-11e6-9910-0fac007945e7.PNG">
---------
<img width="960" alt="4_maven" src="https://cloud.githubusercontent.com/assets/22674403/21688239/12b566f4-d33a-11e6-9fd8-f361050e5277.PNG">
<img width="960" alt="4_msee" src="https://cloud.githubusercontent.com/assets/22674403/21688240/12b5aa2e-d33a-11e6-8cb0-b7ded65ece8f.PNG">

**Comment by shubhra-agrawal** [comment]
@chubukov Can we close this issue?
