### ISSUE TITLE
Infinite Loop in Alignment

### ISSUE THREAD

**Issue by IpankajI** [ElucidataInc/ElMaven#490]
While doing alignment using Loess Fit Alignment Algorithm and setting Minimum Peak Intensity to a high value leads to infinite loop.

**Comment by IpankajI** [comment]
@chubukov @lparsons @sahil21 Data transmission between python and Qt is verified by sending keywords (start processing/end processing). In case of errors these keywords get missed and in that case python is waiting for infinite time and Qt is waiting python to exit for further processing of data. We have few meetings and came up with a better solution. We are not using keywords anymore instead we'll use signals and slots mechanism to verify data transmission.

**Comment by saifulbkhan** [comment]
Loess fit was removed. Closing this.
