### ISSUE TITLE
R-squared values in Alignment Visualization

### ISSUE THREAD

**Issue by IpankajI** [ElucidataInc/ElMaven#491]
R-squared values ( current R2 and previous R2 in AlignmentVisualization) are fluctuating a lot for different groups while using Loess Fit. These statistical values should be between 0 to 1 (currently, most of the time I am getting more than 1). And most of the time previous R2 should be less than current R2 that is not happening right now.

**Comment by chubukov** [comment]
What is this R^2 value actually used for? As far as I can tell, you're calculating the correlation across samples between the old retention times and the new retention times (after alignment). I guess what this tells you is how significantly the alignment rearranged the samples. Is that what it's meant to represent? I would be wary of using this as a metric of alignment quality or anything like that.

**Comment by saifulbkhan** [comment]
Not relevant anymore (Loess fit). Closing.
