### ISSUE TITLE
Calculate Area of smoothed spline 

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#496]
Related to #474

**Comment by sahil21** [comment]
@chubukov What should be the spline bounds for shift drag integration? min and max position of mouse drag event or actual bounds of spline?

Example - 
![image](https://user-images.githubusercontent.com/21240516/35083145-a26ba546-fc43-11e7-8606-f9ca9651a1c7.png)

**Comment by chubukov** [comment]
@sahil21 there was a comment on this thread which is now gone in which you asked an excellent question about how shift-drag should actually operate. I commented here: #528

**Comment by sahil21** [comment]
@chubukov I was going to post it again. (Earlier I thought the question was not clear)

Here is the question (for documentation purpose):

What should be the spline peak bounds in case of shift-drag integration? Whether it should be min and max position of mouse drag event or actual spline bounds.

**Comment by shubhra-agrawal** [comment]
@sahil21 @chubukov SplineArea is being calculared using the dragged bounds, exactly like peakArea. Available in v0.7.0 and above
