### ISSUE TITLE
isotopes in positive mode 

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#50]
Something is going horribly wrong in the calculation of isotope masses in positive mode.

I uploaded some sample data in Maven/bug_reports/sample_positive_mode_data as well as a source file.

Load a few samples and scroll to any compound (try L-Glutamic Acid for a really nice clean example). Click to bring up the isotope barplot and doubleclick to integrate. I use a ppm of 10.

If you look in the table, the expected isotopes are missing, and it looks like all the mass windows are about 2 daltons lighter from what they should be.

_Is there a negative ionization (causing -1 instead of +1 for the mass calculation) hardcoded somewhere?_

Note this doesn't happen if doing automatic peak integration through the peaks dialog.

Maven 776 does not have this bug.

**Comment by GeorgeSabu** [comment]
@chubukov This problem is resolved. The change will be reflected on the commit https://github.com/ElucidataInc/ElMaven/commit/f83c3ec72602af8c37b4551a67f3bbb369fa4505. This was because IonizationMode was not set properly. Before it was done in the run() function in background_peaks_update.cpp which we had moved to a function in peakdetector.cpp. So now it was not getting set properly. Now I have set it before it starts pullIsotopes() function.

**Comment by chubukov** [comment]
@GeorgeSabu Great, thanks, will test ASAP on my end.

I haven't looked at the code in detail, but this just jumped out at me: `if (_mw->getIonizationMode())`

Are you properly handling neutral ionization mode (0)?

**Comment by GeorgeSabu** [comment]
@chubukov We haven't changed the logic in ionization. It's the same as previous MAVEN 776. I guess we have to do a thorough check on this. Especially when ionization method is neutral inside the sample file. Do you have some samples on which I can perform tests or can I take a sample and change the polarity as 0 and use it?

**Comment by chubukov** [comment]
@GeorgeSabu Do you have the GCMS data I shared at some point? That should be neutral mode. It worked ok in Maven 776. If not, I'll upload some more.

I was just trying to make sure that nothing silly was happening where neutral was treated the same as unknown.

**Comment by GeorgeSabu** [comment]
@chubukov I have the GCMS data. I will do checks with that.

**Comment by chubukov** [comment]
Closing this issue -- let's have a discussion of GCMS data separately. I'm actually not convinced that "neutral" mode is the right way to think about that data -- it's not that there's no ionization, it's just that people usually think of the fragments in terms of the ionized m/z, so you're not calculating that m/z the same way.
