### ISSUE TITLE
El MAVEN not starting up

### ISSUE THREAD

**Issue by Raghavdata** [ElucidataInc/ElMaven#506]
As mailed by @danielbraas:

"Anyway, the reason I am emailing you is that I have set up a new Windows7 PC in my office and have been running El-Maven on it. Unfortunately, after analyzing a sample set in negative mode, I had to close Maven and when I tried to re-open it, it never opened similar to what I had described with my other PC here. I tried to open it from the command line and below you can see that there was no error message, but it still didn't open...any idea? "

**Comment by Raghavdata** [comment]
@danielbraas 
Can you check if you can see El-MAVEN in your task manager (Ctrl + Shift + Esc). Please do this after you have tried to start El-MAVEN. This will help us confirm if El-MAVEN is running in the background or not.

@rish9511 @sahil21 FYI

**Comment by sahil21** [comment]
@Raghavdata Please close the issue if this is resolved.
