### ISSUE TITLE
m/z info in compound widget

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#51]
This is present in all maven versions.

-If you provide m/z in the compound database, that m/z is displayed in the compounds widget
-If you provide formula as well as m/z, the m/z you provide is displayed, but the m/z calculated from the formula overrides it for all purposes (like pulling EIC)
-If you provide formula but not m/z, the m/z displayed is actually the neutral mass (and the correct ionized m/z is calculated from the formula and used for pulling EIC)

This is quite inconsistent, the last case in particular is misleading. 

Not 100% sure what the right solution is, especially since ionizationMode can change after loading the compound database (it's determined when samples are loaded). I guess my vote is to display calculated m/z and trigger a refresh of the widget if ionizationMode changes. 

Maybe if we do that let's have ionizationMode displayed somewhere in the main window (I think this has come up before).  Maybe in the corner by the formula and ppm boxes. (and take it out of the main options).

Please don't forget about neutral ionizationMode as well.

**Comment by chubukov** [comment]
@GeorgeSabu I guess I have no idea how this should work with polarity-switching methods. I actually feel like I don't really have a good grasp of how Maven is used with such methods, so perhaps you can judge better, since I think you've worked with polarity-switching data from MVH?

**Comment by GeorgeSabu** [comment]
@chubukov I was also thinking about the polarity-switching case. Let me play around with the dataset and related code. Will update you soon on this.

**Comment by rkdahmiwal** [comment]
We analyzed possible solutions, here are the cases we thought about

While uploading database

Case-1 If compound formula is not given and m/z is given

	 Compound m/z will be same as of given m/z

Case-2 If compound formula is given

	 Pop-up will ask user to select which m/z to choose, either given m/z for every compound 
     in database or calculated m/z for compounds based on their formula and ionization mode.
	 
![mz1](https://cloud.githubusercontent.com/assets/25100240/25611988/a9070d20-2f46-11e7-985b-32d450568e39.png)
	
If the user selects to use calculated m/z based on formula and ionization mode

	SubCase - 1 Samples are already being loaded (present in El-Maven) 
	
Then polarity(ionization mode) of samples will be used in m/z calculation

SubCase - 2 Samples are not being loaded (present in El-Maven)
	
	Another pop-up will come up and ask user to select the polarity

![mz2](https://cloud.githubusercontent.com/assets/25100240/25611987/a8fe0d42-2f46-11e7-9d88-a64b60742dd4.png)




Note - 

1)	Legend widget will show the m/z of compounds which are used by application and if m/z of compounds got changed then ligand widget will be updated(refreshed). 

2)	After all this(m/z calculation) if more samples are being uploaded then m/z of compounds will change according to polarity available in samples given their formulas are available.

3)	If user changes the ionization mode present in top right corner of main window of El-maven then m/z of compound will be changed according to ionization mode if their formulas will be available.  

4)	All the changes made to m/z of compounds are only for current selected database.

5)	If the polarity get changed manually or automatically, then the current m/z will be updated if their chemical formula is present. No matter what m/z calculation option user selected for current database at the time of uploading.

**Comment by chubukov** [comment]
@rkdahmiwal I think you basically have the logic exactly right, but I would try to limit the number of pop-ups, since they're mildly annoying.

For instance, for the initial loading, I think it's ok to just use whatever is currently selected for ionizationMode in the main window (I guess it's positive by default).

The first dialog you suggest ("do you want to change the m/z based on formula and ionizationMode") is also probably not necessary, and I could see how it could be actually confusing (it sounds like the change is permanent, but in fact it will still respond to a change of ionizationMode). I think in any case, using an "incorrect" m/z when the formula is provided will lead to very awkward behavior if the user tries to pull isotopes -- the parent peak will not be the same as the "C12 parent" and the isotopes are going to have the wrong masses, it's all going to be quite a mess I think. For it to work, we would have to change the pullIsotopes code to not use the formula. I could see that actually being a good idea, but I think that's not really necessary for now.

Otherwise everything you wrote sounds good to me.

**Comment by sahil21** [comment]
@chubukov 

The Ligand widget’s m/z column will be updated according to charge used by EIC Pulling/Peak detection.
![image](https://user-images.githubusercontent.com/21240516/27337565-6a29c220-55f0-11e7-8594-067861795f49.png)

**1. Compound with No Formula**

![image](https://user-images.githubusercontent.com/21240516/27337635-a63fbb70-55f0-11e7-8ea3-b505ac57750f.png)

![image](https://user-images.githubusercontent.com/21240516/27337638-a8716bb4-55f0-11e7-9e38-7d2a04d20791.png)

**Results:** Ionization Mode and charge changed but the m/z is same


**2. Formula is there but no M/z**


![image](https://user-images.githubusercontent.com/21240516/27337684-c2ddcaec-55f0-11e7-914a-50304b8ad3c2.png)

![image](https://user-images.githubusercontent.com/21240516/27337688-c5542c30-55f0-11e7-9bc0-2f873665f34c.png)

**Results:** Changing Ionization mode and charge modifies the m/z column

**3. Formula and m/z both are in the compound database**

![image](https://user-images.githubusercontent.com/21240516/27337706-d85b9386-55f0-11e7-9175-db173ac28e75.png)

![image](https://user-images.githubusercontent.com/21240516/27337711-db281a80-55f0-11e7-912c-be2ce946621d.png)

**Results:** M/z column in the compound database widget is updating irrespective of the fact that m/z is already present in the compound database.

**Comment by chubukov** [comment]
@sahil21 basic functionality seems to be working fine. Are there any edge cases that you weren't sure about?
