### ISSUE TITLE
Loess Fit Alignment w.r.t. expectedRt

### ISSUE THREAD

**Issue by IpankajI** [ElucidataInc/ElMaven#514]
Currently, Loess Fit Alignment is always done w.r.t. median rt. it should use expected rt if available.
Copy and paste from #39 -
" 2b) What I want to do is have another option at the core of the algorithm, where on each sample, you run processCompounds using a special compound database that's only for alignment. Then fit some kind of spline from the expected (reference) RTs to the observed RTs for all the compounds you find, and use this to interpolate the whole RT vector. This is in many ways much much easier than aligning all samples at once. For the gui, the current dialog box could be reused to a great extent, and the command line version is even easier. "

**Comment by chubukov** [comment]
@IpankajI to be clear, I'm suggesting this as an additional option, not necessarily as the default behavior. It's really a different type of alignment than "standard". Not sure if other software does this or not.

**Comment by shubhra-agrawal** [comment]
Closing this since Loess Fit has been deprecated.
