### ISSUE TITLE
Automated Installers/packaging

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#524]
This will save a lot of time at the end of the release. Also, we can provide daily builds to the users.

**Comment by lparsons** [comment]
I'd like to bump this in priority. See #1063, #1095, and #1096.

The Maven project (which this was forked from) has automated builds for all three platforms: Windows, MacOS, and Linux (using AppImage). See https://github.com/eugenemel/maven/blob/master/.travis.yml and https://github.com/eugenemel/maven/blob/master/appveyor.yml.

In addition to saving time and frustration, this makes the build process transparent. Right now there is no assurance that the binaries are actually built from the code on GitHub without modification.

**Comment by shubhra-agrawal** [comment]
@lparsons There has been major progress on this recently for Mac and Windows platforms. Will tag you on the PR once it's ready! Please accept the collaboration invite you must have received.

**Comment by saifulbkhan** [comment]
From release v0.8.0 onwards, installers are now built and uploaded to the releases page automatically whenever a tag is pushed.
