### ISSUE TITLE
Not able to build El-Maven for current develop branch

### ISSUE THREAD

**Issue by DeepakSharmaElucidata** [ElucidataInc/ElMaven#525]
<img width="1279" alt="screenshot 2018-01-10 18 38 18" src="https://user-images.githubusercontent.com/30472110/34774543-beb1dea0-f635-11e7-9d2d-1e1e81a2bb78.png">

It's something related to libdate library

**Comment by shubhra-agrawal** [comment]
@DeepakSharmaElucidata This library was added recently as part of a feature addition. Please use v0.2.2 for now. We will let you know when this issue is resolved.

**Comment by shubhra-agrawal** [comment]
@DeepakSharmaElucidata This issue has been fixed and merged to develop. You can successfully build El-MAVEN on Mac now.

**Comment by DeepakSharmaElucidata** [comment]
@shubhra-agrawal: Thanks!
