### ISSUE TITLE
Reproducibility: Add parameters used for peak picking to output CSV file

### ISSUE THREAD

**Issue by shashj199** [ElucidataInc/ElMaven#526]
In order to bring reproducibility to the method of peak picking in El-Maven, can we export all the parameters used in the header of output CSV file? We can also output a second CSV file for this, the file should be mandatory as part of an output from El-Maven.

**Comment by sahil21** [comment]
@shashj199 We implemented something like this in the last sprint #425. Do check that out.

**Comment by sp-eldata** [comment]
@shashj199 We are way ahead ;)

**Comment by shashj199** [comment]
@sahil21 @sp-eldata I think compulsion is of the essence here. We cannot expect users to export settings file separately every time. The settings must be with the output. For example: If you use featurecounts (a package to get gene counts), then along with the output it adds a header which tells the exact command used for generating the output. 

# Program:featureCounts v1.5.2; Command:"featureCounts" "-T" "8" "-t" "exon" "-g" "gene_id" "-a" "/home/ubuntu/HumanGenome/genes.gtf" "-o" "Exp9_10.csv" "10A01_S3_L001_R1_001Aligned.sortedByCoord.out.bam" 

I don't see any such header in Maven's output which might make it trickier and sometimes impossible to retrieve settings used for processing.

**Comment by sahil21** [comment]
@shashj199 I agree with you that settings are important but we try to avoid putting lots of information to CSV files. That is the reason we have an option to export settings separately. But soon we'll implement something like project file for El-MAVEN which will solve this issue (Imagine project file like pptx for Microsoft powerpoint)

The project file will be one single file which will contain all the information related to the experiment like samples used, Peaks found, settings used. It is basically all the output files present in a zipped folder. So the user doesn't have to output multiple files.

**Comment by chubukov** [comment]
@sahil21 the only thing I would add to this thread is something that I mentioned very briefly in the other thread: it would be good if the same settings file could be used to run the command line version. That would allow @shashj199 to re-run automated peak picking and hopefully get an identical result back.

**Comment by sahil21** [comment]
@chubukov That's the plan :)

**Comment by saifulbkhan** [comment]
The problems discussed here should can be considered "solved" now with emDB available. Settings and CSV export are also separately available as well.
