### ISSUE TITLE
shift-drag and area calculation

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#528]
I was trying to figure out whether integration by shift-drag actually sets the peak bounds for Area calculation, or whether it only identifies the peak. I took a peak and shift-dragged such that I covered the center but not the entire peak area. 

It turns out it's inconsistent. For the "parent" it looks like it does restrict the left/right bounds for the Area calculation. But for the "C12 Parent" I get the larger area that would get by shift-dragging over the entire peak.

**Comment by chubukov** [comment]
I took a survey of our group, and it was pretty unanimous that the desired behavior was to use the dragged bounds directly to set the peak bounds and calculate area or smoothed (spline) area. (i.e. each sample would get a peak created with the exact same bounds).

**Comment by chubukov** [comment]
That said, I haven't looked carefully at how this might affect some other metrics like quality.

**Comment by saifulbkhan** [comment]
Similar to #344, region of integration for isotopes can be restricted to parent peak's x-range. Closing this.
