### ISSUE TITLE
Make it easier to see intensity plots and isotope fraction plots together

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#529]
One issue our users have complained about is that the new isotope barplot is vertical, instead of horizontal like the intensity barplot. Also, making it a widget separated it from the main window. Those two things make it difficult to see the intensity and isotope fractions at a glance, which was much simpler and more intuitive in the old maven (see screenshot).
![image](https://user-images.githubusercontent.com/645128/34896704-d1404e9c-f7b8-11e7-9fef-30817c92d6b3.png)

This is related to #75.

**Comment by chubukov** [comment]
@lparsons I agree with you that the layout in the old version was actually better. This was one of the earliest performance-related improvements -- @sahil21 and @GeorgeSabu found that a lot of the crashes in the old version were due to the fact that the boxes in the isotope plot were slow to be drawn, and would cause a crash if the UI changed before the drawing was done. At least in our hands, this definitely helped with the crashing.

@sahil21 worth revisiting now that you have a better grasp on how to handle the multithreading, etc? Not sure.

There's also an additional thread hanging around about the aesthetics of the isotope plot.

**Comment by chubukov** [comment]
Was just thinking about this more today. One of the ways the widget is actually better is if you have a large number of samples (because you can resize it). The barplot sort of suffers from this too -- once you get above 50 samples or so, it's really hard to read. So I'd be ok with a solution where we move both of them into a widget which can be nicely resized and repositioned, and which keeps the barplot and fraction plot lined up.

**Comment by lparsons** [comment]
I think moving it out to a widget is probably fine, as long as it's easy to move around and save the position from session to session. And I think the big issue is making the two barplots comparable. One vertical and one horizontal is not intuitive.

**Comment by lparsons** [comment]
I had some more feedback from our lab regarding the isotope plot. The issue revolves around very small fractions. It was noted that in the old plot the bar were closer together with black lines separating the colors. This made it relatively easy to see very small fractions and small differences.
![image](https://user-images.githubusercontent.com/645128/38506841-f3f6782a-3be8-11e8-93fb-29f569ad3076.png)

In the new plot, the bars are separated and there is no black separator, making it much more difficult to see small fractions. Also, it seems that fractions less that 1% are not displayed at all in the barchart:
![image](https://user-images.githubusercontent.com/645128/38506950-497e30e4-3be9-11e8-923d-6ca69972dc82.png)

I'm not convinced that the older plot was optimal, but certainly for such small fractions and small differences, it was much better. A few ideas:
* Eliminate space between bars
* Add black separator lines
* Change colors so they are not so similar (see [qualitative color brewer schemes](http://colorbrewer2.org/#type=qualitative&scheme=Accent&n=3) for an example).
* Allow user to "hide" the parent fraction, only plotting the heavier isotope fractions.
* Allow the user to change the scale (limits) from 0-1 to something else (e.g. 0.5 - 1.0)

**Comment by shubhra-agrawal** [comment]
@chubukov What if one could zoom into the barplot? That should solve the readability problem. We are a bit hesitant on moving it out to another widget as it needs to be open at all times and that might add to the clutter. 
@lparsons The isotope plot pops out if you click the top-right button on the dock. You can resize and reposition the isotope plot anywhere to align it with the barplot if it's required. Once we make the plot horizontal and the other UI suggestions, it should be easy to see both plots side-by-side. Something like this,
![image](https://user-images.githubusercontent.com/28925846/39174542-a2e252d6-47c5-11e8-8d49-60e27c7b3d19.png)

**Comment by lparsons** [comment]
I think that's a step in the right direction. One other thing people have asked about is if the popup values could be easier to read, and perhaps only show the values for the specific sample the user is hovering over.

As a side note, many users, myself included, don't seem to be able to "save" a widget configuration. Each time I load El-MAVEN, the window is set to some standard size and the widgets are back to some default placement.

Finally, I've noticed that El-MAVEN is nearly unusable on a 13" laptop, presumably due to minimum widget sizes that make it nearly impossible to see bookmarks, isotope plots, and the data. (Perhaps these two things should be new issues?).

**Comment by shubhra-agrawal** [comment]
@lparsons Need more clarification on the "Hide parent fraction" issue here. Could you please elaborate on the use case? 

Is this a visibility issue where hiding the parent fraction would help see the other labels clearly?
with Parent:
![image](https://user-images.githubusercontent.com/28925846/40353975-68e53118-5dd0-11e8-91bc-99bc022166cc.png)

without Parent:
![image](https://user-images.githubusercontent.com/28925846/40353153-6c3e41c6-5dce-11e8-92ae-26a83cfbacf1.png)

Or is there a use case for calculating fractions without the C12 parent?

@chubukov thoughts?

**Comment by chubukov** [comment]
@shubhra-agrawal that last image seems fine, but I have no strong preference about whether there's a colored bar for the parent or not. Don't really see a use case for excluding the parent from the calculation. Most annoying visual aspects to me are

- the difficulty of reading the numbers when they're on top of somewhat dark bars
- similar colors blend together

Some other potential improvements (most of these are hanging around on various other threads):
- pool fractions <x% into "other"
- somehow highlight the sample that was clicked on in the EIC window

**Comment by lparsons** [comment]
Sorry for the delay in responding. I haven't evaluated all of the options, so I'm not necessarily advocating for any particular solution. The general consensus from the lab is that the previous layout was significantly more useful that the current layout. One of the big issues was the ability to see small fractions (e.g. < 1%) in the graph. One strategy would have been to stretch the graph out by adjusting the scale and not plotting the parent. There are some issues with this though, and I'd rather try other things first. But an example would be:
![image](https://user-images.githubusercontent.com/645128/40677926-17984e8a-634d-11e8-8ce3-000d40913cbd.png)

**Comment by shubhra-agrawal** [comment]
@lparsons @chubukov You can set the minimum abundance threshold in the Isotopic Detection tab of Options menu for now. The default value is 1 which is why all fractions with <1% abundance do not show up. I'll bring this option to the plot itself where you can set what percentage goes to "other".

**Comment by shubhra-agrawal** [comment]
@lparsons @chubukov The following changes have been shipped out as part of 0.4-beta:

- Horizontal bars
- Persistent plot (earlier, plot used to disappear when user clicked outside the widget)
- Colours are more differentiated
- Black bar between labels for clear separation
- Labels can be checked/unchecked from within the widget
- Pool fractions less than x% as 'other'
- Legend with label information is visible at mouse position for better visibility of bars
- Sample bars are in the same sorting order as the intensity bar plot

Remaining changes:
- Update plot on selecting from compound widget and peak table
- Highlight selected sample bar
- Natural sorting in isotope labels
- Saving widget configuration

Let me know if I'm missing any remaining changes.

**Comment by lparsons** [comment]
See #679 and #703

**Comment by saifulbkhan** [comment]
Closing this. Most requests seem to have been covered now.

**Comment by saifulbkhan** [comment]
Although I can still think of some visual improvements to both barplots. Also the fact that one is embedded in the EIC and one is a widget by itself will prevent a good "side-by-side" comparison.
