### ISSUE TITLE
Isotope widget does not show the sample name being displayed

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#531]
The isotope widget shows the isotope breakdown for a given sample in the selected group. However, there is no way to tell which sample's data is being displayed. Adding the sample name to the widget would be very helpful.
![image](https://user-images.githubusercontent.com/645128/34896867-6fe3fefe-f7b9-11e7-8f79-cd75782cc21a.png)

**Comment by chubukov** [comment]
Good idea. This would be good for a bunch of other widgets too (e.g. covariants widget)

**Comment by shubhra-agrawal** [comment]
@lparsons @chubukov We have added a sample drop down list which displays the current selected sample. User may also change samples directly from the isotope widget. Available in v0.3.0-beta and v0.3.0.
