### ISSUE TITLE
Isotope widget displays all possible isotope combinations

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#532]
Isotope widget displays all possible isotope combinations, even when there are none detected in the sample. The rows with all zeros should not be displayed.

![image](https://user-images.githubusercontent.com/645128/34896932-a94f968a-f7b9-11e7-9a3d-4d12910d889a.png)

**Comment by shubhra-agrawal** [comment]
@lparsons Any row with a zero intensity and abundance value will be hidden in the isotope widget in order to reduce clutter. This has been merged to develop.

**Comment by tonyshenghui** [comment]
Probably in the process of fixing this issue, a bug was introduced and now the software does not always show rows with >0 intensity in the isotopes widget. In my particular case, this happens for metabolites with both 13C and 15N. Please see the attached screenshot, where the isotope plot shows there is 9.83% for phenylalanine [9-13C, 1-15N] while the isotopes widget only lists the carbon isotopomers. Thank you for looking into this issue. I'd happy to answer any questions you have. 

![Screen Shot 2019-05-03 at 4 19 17 PM](https://user-images.githubusercontent.com/13423252/57164544-737a7900-6dc2-11e9-8473-5e22ba449034.png)
