### ISSUE TITLE
Indicate the "high quality" isotopes in the Isotopes widget

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#533]
Also, when bookmarking a peak group, only some of the (presumably highest quality) isotopes are included. It would be nice if the widget indicated which of the isotopes are considered "high quality", and thus would be bookmarked.
![image](https://user-images.githubusercontent.com/645128/34897093-5ef263d2-f7ba-11e7-80fe-bcbda1bbf9d9.png)

**Comment by shubhra-agrawal** [comment]
@lparsons the isotope widget shows all possible combinations, therefore it also shows intensity values for all isotopes detected. There is no quality criteria in play here. The last isotope is M+8 so you might have to scroll farther down in the widget to find it. 

Let us think about possible solutions to #532 to avoid looking at zero-intensity rows/scrolling too much.

**Comment by lparsons** [comment]
@shubhra-agrawal I realize that the isotope widget shows all possible combinations, however, when bookmarking a compound, not all isotopes are bookmarked. Somehow, ElMaven is deciding that some combinations shown in the isotope widget should not be bookmarked. What is that criteria? Is it simply that all isotopes with some measured intensity are bookmarked?

**Comment by shubhra-agrawal** [comment]
@lparsons This should have been resolved by the #567 fix. Are you still able to reproduce this on your end?
