### ISSUE TITLE
Sort isotopes in bookmarks list, peak table, and exported peak table

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#534]
Export of bookmarks is sorted in a confusing (seeming arbitrary) order. It would be nice if it was sorted by compound and then medMz (which mimics how the values are ordered when Copy and Pasting).

**Comment by lparsons** [comment]
![image](https://user-images.githubusercontent.com/645128/35460181-124a06c8-02b1-11e8-851c-28d955a6f919.png)

**Comment by IpankajI** [comment]
@lparsons This is updated sorting -

![sorting](https://user-images.githubusercontent.com/19559785/35909569-079be634-0c1a-11e8-8663-041e3e81b4fd.png)
Expanding a group will always display it's children in ascending order, but this sorting order can be changed by clicking header items ("#" ,"ID", etc.). Currently, table is sorted with column with header item "ID"
