### ISSUE TITLE
bookmarking by star button leads to crash if there are zero peaks

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#536]
I most often run into this by mislicking.

I don't know if anyone even uses the star button to bookmark, maybe it can be disabled?

**Comment by shubhra-agrawal** [comment]
@chubukov The crash used to happen when there was no highlighted group in the EIC widget. That has been fixed and merged to develop. Will be part of v0.4.1

As for disabling it, we will take that into consideration along with the other UI clean-ups we're planning.
