### ISSUE TITLE
Marking peak group with isotopes, doesn't actually mark any peaks

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#537]
Once a peak group and isotopes are in bookmark list, marking the entire compound group (all isotopes, etc. while folded up), doesn't actually mark any of the subgroups as good and exporting shows nothing marked as at all.

1. Mark peak group as good
![image](https://user-images.githubusercontent.com/645128/34897498-40264d90-f7bc-11e7-8cad-a4930a8f9890.png)

2. Expand and see that none are marked
![image](https://user-images.githubusercontent.com/645128/34897509-4afed9e4-f7bc-11e7-9c0d-53aa2fb499ba.png)

3. Export, and nothing indicates any are marked
![image](https://user-images.githubusercontent.com/645128/34897548-81a2260e-f7bc-11e7-8257-69bb534dc5e8.png)

Not entirely sure what should happen, perhaps all should be marked as good (or bad). The current behavior is misleading and pointless (IMHO).

**Comment by chubukov** [comment]
@lparsons hmm, I thought we fixed this a while ago #143. Does seem weird that not even the parent gets labeled. Maybe we only took care that "export good" worked, and didn't check the label column. Not sure.

**Comment by lparsons** [comment]
@chubukov Yes, it appears that "export good" does work, but the label column is not properly populated, making export all useless in this case. I don't see any commits tagged with #143, if you can point me to the right place in the code, perhaps I could tackle this one...

**Comment by saifulbkhan** [comment]
@lparsons With v0.10.0, C12 parent isotopes are now tied to their parent groups and changing the good/bad state of one will set the same state for the other. The C12 groups exported in CSV will be exported with its curation appropriately.
