### ISSUE TITLE
Adding NetCDF library to the installation instructions/installer

### ISSUE THREAD

**Issue by Raghavdata** [ElucidataInc/ElMaven#539]
NetCDF library is not installed in natively on machines and thus would have to be explicitly installed. This needs to be present in the installation manual and the installers as well (eventually).

**Comment by shubhra-agrawal** [comment]
@Raghavdata Instructions for installing netcdf library are present in README file. The library is also sent out as part of the installer on Windows at the moment. 

We're working on bringing it for Mac as well.
