### ISSUE TITLE
alignment error "received data: 0 bytes"

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#540]
This is off the `fix_alignment` branch. I used the alignment test dataset that I shared at some point.

![image](https://user-images.githubusercontent.com/13080968/34907793-0bfd6d6e-f852-11e7-8e5e-b71e2be9187b.png)

This is after it ran for maybe 30 minutes? Definitely an improvement over just running forever or crashing! But the error message doesn't really help me troubleshoot.

These were my alignment settings
![image](https://user-images.githubusercontent.com/13080968/34907800-38a2357a-f852-11e7-80bc-e4ceeb9befa2.png)

And the log
![image](https://user-images.githubusercontent.com/13080968/34907813-70967e82-f852-11e7-8d99-2ad11decce59.png)

**Comment by IpankajI** [comment]
@chubukov Thank you for reporting the issue. Minimum Peak Intensity is 100000 and in this case very few peaks are qualifying this barrier and consequently, very few groups are getting generated. When running Loess Fit (python script) over these groups, all peaks are rendered as outliers and in this case we are getting 0 bytes of processed data.
    I'll be updating the code for user-friendly error-message (removing bytes like words) and looking into python-script for any enhancement.

**Comment by chubukov** [comment]
@IpankajI Are you sure that's what's going on? There are 11000 groups in the peak table after the alignment process is finished.

**Comment by chubukov** [comment]
@IpankajI FWIW, I did get alignment to work nicely for a smaller set of less-badly-aligned samples

**Comment by chubukov** [comment]
I got this message again today on some data that I thought was quite innocent-looking.

**Comment by lparsons** [comment]
Not sure how good the data is, but I've run into that error as well as some pretty hairy looking EIC plots after "align wrt expectedRT". I suspect it has to do with cases where multiple peaks are found for a compound (isomers). I've held off reporting any issues with alignment until it's expected to be working. I suggest that the feature get a "beta" label in the interface until it's ready, btw.

**Comment by lparsons** [comment]
@IpankajI Sounds good, does this mean you will be making it clear in the UI (options pane) which features are still experimental? ;-)

**Comment by sp-eldata** [comment]
@lparsons We'll do that. Thanks for flagging it again :) 

@sahil21 Can we also make it clear for other features? Also, are you creating the issue for discussing which features to 'deprecate'?

**Comment by sahil21** [comment]
@sp-eldata @lparsons Sure we will add something like 'beta' tag in the UI for all the experimental features like new alignment and baseline algorithms #583 
For deprecate features, we have filed an issue #586

**Comment by saifulbkhan** [comment]
Another old Loess fit issue. Closing.
