### ISSUE TITLE
peaks pre/post alignment -- tricky/corner cases

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#550]
What happens when a user gets some peaks into a table (doesn't matter how) and then runs alignment, and then goes back to the old peaks?

It looks like something expected but mildly stupid happens. The peak RT is still recorded in the old units, but the EICs are going to be displayed in the new units. So now your peak position is not even on top of the peak.

Additionally if you now add more peaks into the table, the RTs are going to be inconsistent between the peaks.

I'm not sure what the best solution is. You could imagine something complicated where each peak keeps track of its RT vector. But I'm ok with alignment just clearing the peak tables. Maybe a hybrid is that a single peak table keeps track of whether it's using aligned or not aligned rts.

**Comment by lparsons** [comment]
I like the idea of a single peak table keeping track of (and reporting) whether it uses aligned or not-aligned RTs. Keeping both pre and post alignment data available would facilitate this and #551, assuming it's not too much of a performance or memory hit.

**Comment by chubukov** [comment]
@lparsons this sounds good to me too. 

There are definitely a few complications to deal with -- e.g. i guess a peak table should be locked into read-only if you're in the "wrong" view, so you can't add new peaks. And what if you run a new alignment with different parameters -- not clear what should happen.

We had a call around alignment last week and agreed that implementing #551 would be really useful for testing/debugging. So @IpankajI maybe we keep this issue in mind as we go and think about some potential ways to handle it.

**Comment by chubukov** [comment]
@sahil21 @IpankajI can you comment on how these corner cases are meant to be handled in the latest version?

**Comment by saifulbkhan** [comment]
All peaks in all peak-tables in a session are re-assigned their peak RT value based on the peak's minimum topmost and maximum scan values, if alignment is performed after peak-group creation. In fact most other peak attributes are also recalculated after which each peak-group's statistics are also recalculated. Available with v0.11.0. Closing this.
