### ISSUE TITLE
bars in alignment visualization plot pre/post alignment

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#552]
In the alignment visualization plot (the one with the purple bars on top of the RT line) I only see the two bars (pre/post) after I undo alignment.

Additionally, samples are not ordered consistently.

**Comment by lparsons** [comment]
Inconsistent ordering of the samples is a major issue. However, in order to improve readability, I would suggest that the bars for each sample share the same color coding as in other widgets.
![image](https://user-images.githubusercontent.com/645128/35445985-58368d9e-0281-11e8-8b05-b8645b40a4d8.png)

**Comment by IpankajI** [comment]
@chubukov @lparsons This will be the ordering and color mapping among sample project widget, alignment visualization and bar-plot.

![oredering1](https://user-images.githubusercontent.com/19559785/35914542-984f837a-0c29-11e8-8841-4b2af1e9e846.png)

After reversing the sample order

![ordering2](https://user-images.githubusercontent.com/19559785/35914568-ae83a130-0c29-11e8-9654-d52656c554d0.png)

@chubukov Could you give us a little more insight to first issue in this thread, screen shot of settings and resulted  alignment visualization plot would be more helpful

> In the alignment visualization plot (the one with the purple bars on top of the RT line) I only see the two bars (pre/post) after I undo alignment.

**Comment by saifulbkhan** [comment]
The order and colors of bars in the group RT deviation widget are now synced with that of the sample widget. Closing this.
