### ISSUE TITLE
Failitate identification of exactly one peak for a list of compounds

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#554]
Our lab frequently follows a workflow where they want to identify exactly one peak per compound in a list of compounds from tens to hundreds of compounds long.

Thier current approach involved loading the compound database and going through the list, one by one, identifying the correct peak, and then either copying that peak to an Excel spreadsheet or bookmarking it.

We believe that the targeted automatic peak detection in El-MAVEN has the potential to greatly speed-up and improve this workflow, however, currently the interface is lacking in some features that would make it useful. Right now, when a user runs targeted peak detection, El-MAVEN finds 0-*N* peak groups for each compound (where *N* is configurable) and puts those detected peak groups into a table. For a given list of, for example, 100 compounds, this will produce a list of say 150 peaks. The user must then go through each of 150 peaks and evaluate those, marking them good or bad. They then have a second step to go through the list of compounds for which no peak was detected and determine if they want to include the possibly lower quality peak. This is significantly *more* work that the old manual workflow.

We propose that El-MAVEN make it easy to identify compounds for which:

1. There was exactly 1 peak detected - these are likely done
2. There were more than one peak detected - these require manual review to select the appropriate peak. Once reviewed, they can go into the "done" category
3. There were no peak detected - depending on this list, the user may want to relax the parameters if there are too many in this category, or simply review them to manually determine if they want to select a peak.

I envision a workflow where the user reviews compounds/peaks until they have put a check mark next to each compound indicating it was reviewed and a peak selected.

**Comment by lparsons** [comment]
@sp-eldata I updated this issue to reflect my updated thinking on the workflow issue we discussed when you were here. 

@shubhra-agrawal I'd be happy to have additional discussion about this, perhaps on a call sometime next week.

**Comment by chubukov** [comment]
@lparsons @sp-eldata @shubhra-agrawal This sounds great and makes a lot of sense to me.

An additional feature that I think would be related to this is to improve the covariants widget a little bit to make it clear if the same peak (or a very highly correlating peak) was picked for multiple compounds.

**Comment by chubukov** [comment]
@lparsons the only thing I would add is that through experience with the filters, expectedRt, etc we've mostly eliminated the step of going through and marking every peak good/bad -- we generally just keep everything now. But I still agree with your suggestions.

**Comment by sahil21** [comment]
@lparsons @chubukov Now user can easily review the compounds which are left out after automated peak detection. The compounds which are present in the peaks table are _marked green_ in the compound's widget. Now users don't have to go through the whole list of compounds to find out which compounds are missed. Here is an example:

![issue_554](https://user-images.githubusercontent.com/21240516/38912646-20b57cc8-42f4-11e8-9a68-bab18ab3ff6f.gif)

This UX addition takes care of multiple peaks table too. Depending on what the last peaks table user interacted with, the compounds in the compounds widget will be highlighted accordingly. 

Let us know your feedback/suggestions around this.

PS. This only solves part of the issue. We'll get back to you on how we are going to solve the rest of the issue.

**Comment by sahil21** [comment]
@lparsons @chubukov This UX addition will be part of v0.3

**Comment by saifulbkhan** [comment]
Using ranks to filter for the top [X] groups, should take care of this. Although rank calculation itself can do with some work (for which we have separate issues). Closing this.
