### ISSUE TITLE
Export Group Summary Matrix adds an extranous blank line after the headings

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#555]
Exporting the Group Summary Matrix from a peak table or bookmarks list adds a blank line after the headings. This makes sorting in Excel a bit difficult, and importing into other downstream analysis a bit more complicated than necessary. It would be nice to not include that blank line.

**Comment by chubukov** [comment]
@lparsons That's reserved for the set names and actually the second drop down option in the file save dialog is "group summary and exclude set names".

@sahil21 @shubhra-agrawal why don't we just make "without set names" the default? It's certainly more popular here as well.

**Comment by lparsons** [comment]
@chubukov Thanks, didn't realize that. And yes, I'd vote for making the default be without set names. And perhaps change the naming of the options to "Groups Summary Matrix Format" and "Groups Summary Matrix Format with Set Names"?

**Comment by lparsons** [comment]
Or perhaps reduce to one option and only export set names if the actually exist?

**Comment by chubukov** [comment]
Apprently the reason for having it originally was that metaboanalyst likes it? (#45) I don't use metaboanalyst, so I never bothered verifying this.

**Comment by lparsons** [comment]
I would prefer something where one selected "Group Summary Matrix format" and then, in the next dialog one had some radio buttons to select csv vs tab and turn on/off set names.

**Comment by shubhra-agrawal** [comment]
@lparsons That sounds like a good idea. We will consider that when we're making design changes. For now, I will change the option names to "Groups Summary Matrix Format" and "Group Summary Matrix Format with Set Names" and remove the empty line in the first option. Does that sound okay?

**Comment by lparsons** [comment]
@shubhra-agrawal Yes, that sounds like a good plan, thanks.

**Comment by shubhra-agrawal** [comment]
@lparsons @chubukov This has been implemented and merged to develop. The extra line will be present in the "Group Summary Matrix Format with Set Names" if there is no cohort information but not in the default format. I'm creating a new issue for the design suggestion made by @lparsons.
