### ISSUE TITLE
Ability to adjust baseline calculation per peak group (or at least per m/z window)

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#556]
We have noticed that for certain chromatography methods, some compounds are noisier than others. We can improve the integration of those peaks by adjusting the background calculation, but that is a global adjustment. It would be useful to be able to adjust this on a per compound basis.

**Comment by chubukov** [comment]
@lparsons i agree that this would be useful but i also think the entire baseline calculation is due for an overhaul. (one of the issues I've harped on is that you can get a different baseline just by shrinking/expanding the EIC window. but in general it's just kind of hacky). I think the elucidata team was planning on taking this up in one of the next couple of sprints.

**Comment by chubukov** [comment]
@lparsons PS thanks a lot for all the great suggestions!

**Comment by raaisakuk** [comment]
We have been using the global option but change it with every metabolite that we integrate.

**Comment by chubukov** [comment]
@raaisakuk @shubhra-agrawal seems like this is a pretty error-prone workflow. E.g. if you save to mzroll and re-load, do the individual baseline parameters get restored? I don't think they do -- I don't think that information is stored for the peakgroup level at all.

**Comment by raaisakuk** [comment]
@chubukov I generally export peaks in one go but otherwise when I bookmark peaks I thought it saves everything. Once the area has been calculated, it should not change, right? @shubhra-agrawal @shefalilathwal If I remember correctly you use similar workflow with different baseline for different metabolites. Do you not bookmark those together?

**Comment by saifulbkhan** [comment]
Available as part of the "Peak editor" widget (accessible from peak-table) starting v0.11.0. Closing.
