### ISSUE TITLE
Export compound category in Group Summary Matrix format

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#558]
We are exploring the use of category in the compound database to help us identify compounds that readily assessed by automated peak detection vs. those that require some additional review. Including the "category" in the bookmarks/peak table as well as exporting it would make the category variable more useful in this context.

**Comment by lparsons** [comment]
This is similar to #589

**Comment by lparsons** [comment]
Did #608 address this?

**Comment by shubhra-agrawal** [comment]
@lparsons #608 does not address this. 

The category column serves a specific function here i.e. to mark amino acids, nucleic acids etc so users can sort compounds by category in the manual workflow. Although, I am not sure how many people use it. For your use case, maybe we can add another column called "Notes" and make it visible in the compounds widget as well as the CSV?
@sahil21 thoughts?

**Comment by shubhra-agrawal** [comment]
@lparsons We have added a 'note' column in the compound widget. You can add this column to your compound database and it will be reflected in the UI. This change will be part of the v0.7.0 release. Closing it now.
