### ISSUE TITLE
cannot delete groups corresponding to isotopic species when bookmarked from peaks table

### ISSUE THREAD

**Issue by MyaSteadman** [ElucidataInc/ElMaven#56]
once I select a peak as good, I am unable to remove it from my bookmarked list.

**Comment by chubukov** [comment]
@MyaSteadman maybe you can give a little more detail? I haven't had any issues with this.

**Comment by MyaSteadman** [comment]
sure, when I use "g" to select a peak as good, it adds it to my bookmark list. however, when I try to remove a peak from that list I can delete it. I've tried hitting the delete button, the backspace button, and right click, remove this group, as well as the "delete group" button in the task ribbon above the bookmarked window. the blue highlighting will move down to the sample below the one I tried to delete, but the line and selected group doesn't get removed from the list. I don't know if it's still included in the export list because I haven't gotten that far yet, but I will let you know when I'm finished with this file.

**Comment by chubukov** [comment]
Mya and I talked about this today and were able to reproduce the behavior. This happens specifically when you are scrolling through a peak table (resulting from automatic peak picking) that includes isotopic species, and you try to bookmark one of the isotopic peaks. This seems to screw up a couple of different things, but most notably you indeed cannot delete the group from the bookmarks table.

**Comment by GeorgeSabu** [comment]
@MyaSteadman @chubukov This bug is resolved in the isotopic refactoring. #43

**Comment by chubukov** [comment]
Confirming that this appears to be resolved.
