### ISSUE TITLE
Mac installer not working on Sierra 10.12.6 - v0.2.4-beta

### ISSUE THREAD

**Issue by sp-eldata** [ElucidataInc/ElMaven#564]
From a user at Yale: 

I have a macOS Sierra Version 10.12.6. I was able to unzip the folder and install El Maven. (screenshot attached)

After the installation was complete I tried to open the application and then I got this message: Check with the developer to make sure El_Maven_v0.2.4-beta works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS. (screenshot attached)

![1516905646341](https://user-images.githubusercontent.com/22666033/35440104-f4a9e8dc-02c3-11e8-96aa-a6cccc7d1355.jpg)

**Comment by rish9511** [comment]
This has been fixed in the v0.2.4.
Please re-open if you face it again
