### ISSUE TITLE
lastDatabaseFile is ignored

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#568]
I was waiting on this since I thought it might end up being part of #425 but it looks like we're only keeping the peak picking settings there (which is totally fine).

It used to be that when you went to load a file in the compound widget it would default to the last used location (and it would also pre-load with the last used file upon opening). Now it defaults back to the installation directory every time. The registry setting `lastDatabaseFile` is still getting properly populated, looks like it's just not being used.

This broke several releases ago (maybe even a year at this point).

**Comment by sahil21** [comment]
@rish9511 Let's add this in the `lastrun.xml` file.

**Comment by rish9511** [comment]
@sahil21 @chubukov 
imo such things should be part of configuration file(`Application Settings.conf`) and not `lastRun.xml`.  Thoughts ?

Anyway, if `lastDatabaseFile` is being updated with right values, we should make sure that it's used to update the Database as well.

**Comment by rish9511** [comment]
fixed in commit 46e6043ccd5c8700bf1ba02e0e422867da60854c
