### ISSUE TITLE
autosave?

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#57]
@MyaSteadman was telling me about a frustrating experience in which she was processing some data doing manual peak picking, and ElMaven crashed after she had picked a large number of peaks (thus a lot of time was wasted).

Obviously we have to try to fix these crashes, but what do you think about an autosave feature? It takes less than a second to write the current bookmarks table to csv, and probably not much more to write an mzroll. An option to enable autosave every N minutes, or even after every bookmarked peak, could be kind of nice.

The details need to be thought through. Could we save mzroll in the background, or would the slowdown be too much? (I'm not sure). But I think it's definitely worth thinking about.

**Comment by sahil21** [comment]
@chubukov This feature has been implemented. 

Ways to activate this:
1. Mark peaks good/bad either through EIC Widget or table dock widget
2. Bookmarking the peaks.
