### ISSUE TITLE
Isotope widget and peak hover intensity always displays "height" regardless of peak quantitation type setting

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#571]
The bookmark table displays "intensity" in the specified *Peak Quntitation Type* (sic) (e.g. AreaTop,  Height, etc.). However, the Isotope Widget and Peak hover always displays the intensity quantified using the "Height" method.
![image](https://user-images.githubusercontent.com/645128/35535437-923a4b60-0511-11e8-8a19-d81a0d9640ad.png)
![image](https://user-images.githubusercontent.com/645128/35535427-8a42e930-0511-11e8-9f2f-2adc1918d706.png)

**Comment by saifulbkhan** [comment]
@lparsons The isotope widget will now show intensity using the globally selected quantitation type, starting v0.10.0.
