### ISSUE TITLE
Deleting peak groups from a large peak table is extremely slow (0.2.4 beta, Windows)

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#573]
With a peak table of ~500 peaks, deleting peak groups becomes very slow (at least 3 seconds per peak group). Attempting to delete 10 or more can cause ElMaven to become unresponsive for quite some time. So far I haven't replicated this issue on my build of the `develop` branch on Linux, but I have confirmed this on 0.2.4 beta on Windows.

**Comment by lparsons** [comment]
I can confirm this issue on Linux as well.

**Comment by sahil21** [comment]
@lparsons This issue is there in the previous versions also. One solution I can think of is putting the delete groups function on a separate thread so that it doesn't make the UI unresponsive.

**Comment by saifulbkhan** [comment]
The latest v0.11.0, should help with this issue. Closing.
