### ISSUE TITLE
ElMaven not reloading last used settings (0.2.4 beta, Windows)

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#574]
Restarting ElMaven does not reload the last used settings. This occurs using the 0.2.4 beta build on Windows. This does not appear to be a problem on my build of the develop branch on Linux.

**Comment by rish9511** [comment]
@lparsons  thanks for reporting the issue.
We are looking into it

**Comment by sp-eldata** [comment]
@lparsons Have you seen this on one machine or multiple?

**Comment by lparsons** [comment]
@sp-eldata Since this is the beta version, we've only tested it on the one machine.

**Comment by shubhra-agrawal** [comment]
@rish9511  Tried reproducing this in Windows 7 and 10. Last saved settings is working fine on Win10 for both installer and build versions. Win7 installer version is going back to defaults. Will check the build version too and let you know.

@lparsons @sp-eldata FYI

**Comment by rish9511** [comment]
@lparsons  
when El-Maven shuts down it shows the path where the last ysed settings were saved. e.g `saving the settings at /path_to_folder/lastRun.xml` . Could you please check if the file is getting updated or not? 
This way we will know if it's the problem with loading them back or is it that we are not able to write in that location.

**Comment by lparsons** [comment]
Actually, I'm running Linux, but @LiChenPU has a Windows machine that is exhibiting this issue. Li, can you check to see if the file is getting updated? If you need help figuring it out, let me know (or stop by my office) and we can sort it out. Thanks.

**Comment by LiChenPU** [comment]
ElMaven reports it is attempting to save the settings in: `C:/Program Files (x86)/El-Maven/El-Maven 0.2.4 beta/bin\lastRun.xml`, which doesn't seem right. That file doesn't get created either.

**Comment by lparsons** [comment]
Is there some way we can confirm what specific revision the build is from? Or better yet, is there a documented process to build and create the installer on Windows/MacOS?

**Comment by rish9511** [comment]
@lparsons @LiChenPU 
Writing files in `C:/Program Files (x86)/El-Maven/El-Maven 0.2.4 beta/bin\lastRun.xml`  requires admin rights. You can temporarily solve this by running El-Maven in admin mode or installing it in different directory that does not require Admin rights . 

We have addressed this issues by storing `lastRun.xml` in user-config location. The next release will have this feature

**Comment by rish9511** [comment]
@LiChenPU @lparsons 
Closing this as this has been fixed in v0.2.4
