### ISSUE TITLE
Broken links in the build section.

### ISSUE THREAD

**Issue by sonu-jun3** [ElucidataInc/ElMaven#576]
![screen shot 2018-02-01 at 12 12 40 pm](https://user-images.githubusercontent.com/5160140/35664759-64315a58-0749-11e8-9d50-abc42c825ac8.png)
![screen shot 2018-02-01 at 12 14 56 pm](https://user-images.githubusercontent.com/5160140/35664814-9098394a-0749-11e8-95ba-efd1b2a5487d.png)

Steps to reproduce-
1. Go to build section of the github documentation
2. Click on the link **windows** or **Ubuntu**

**Comment by shubhra-agrawal** [comment]
@sonu-jun3 Removed the old installation links. The website link is provided instead.

**Comment by lparsons** [comment]
BTW, the form is a bit awkward when downloading more than once (should recognize the email was already "registered"). Also, the filenames don't seem right (they have `_old`, *e.g.* `El-Maven-v0.2.4_old.exe`)

**Comment by rish9511** [comment]
@lparsons 

> BTW, the form is a bit awkward when downloading more than once (should recognize the email was already "registered")

we too want to get rid of in but in the future. We introduced the forms today only so it's mvp 

>  the filenames don't seem right (they have _old, e.g. El-Maven-v0.2.4_old.exe)

We will update the new installer today in some time.
