### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by sonu-jun3** [ElucidataInc/ElMaven#577]
Seems like download and install Qt5.6 link is broken
Check below image for more details
![screen shot 2018-02-01 at 12 34 15 pm](https://user-images.githubusercontent.com/5160140/35665450-43e368a6-074c-11e8-99cf-b2688a8c4115.png)

![screen shot 2018-02-01 at 12 32 08 pm](https://user-images.githubusercontent.com/5160140/35665403-28dcd25e-074c-11e8-8b46-60faea877050.png)

**Comment by lparsons** [comment]
Seems like this link works now: http://download.qt.io/official_releases/qt/5.6/5.6.2/qt-opensource-mac-x64-clang-5.6.2.dmg

**Comment by shubhra-agrawal** [comment]
@sonu-jun3 Fixed and merged to develop. Thanks for pointing it out!
