### ISSUE TITLE
Make spelling and capitalization of El-MAVEN consistent across documentation and webpages

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#594]
Currently, most of the documentation in GitHub ([`README.md`](https://github.com/ElucidataInc/ElMaven/blob/develop/README.md), etc.) references El-MAVEN as "El-MAVEN". However, the main webpage at https://elucidatainc.github.io/ElMaven/ uses "El Maven" ([History section and HTML page title](https://elucidatainc.github.io/ElMaven/)), "[ElMaven](https://elucidatainc.github.io/ElMaven/)", and "[Elmaven](https://elucidatainc.github.io/ElMaven/Why-ElMaven/)". There should be exactly one proper spelling that is used consistently.

**Comment by shekhjha** [comment]
Strongly agree! :)

**Comment by shubhra-agrawal** [comment]
Updated the website with the correct spelling. Thanks for filing!
