### ISSUE TITLE
setting isotope options for manual peak picking

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#6]
This was always problematic also in Maven 776, but I really can't get it to work at all in EL Maven 0.2.

It seems that no matter which options I set, I cannot get N15-labeled species to show up when bookmarking a peak. (I can get C13N15 species, but not N15 only). The peaks are clearly there in the spectrum.

Can you put together a working example? Tell me if you need data files.

If you're actively working on refactoring the isotope options as we discussed, then we can wait until that's finished.

V.

**Comment by GeorgeSabu** [comment]
@chubukov We will solve this with the isotopic refactoring that we are going to do. It will be good to get an isotopic data on which we have to test.

**Comment by chubukov** [comment]
I was able to get 15N-labeled species to show up, and I think I might have some extra insight here. Somehow, the mass window for the 15N-1 species is being set with a ppm tolerance of 0. That would actually explain why I was often not getting the peak.

Let's revisit this after refactoring, but I wanted to get that information in.

**Comment by GeorgeSabu** [comment]
@chubukov Could you please share with the data set with which I can reproduce the bug. And also the peak or m/z and RT of the parent peak for which I can see the 15N isotope.

**Comment by GeorgeSabu** [comment]
@chubukov When I tried marking the peaks manually with an isotopic data I am getting N15 species without any change in settings here are the screenshots for the same. 
![parent_valine](https://cloud.githubusercontent.com/assets/22674403/19724645/0bc189d6-9b9f-11e6-904d-045ec8fc71e4.png)

![15n_isotope_of_valine](https://cloud.githubusercontent.com/assets/22674403/19724650/127909e8-9b9f-11e6-8389-8f926b2e6e0f.png)

I am playing around with isotopic data more. Let me see if I can reproduce the issue you pointed in some way.

**Comment by chubukov** [comment]
@GeorgeSabu I've made a video and uploaded some samples on dropbox in MAVEN/bug_reports/2016_10_26_no_15n

**Comment by GeorgeSabu** [comment]
@chubukov Saw the video. Got the issue will update you as soon as possible.

**Comment by chubukov** [comment]
Don't know if you caught it but note that the 13C+2 window was also being set to zero ppm.

**Comment by GeorgeSabu** [comment]
@chubukov Yes. I saw it set to 0ppm. Now I am thinking. Is this the same reason why we didn't get all the peaks same as MAVEN 776 when we did a comparison between MAVEN-776 and El-MAVEN(This was in the presentation that we prepared for EL-MAVEN).

**Comment by GeorgeSabu** [comment]
@chubukov His problem is resolved. It was the problem related to GUI values not getting properly connected to settings value. Changing the settings related to isotopes in the options dialogue will control. This is the commit in which the update is been made https://github.com/ElucidataInc/ElMaven/commit/d3c12dbc17671640564509e14194802a9678f42d.

**Comment by chubukov** [comment]
Ok great Sabu. I'm going to sort of call this done, because indeed, this exact bug has been resolved.

However, I still am getting some very strange behavior wrt isotope picking. Somehow it has to do with the stored settings, because I get different behavior depending on what order I do things in. Will start a new issue.

**Comment by GeorgeSabu** [comment]
@chubukov We have to put bullet points on things that have to be taken care when we are refactoring isotopic code. I guess we can incorporate all the isotopic issues and points to be taken care while refactoring isotopes into one issue with checkboxes. It will be easier to track I guess.
