### ISSUE TITLE
mzML parsing problem with negative mode thermo data

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#600]
If I use msConvert to convert negative mode QExactive data to mzML format, maven is not able to import it.

- mzXML works fine
- Positive mode data works fine.
- Negative mode data from a waters qTOF works fine

I was almost ready to switch everything we do to mzML instead of mzXML but now I realize I didn't test this particular case!

**Comment by sp-eldata** [comment]
@chubukov El-Maven not Maven ;) 

Putting this link here as it might come out useful: https://github.com/pymzml/pymzML This is a Python parser for mzMl files.

**Comment by chubukov** [comment]
@sp-eldata ok

It's of course possible it's not negative mode per se but some other subtle difference between the methods. I should share the files -- are we still doing dropbox or do we have another solution?

Should also mention that the generated mzML looks fine by eye and opens fine in seeMS.

V

**Comment by chubukov** [comment]
I just wanted to highlight that this is a medium-high priority issue for me. Can you let me know if it fits into any of the upcoming sprints? If not, I'll see if we can tackle it ourselves.

**Comment by sahil21** [comment]
@chubukov Sure, we can take this up in the next week. Could you upload the data to Dropbox?

**Comment by chubukov** [comment]
@sahil21 I believe I was able to resolve this by playing with msConvert. I'm going to keep this open for a little while to see if I actually understand the issue, but for now the only problem is the thing that comes up all the time about the poor function naming (#116)

**Comment by shubhra-agrawal** [comment]
@chubukov Checking in to see if mzML files are still posing a problem for Thermo data. 
Also curious about what changes were required in msConvert to be able to process your dataset (in case you remember)

**Comment by chubukov** [comment]
@shubhra-agrawal As far as I remember all I needed to do was upgrade to the latest version. It's currently working fine for us with these settings 

```
mzML=true
filter="peakPicking true 1-"
```
