### ISSUE TITLE
Showing same values for Max S/N and Max Quality in output of automated peak detection

### ISSUE THREAD

**Issue by sunil20dhakad** [ElucidataInc/ElMaven#602]
I am working on untargeted unlabelled data, I did peak picking using Automated Feature Detection. I found that the max S/N and max quality columns have same values. I am not sure whether these should be same or not.

**Comment by shubhra-agrawal** [comment]
@sunil20dhakad Max S/N is getting overwritten. This is why you see the maxQuality value in both the columns. This has been merged to develop.
