### ISSUE TITLE
Use Match Fragmentation panel to set m/z tolerance for MS/MS data

### ISSUE THREAD

**Issue by shubhra-agrawal** [ElucidataInc/ElMaven#607]
For targeted MS/MS peak detection, Q1 and Q3 tolerance have to be adjusted from the SRM widget currently. The amu windows in the SRM widget should only be used for EIC visualization (i.e. how the mass cut off window works for LCMS data) and tolerance for automated peak detection should be provided from the Match Fragmentation panel in Peaks dialog. The panel is currently grayed out.

**Comment by saifulbkhan** [comment]
Turns our "Match fragmentation" had a different use altogether. Closing this.
