### ISSUE TITLE
Plots in Isotope Plot Widget get disappeared

### ISSUE THREAD

**Issue by rish9511** [ElucidataInc/ElMaven#615]
Steps to reproduce:
1. Find peaks with/without Isotopes 
2. Use the _Isotope plot widget_ to see the plots
3. Click anywhere outside the _Isotope plot widget_ to make the plots disappear

Expected behavior:
The plots should keep showing

**Comment by shubhra-agrawal** [comment]
@rish9511 Merged to develop. This is part of the 0.4 beta release.
