### ISSUE TITLE
New Alignment Algorithm

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#623]
**Challenges**

- The current alignment algorithm does not work for 'badly misaligned' data
- Current algorithm depends on peak grouping

**Comment by shashj199** [comment]
@sahil21 @IpankajI @chubukov We evaluated obiwarp algorithm from XCMS package and found it to be very helpful in aligning badly misaligned data. The source code of obiwarp is available in C++ [here](http://obi-warp.sourceforge.net/). We summarised the analysis in a knowledge repo which can be accessed [here](https://polly.elucidata.io/polly-knowledgerepo?polly-notebook-name=El_Maven_Alignment_Polly_260218_1327&polly-project-id=51).

**Comment by chubukov** [comment]
@shashj199 @sahil21 I did look through this notebook. It looks good -- quite similar to what I got with this dataset using xcms online.

Do you want more datasets to work with? Does it make sense to start implementing/linking obiwarp? 

There were some other issues around loess alignment too right?

**Comment by sahil21** [comment]
@chubukov Sure, more datasets will be helpful. 

> Does it make sense to start implementing/linking obiwarp?

Let's do that after testing with a couple more datasets? 

> There were some other issues around loess alignment too right?

Are you talking about alignment in general or specifically loess fit alignment? If obiwarp works fine, does it makes sense to keep loess fit or Poly Fit in El-MAVEN?

**Comment by shashj199** [comment]
@chubukov I think it will be more helpful if we can sit together and look at these algorithms in more detail. Basically, we can discuss what more these algorithms have to offer for El Maven and how El Maven is lacking in some aspects when we compare it to XCMS. Let us know your thoughts.

Thanks

**Comment by IpankajI** [comment]
@chubukov 
OBI-Warp is added to ElMaven and verified internally, please look over this [PR message](https://github.com/ElucidataInc/ElMaven/pull/666) and give your feedback.

**Comment by lparsons** [comment]
We are testing this out, and were able to get it to run. However, when we look at the Alignment Viz widget, we don't see any obvious changes. Should we see something on this plot? It's possible the test data we're using isn't poorly aligned enough in the first place, but it would be nice to know what we should expect to see. 

Also, we did have one crash, which may or may not have been alignment related. I got a crash reporter dialog, but it wasn't clear if this was the new Sentry logging. Can you confirm that you got  the report (I included my email (lparsons@princeton.edu) in the message. Thx.

**Comment by chubukov** [comment]
@lparsons @IpankajI This seems to be working reasonably well in my hands. The "Alignment PolyViz Widget" gives the standard plot you'd get in xcms. I think there was another thread hanging around about the various alignment visualization widgets -- I don't think all three of them are needed.

**Comment by shubhra-agrawal** [comment]
@chubukov @lparsons @sahil21 There are other open threads around visualisations and optimisation etc. Closing this one! Will start a new thread around which algorithm and visualisations should be removed (if any)
