### ISSUE TITLE
Highlighting area based on manual integration in the EIC window

### ISSUE THREAD

**Issue by raaisakuk** [ElucidataInc/ElMaven#625]
If while manually integrating only the area which is going to be integrated is highlighted that would help. As currently only the peaks are circled the user won't be able to tell if the whole area under the peak was integrated or just parts of it.

![image](https://user-images.githubusercontent.com/33527542/36809916-6075c5e4-1c97-11e8-863e-3e1fbf4938ff.png)

**Comment by chubukov** [comment]
@raaisakuk @shubhra-agrawal this would be good if the integration type is set to "Area". If it's Height or AreaTop, it'll be misleading -- the circles are actually better for that.

**Comment by shubhra-agrawal** [comment]
@raaisakuk @chubukov Sounds like a good idea in general. The peak highlights can stay but only the integrated area will be colored. The rest of the EIC can be greyed out. Would also make it very clear which peak corresponds to the curated group and which ones are neighbouring peaks. The highlight moves on moving the cursor, this would be a more concrete visual.

Let us discuss this internally and see if this is feasible!

**Comment by saifulbkhan** [comment]
This was taken care of in v0.10.0. Closing.
