### ISSUE TITLE
Isotope plot doesn't update list of isotopes until new compound is selected

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#627]
After unselecting isotopes (e.g. uncheck D) from the Isotope Detection options dialog, if I continue to look at the same peak I'm on, the isotope plots show all of the isotopes for the unselected isotopes (e.g. D and C13). However, if I select a new compound, the widget updates to show only the current list of isotopes (e.g. just C13). Minor issue.

**Comment by lparsons** [comment]
Duplicate of #703

**Comment by saifulbkhan** [comment]
#703 was closed. Closing this as well.
