### ISSUE TITLE
Unable to use El-Maven again once it crashes on mac

### ISSUE THREAD

**Issue by sunil20dhakad** [ElucidataInc/ElMaven#632]
I am working on untargeted metabolomics datasets. While working on El-Maven on mac it got crashed for some reason but I am not able to use it after it crashed. I am not able to use any widgets present in El-Maven, the screen gets freezed. There is no way to qiut El-Maven other than doing force quit.
![image](https://user-images.githubusercontent.com/31559038/37141586-7ff57550-22db-11e8-9a5f-676e5e1d6e7a.png)

**Comment by rish9511** [comment]
@sunil20dhakad 
For now the only way to fix this is to delete the Application settings stored in "/Users/YOUR_USER_NAME/Library/Preferences/com.mzroll.Application Settings.plist". 

This way it won't try to restore the old state and therefore you won't have that pop up.

Hope this helps

**Comment by sunil20dhakad** [comment]
@rish9511 thanks for your suggestion. Can we also try to separate the two widgets that are popping up (i.e. Restore window and Elmaven Starting window). If somehow or other I could move away these two widgets from each other then this problem would not arise.

**Comment by shefalilathwal** [comment]
Ran into this issue again. I was able to solve it using @rish9511's solution above.

**Comment by shubhra-agrawal** [comment]
@sunil20dhakad @shefalilathwal Do you still run into this issue from time to time?
@rish9511 FYI

**Comment by shubhra-agrawal** [comment]
@sunil20dhakad @shefalilathwal Closing this since we have not seen this happen since September, 2018. Feel free to reopen if you run into it again.
