### ISSUE TITLE
don't reset sample colors if user has already assigned some manually

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#634]
This is a mild annoyance that I run into occasionally. El-Maven tries to reassign the colors whenever new samples are loaded, which is usually a good thing. But if the user has already assigned colors to samples manually, those should be kept (I guess you could ask the user, but I prefer not to have too many popup dialogs).

**Comment by shubhra-agrawal** [comment]
@chubukov In v0.7.0 and above, sample colors are not re-assigned once the sample has been imported into El-MAVEN. Only the user can re-assign colors manually. Hope that works for you!
