### ISSUE TITLE
Peak Detailed Format (.csv) is changed 

### ISSUE THREAD

**Issue by sunil20dhakad** [ElucidataInc/ElMaven#635]
The data of column name 'compound' is changed from earlier versions.
Previous: 
Citrate 191/111 
Current:
Citrate 191/111 | SRM SIC Q1=275.1 Q3=154.096 
Because of which our downstream processing is affected. Please resolve if this is a bug if not then let me know I will change my downstream scripts.

**Comment by shubhra-agrawal** [comment]
@sunil20dhakad This has been merged to develop
