### ISSUE TITLE
allow .txt extension for tab-delimited files

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#64]
Maven always wants .tab for tab-delimited input files (like compound database) which is just mildly annoying since most people use Excel to edit the file, and Excel only saves as .txt . Let's just allow .txt extension and assume it's tab-delimited.

(maybe at some point in the future we can do what spotfire and excel do and guess the format/delimiter, but this is extremely low priority).

**Comment by sahil21** [comment]
@chubukov We have allowed input of .tab.txt rather than just .txt files.
