### ISSUE TITLE
small bug -- trailing delimiter in peaks report

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#640]
the trailing delimiter works fine in Excel but causes havoc when reading with pandas.

https://github.com/ElucidataInc/ElMaven/blob/9e89a72c9b1f845918b2b4c0b12eec67e76d0dab/src/core/libmaven/csvreports.cpp#L406

**Comment by shubhra-agrawal** [comment]
@chubukov Fixed and shipped with v0.3.1. Let us know if there are issues with it.
