### ISSUE TITLE
Getting blank EIC plot with DNA dataset in El-Maven

### ISSUE THREAD

**Issue by sunil20dhakad** [ElucidataInc/ElMaven#641]
I am working on a DNA dataset (.d format) which I converted to mzML format using MSconvert. When I uploaded the data on El-Maven it is showing blank EIC plot. I can share data if needed.

**Comment by sahil21** [comment]
@sunil20dhakad We'll look into this. Please share the data with us.

**Comment by sunil20dhakad** [comment]
@sahil21 The problem is solved. It was the issue of file format.

**Comment by sahil21** [comment]
@sunil20dhakad Great! :D
