### ISSUE TITLE
Crash in libneural if defualt.model is not found

### ISSUE THREAD

**Issue by rish9511** [ElucidataInc/ElMaven#642]
Steps to reproduce:
1. Upload samples
2. find peaks 
3. click on any group in the peaks table

Back trace report: https://pastebin.com/riyefrV2

**Comment by saifulbkhan** [comment]
Whatever the issue was, it probably got fixed in the referenced commits. Anyhow, "default.model" should always be found unless someone removes them from where they should be. Closing this.
