### ISSUE TITLE
Crash when trying to access PeakGroup using IsotopeWidget

### ISSUE THREAD

**Issue by rish9511** [ElucidataInc/ElMaven#650]
There are no defined steps to reproduce this crash but it happens generally when the following is
done:
1. find peaks with Isotopes
2. Go through groups in IstopoeWidget
3. Click on one of the Peaks in Eic Widget

back trace report: https://pastebin.com/LiEtYRyP

**Comment by shubhra-agrawal** [comment]
@rish9511 There were some fixes in isotope widget in the 0.7.1 release which stabilized it to a large extent. We have not observed this crash since then. Closing it
