### ISSUE TITLE
mismatch/typo in isotope logic

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#66]
I mentioned this peripherally in another issue, but I just tracked it down specifically, so I thought I'd post it

In `libmaven/constants.h` deuterium labeling is specified as "D-label"

`const string H2_LABEL = "D-label-";`

but in `libmaven/csvreports.cpp` it's looked for as "D2-label"

`(isotopeName.find("D2-label") != string::npos`

**Comment by GeorgeSabu** [comment]
@chubukov Thank you. I have updated develop with this change.
