### ISSUE TITLE
more obvious error when files aren't loaded

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#676]
If there's an error reading in a data file, the only error is currently a console message (which can quickly get drowned in other debug messages). This is a major error, so a dialog or something like that would be appropriate.

**Comment by rish9511** [comment]
@chubukov 
Thanks for the suggestion. 
Just one question: You would not want a separate error message for every file that fails to load , right?
I am thinking it more in the terms of: A dialog box that informs the user about the files that failed to load

**Comment by chubukov** [comment]
@rish9511 that sounds fine, sure.

**Comment by saifulbkhan** [comment]
With v0.10.0, a message box will appear notifying the user about which samples were not loaded.
