### ISSUE TITLE
Sort Isotopes in IsotopesPlots widget in natural sort order

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#679]
Currently, the isotopes are sorted in asciibetical order (or similar), but not natural sort order.

![image](https://user-images.githubusercontent.com/645128/38940759-f587d85c-42f8-11e8-9b37-7e5c44b5be2f.png)

**Comment by lparsons** [comment]
This can be addressed in the reorganization of these plots #529.

**Comment by saifulbkhan** [comment]
This kind of labeling is no longer present in isotope plots. Hovering will instead provide sample names and distributions. Maybe not the best UX, but this issue itself is stale.
