### ISSUE TITLE
export to csv fails silently if file can't be opened

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#68]
During CSV export, if writing the file fails (most common scenario is that user doesn't have permissions, or file is already open), there is no error displayed, so the user doesn't realize that it failed. Let's have some sort of pop-up error here?

**Comment by GeorgeSabu** [comment]
@sahil21 add code to check when the compoundDB loads.

**Comment by GeorgeSabu** [comment]
@sahil21 I guess we misunderstood the issue. Make sure we capture this asap.

**Comment by GeorgeSabu** [comment]
@chubukov This feature is now implemented and merged with the develop.

**Comment by chubukov** [comment]
I tested this without meaning to. Good feature :P Seems to work fine.
