### ISSUE TITLE
feature: Installing new version of ElMaven without creating new folder

### ISSUE THREAD

**Issue by raaisakuk** [ElucidataInc/ElMaven#681]
Currently, when I try to install a new version it doesn't automatically detects the old one. _ have to delete the existing folder and install a new one or create a different folder. It would be great if it upgrades the existing one.

**Comment by saifulbkhan** [comment]
El-MAVEN can upgrade existing installations now, if the update is performed using the update prompt available since v0.10.0. Marking this as done.
