### ISSUE TITLE
Is xcode required to use/install ElMaven in MAC?

### ISSUE THREAD

**Issue by shefalilathwal** [ElucidataInc/ElMaven#683]
Apple keeps asking me to update xcode and it's taking up more than 5 GB space and I am running out of space on my mac. Can I just remove it without affecting EL-MAVEN?

**Comment by shubhra-agrawal** [comment]
@saifulbkhan FYI

**Comment by saifulbkhan** [comment]
@shefalilathwal you do not need Xcode, the development application itself, to be able to install or run El-MAVEN. You can uninstall it, assuming that you need its binaries and libraries for other work. If I remember correctly, its this application that takes a huge amount of disk space.

But the xcode command-line utilities (a separate software package) are often needed by other common tools (such as homebrew), so you can chose to keep it.
