### ISSUE TITLE
can alignment be used from command line (peakdetector)?

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#691]
If so, could someone provide an example?

If not, I would put this as a low/medium priority feature.

**Comment by shubhra-agrawal** [comment]
@chubukov Currently, you can only use PolyFit alignment through command line. The other 2 algorithms still need to be enabled.

**Comment by rish9511** [comment]
@chubukov 
This feature is now available in the `develop` branch . 
The alignment option can either be specified in the command line or can be configured in the default `config.xml` file

Usage:
1. From command line: `peakdetector -a 1 path_to_sample_file`

2. From config file
```
....
<GeneralArguments>
    <alignSamples type="int" value=2 />
     ...
</GeneralArguments>
...
```

* 1 is for OBI-WARP   
* 2 is for Poly-Fit

Hope this helps!
Closing the issue for now. Please re-open it if you still face issues
