### ISSUE TITLE
Method to properly separate multiple peak groups for a single compound in labeled data export

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#693]
The automated peak picking has been useful for us, and we are hoping to use it more in our workflows going forward. However, we have run into an issue with some of our downstream processing. There are times that the automated peak detection will detect two or more peak groups for a single compound. When the peak data is exported to a CSV file, it can be difficult to properly group the rows for the isotopes according to the compound *and* the peak group.

For example, the table below, there were two peaks detected for the `C17:0` compound. This is evident from the fact that there are two rows with `C12 PARENT` as the **isotopeLabel**, both with the same value (`C17:0`) for the *compound*. Currently, the only way I can see to properly group the isotopes together is to use the sort order (which is rather fragile). It would be great if there was a column that could be used to group together the isotopes for a given parent peak group. I had thought that **groupId** or **metaGroupId** would do this, but it appears not.

| label | metaGroupId | groupId | goodPeakCount | medMz | medRt | maxQuality | isotopeLabel | compound | compoundId | formula | expectedRtDiff | ppmDiff | parent | F-2-3 | F-2-2 | F-2-1 | F-1-3 | F-1-2 | F-1-1 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| | 0 | 19 | 3 | 269.2483 | 10.66541 | 0.3812263 | C12 PARENT | C17:0 | C17:0 | C17H34O2 | 0.0554142 | 1.246778 | 269.2483 | 968530.8 | 877007.3 | 798940.5 | 916631.2 | 835455.4 | 890473.7 |
| | 0 | 20 | 0 | 270.2516 | 10.66841 | 0.1329716 | C13-label-1 | C17:0 | C17:0 | C17H34O2 | 0.05840874 | 1.355072 | 269.2483 | 145705.1 | 179558.1 | 157521.6 | 187857.9 | 165838.1 | 188400.8 |
| | 0 | 21 | 0 | 271.2553 | 10.66063 | 0.1363112 | C13-label-2 | C17:0 | C17:0 | C17H34O2 | 0.0506258 | 0.112505 | 269.2483 | 0 | 21641.75 | 37308.98 | 0 | 38462.94 | 31614.97 |
| | 0 | 22 | 0 | 279.2812 | 10.67332 | 0.06595834 | C13-label-10 | C17:0 | C17:0 | C17H34O2 | 0.06331635 | 3.496688 | 269.2483 | 0 | 0 | 0 | 0 | 12059.9 | 0 |
| | 0 | 23 | 0 | 286.306 | 10.6621 | 0.05498731 | C13-label-17 | C17:0 | C17:0 | C17H34O2 | 0.05210018 | 1.065909 | 269.2483 | 0 | 0 | 0 | 0 | 5312.716 | 0 |
| | 0 | 24 | 6 | 269.2483 | 10.83009 | 0.6458657 | C12 PARENT | C17:0 | C17:0 | C17H34O2 | 0.2200947 | 1.360122 | 269.2483 | 1403727 | 1372650 | 1224187 | 1717277 | 1351518 | 1380006 |
| | 0 | 25 | 1 | 270.2517 | 10.83084 | 0.6351051 | C13-label-1 | C17:0 | C17:0 | C17H34O2 | 0.2208424 | 1.129227 | 269.2483 | 263422.5 | 259599.9 | 232503.4 | 347670.3 | 255774.8 | 272030.3 |
| | 0 | 26 | 5 | 271.255 | 10.8256 | 0.7582457 | C13-label-2 | C17:0 | C17:0 | C17H34O2 | 0.2156038 | 1.35006 | 269.2483 | 203092.2 | 210994 | 174553 | 248180 | 161895.4 | 176984.5 |
| | 0 | 27 | 3 | 272.2583 | 10.83608 | 0.4382453 | C13-label-3 | C17:0 | C17:0 | C17H34O2 | 0.2260838 | 1.345085 | 269.2483 | 34552.54 | 30051.12 | 26722.41 | 34615.7 | 23768.76 | 30780.57 |
| | 0 | 28 | 0 | 273.2615 | 10.83905 | 0.1190069 | C13-label-4 | C17:0 | C17:0 | C17H34O2 | 0.2290506 | 1.89854 | 269.2483 | 0 | 2020.727 | 0 | 0 | 1669.672 | 1590.536 |
| | 0 | 29 | 0 | 277.2751 | 10.82664 | 0.1117229 | C13-label-8 | C17:0 | C17:0 | C17H34O2 | 0.2166443 | 1.43081 | 269.2483 | 1469.456 | 0 | 0 | 2226.511 | 0 | 1762.055 |
| | 0 | 30 | 0 | 278.2788 | 10.81927 | 0.1332641 | C13-label-9 | C17:0 | C17:0 | C17H34O2 | 0.2092667 | 0 | 269.2483 | 0 | 0 | 1287.022 | 0 | 0 | 0 |
| | 0 | 31 | 3 | 279.2817 | 10.83571 | 0.8260291 | C13-label-10 | C17:0 | C17:0 | C17H34O2 | 0.2257118 | 1.639072 | 269.2483 | 12272.01 | 7363.174 | 5927.667 | 13739.84 | 8880.015 | 15637.43 |
| | 0 | 32 | 3 | 280.285 | 10.83047 | 0.7457497 | C13-label-11 | C17:0 | C17:0 | C17H34O2 | 0.2204704 | 1.959846 | 269.2483 | 2232.711 | 5447.577 | 4192.296 | 5532.605 | 4001.46 | 6392.808 |
| | 0 | 33 | 1 | 281.2881 | 10.83538 | 0.2016962 | C13-label-12 | C17:0 | C17:0 | C17H34O2 | 0.2253838 | 2.712299 | 269.2483 | 0 | 0 | 0 | 0 | 12148 | 13360.56 |
| | 0 | 34 | 2 | 282.2921 | 10.83313 | 0.4628394 | C13-label-13 | C17:0 | C17:0 | C17H34O2 | 0.2231274 | 0.648638 | 269.2483 | 12058.58 | 0 | 11198.2 | 11894.38 | 9857.778 | 9219.092 |
| | 0 | 35 | 1 | 283.2952 | 10.8286 | 0.4778512 | C13-label-14 | C17:0 | C17:0 | C17H34O2 | 0.2185974 | 1.400405 | 269.2483 | 25540.08 | 26444.85 | 27922.27 | 38972.93 | 30830.57 | 34163.1 |
| | 0 | 36 | 3 | 284.2985 | 10.82934 | 0.6704565 | C13-label-15 | C17:0 | C17:0 | C17H34O2 | 0.2193451 | 1.502806 | 269.2483 | 8233.266 | 7491.957 | 7979.439 | 12861.41 | 11545.51 | 16363.9 |
| | 0 | 37 | 1 | 285.3016 | 10.82536 | 0.7903571 | C13-label-16 | C17:0 | C17:0 | C17H34O2 | 0.2153625 | 2.353247 | 269.2483 | 2174.356 | 0 | 0 | 2526.581 | 4828.144 | 3478.406 |
| | 0 | 38 | 2 | 286.3053 | 10.8286 | 0.7081909 | C13-label-17 | C17:0 | C17:0 | C17H34O2 | 0.2185993 | 1.279091 | 269.2483 | 5120.111 | 4705.006 | 5337.868 | 12369.96 | 9268.435 | 6237.612 |

**Comment by shubhra-agrawal** [comment]
@lparsons @chubukov This has been resolved and merged into v0.4-beta. groupId is different for every group, regardless of child or parent. MetagroupId will be same for a parent and its children.
