### ISSUE TITLE
Sample Number coming twice in exported Peak Detailed Csv format

### ISSUE THREAD

**Issue by raaisakuk** [ElucidataInc/ElMaven#696]
This is from El Maven 0.3.1.1 export
![image](https://user-images.githubusercontent.com/33527542/39544808-3e5ab3c2-4e1d-11e8-886b-db9a85b99c20.png)

**Comment by shubhra-agrawal** [comment]
@raaisakuk one question, is this export done after loading an mzroll?

**Comment by raaisakuk** [comment]
No, this one I did before that.

**Comment by shubhra-agrawal** [comment]
Okay, we'll look into this. Thanks!

**Comment by shubhra-agrawal** [comment]
Fixed and merged to develop @raaisakuk @Raghavdata. Will be available as part of 0.9 in a week or two.
