### ISSUE TITLE
bug: El MAVEN crashed when tried to export bookmarked peaks

### ISSUE THREAD

**Issue by raaisakuk** [ElucidataInc/ElMaven#698]
1. Using El MAVEN v0.3.1 (beta) on Windows
2. Disable multiprocessing
3. Uploaded .cdf files
4. Bookmarked two groups
5. Tried saving using Peak Detailed format, El MAVEN crashed. Again tried it using some other format, crashed.

**Comment by sahil21** [comment]
@raaisakuk This has been resolved and merged to the develop.
