### ISSUE TITLE
Crashing on opening on Windows 2008 server

### ISSUE THREAD

**Issue by GeorgeSabu** [ElucidataInc/ElMaven#7]
Victor was able to install El Maven 0.2 on my laptop, and it’s mostly working. But when he installed it on the server (Windows Server 2008), it crashed immediately upon opening. Here are the two screenshots that he got during the crash.
![image001](https://cloud.githubusercontent.com/assets/22674403/19506197/197855ae-95e7-11e6-94ce-1c4890d48987.png)
![image002](https://cloud.githubusercontent.com/assets/22674403/19506199/1e5ccd70-95e7-11e6-956d-8c57058129b4.png)

**Comment by GeorgeSabu** [comment]
@chubukov We checked/ tested the tool on windows 2008 server it worked fine. 

Will it be possible to get access to the windows 2008 server that you are using for us to debug? 
In the meanwhile, will it be fine with you to use windows 2008 server that we have hosted on AWS to continue with the user testing?

**Comment by chubukov** [comment]
@GeorgeSabu So the only thing I could think of was the internal settings. I deleted all the registry settings, and tried running it again. It crashed the same way (also after reinstall). 

Has anything changed regarding the QT libraries? Could some old versions be the cause? I don't really see how, just throwing it out there.

I don't think I can get you access to the server unfortunately, nor would it be useful to test on another AWS server (copying all the data over constantly would be a non-starter I think). 

What would you want to do if you had access to the server? If you give me a couple of ideas, I can probably test them.

**Comment by GeorgeSabu** [comment]
@chubukov When I was debugging the #2 I got the same error that you explained. Can you check if its the problem with loading of the compound database? Compound databases are automatically loaded at the start of the code.
Can you please check the installation directory under the path C:\Program Files (x86)\ElMaven-0.2\ and see if there are any compound data files that you had edited/added?

**Comment by GeorgeSabu** [comment]
@chubukov will it be possible to get the screenshot of the terminal which is open after El-Maven starts? Attached is an example.

![crashpng](https://cloud.githubusercontent.com/assets/22674403/19554463/5983faa0-96d6-11e6-8bed-f15c5bba3a09.png)

**Comment by chubukov** [comment]
I would have included it but it never gets to that state. Here's the snapshot.

![image](https://cloud.githubusercontent.com/assets/13080968/19565447/dea66f5a-96b4-11e6-86b9-b018b29ead0e.png)

I also don't think it's the database file -- the one it's trying to load looks fine to me, and I get the same crash if I delete all the registry settings.

**Comment by GeorgeSabu** [comment]
@chubukov Did you try running as administrator to see if its not permission problem in accessing files during loading?

**Comment by chubukov** [comment]
Yes. Same behavior.

**Comment by GeorgeSabu** [comment]
@chubukov It's better we install QT and debug. You can pull develop branch and step through the code using QT creator. Installation procedure is [there](https://elucidatainc.github.io/ElMaven/main/2016/02/12/windows-installation.html). You can get QT creator from [here](https://download.qt.io/official_releases/qtcreator/3.1/3.1.0/).

**Comment by chubukov** [comment]
@GeorgeSabu I was able to compile and run the code from source.

I tried running the version you compiled with all the same libraries (I deleted all the dlls in the installation folder so that it use the ones installed with QT) and it still crashed.

**Comment by GeorgeSabu** [comment]
@chubukov When pillowcore.dll is not present it will give an error telling the same. And the El-MAVEN installer is made from the El-MAVEN compiled binary and .dll files made in the form of a package. So in the installation path of El-MAVEN pillowcore.dll should be there. And this shouldn't be the problem as installer works fine in other windows and also we have tested it on windows server 2008.

> I tried running the version you compiled with all the same libraries (I deleted all the dlls in the installation folder so that it use the ones installed with QT) and it still crashed.

Did you put back the .ddls that are generated from compiling the source code to the El-MAVEN installation folder?

**Comment by chubukov** [comment]
@GeorgeSabu I didn't move them there, except for pillowcore.dll, but with them missing, I was assuming it should use the ones in the mingw installation, just like the compiled version does.

**Comment by GeorgeSabu** [comment]
@chubukov All the .ddl that was removed has to be replaced in the El-MAVEN installation folder.

**Comment by GeorgeSabu** [comment]
@chubukov To make it clear you are able to compile and run El-MAVEN in windows server 2008, but not able to run through installer we provided?

**Comment by chubukov** [comment]
@GeorgeSabu (this comment may show up twice, I replied by email but it's still not showing up). Yes, exactly I was able to compile and run from source on that machine. In response to your other point, there wasn't an error because it's using the dlls installed with mingw. I have only compiled in debug mode though, so I'm going to try release mode in case it makes a difference.

**Comment by GeorgeSabu** [comment]
@chubukov can you take the binary that is generated by compiling and put that into the El-MAVEN folder in C drive and make a shortcut for that binary in desktop and check if its working fine?

**Comment by chubukov** [comment]
@GeorgeSabu That's exactly what I did. It works fine.

**Comment by chubukov** [comment]
Yes, exactly. I can put the version from the installer and the version I
compiled in the same directory, and the one compiled locally runs fine
while the installed one crashes.

Hm, I only compiled in debug mode. Let me try compiling in Release mode
with -O3, maybe it makes a difference.

**Comment by GeorgeSabu** [comment]
@chubukov There is a script called "uninstall.sh" and "run.sh", use that to uninstall and run the compilation. While executing "run.sh" you will get an option to build it in release mode or debug mode.

**Comment by chubukov** [comment]
@GeorgeSabu  For what it's worth, I compiled with QT creator, not the command line scripts. I can try it with the scripts next.

**Comment by GeorgeSabu** [comment]
@chubukov Are you using the compiled version of El-MAVEN for user testing?

**Comment by chubukov** [comment]
@GeorgeSabu I have been using it myself a little bit. Given the number of crashes on pretty routine tasks, and the difficulties with the isotope picking, I don't quite feel comfortable yet asking the group to use it. Maybe one more round of bug fixes and I can open it up to the broader audience?

Let's take this discussion elsewhere if we need to continue it and not hijack the thread completely.

**Comment by chubukov** [comment]
Just downloaded latest source and compiled with the command-line script (run.sh). Maven compiled and ran fine. (MavenTests crashed with a segfault -- I'll open another issue for that if that's news).

I'm sort of out of ideas -- this worries me a little bit, but overall it's not a huge problem for us to simply compile from source on this machine every time we upgrade.

**Comment by GeorgeSabu** [comment]
@chubukov We will send you the debug version of the build. This will be equivalent to building it **not** in release version with `run.sh`.

One thing that we can try is that in the `mainwindow.cpp` inside the constructor add, some debug prints statements. For example, before settings are loaded, after loading settings, after `default.model` is loaded etc. And compile with `run.sh` script asking to **not** build in  release mode. And adding it to the installation directory of El-MAVEN and see where the error is happening.
