### ISSUE TITLE
When selecting a peak group from a peak list, the isotope plot is not drawn

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#703]
The user is required to click on the peak group directly before the isotope plot is draw. This severely slows down the workflow for users who rely on the isotope plot as a quick way to evaluate peak quality.

![el-maven_isotope_plot_drawing_bug](https://user-images.githubusercontent.com/645128/39841914-751ef3b0-53b2-11e8-835f-8c8a65b2a505.gif)

**Comment by sp-eldata** [comment]
I love how you made a giff out of this :)

**Comment by chubukov** [comment]
What would be kind of nice is if clicking on a peak highlighted the bar for that sample in some way.

**Comment by saifulbkhan** [comment]
This has been fixed with v0.10.0.
