### ISSUE TITLE
ionization mode reset

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#708]
This happens to me on version 3.0

-ionization mode starts at autodetect(0)
-load a bunch of negative mode LCMS files 
-ionization mode gets correctly set to autodetect(-1)
-delete all the files
-load the same files again 
-ionization mode gets set to autodetect(0)

**Comment by shubhra-agrawal** [comment]
@chubukov Tested on v0.7.1. Works fine, closing it.
