### ISSUE TITLE
Random Appearance of quality indicators without peaks 

### ISSUE THREAD

**Issue by shaaaarpy** [ElucidataInc/ElMaven#710]
After setting the limit intensity range to 5000, i found random appearance of quality indicators as shown in the attached figure. I think this is an issue with the post processing and i didn't use alignment. 

![elmaven_bug](https://user-images.githubusercontent.com/23281566/40346708-4b5c97ea-5dbb-11e8-898b-70787eb1389a.png)

**Comment by chubukov** [comment]
@shubhra-agrawal @shefalilathwal @sharpy013 Usually this kind of thing means the ppm window was changed after the peak was integrated. But I have also noticed this behavior after untargeted peak picking, which is what you seem to have. I'm guessing it's a bug in how the mass slice is calculated/stored.
