### ISSUE TITLE
analytics

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#717]
I would like to understand a little better some of the changes going on with analytics, error reporting, etc.

a) What data exactly is being sent? What data is not being sent? 
b) If the logging/reporting is continuous, then have we done any performance benchmarks with and without it?

Slightly related to #674

**Comment by sahil21** [comment]
@chubukov 
Regarding Analytics:
1. Data being sent
- OS versions
- Screens used (Dialog like Mainwindow, Options Dialog)
- Number of samples loaded
- Number of Active users

**No PII (personally identifiable information) or data is being sent to analytics.**

2. Related to performance - There won't be any performance issue as we are doing HTTP Post request which asynchronous. 

**Example of HTTP POST request we are sending:**

`http://www.google-analytics.com/collect/v=1&tid=UA-118159593-1&cid=%7Ba4bf73b1-2d20-45ba-bbf6-4696d975fb12%7D&ul=en-in&an=El-Maven&av=v0.3.2-16-gdd9f3a1e&t=screenview&cd=MainWindow
`


@rish9511 Can you update around error logging using Sentry?

**Comment by rish9511** [comment]
@chubukov 
With respect to error logging, the two things we send to sentry are:
- Logs: ex: "Sample could not be uploaded". That's all for now.  The name of the sample is not included
- Stack Trace: Whenever El-Maven crashes, a minidump file is created on user's system

Note: Both the things get uploaded to sentry only if user chooses to send the report not otherwise

**Comment by chubukov** [comment]
@rish9511 @sahil21 great thank you both

**Comment by shubhra-agrawal** [comment]
Update: To prepare for the El-MAVEN redesign effort, additional GA triggers have been added in v0.6.1. These have been listed below. Only some UI interactions and data type are being collected. No user data or PII is collected.

- MS level (1, 2 or both)
- if user is loading a custom compound db
- If there were errors in custom compound db, handled by El-MAVEN or not
- how is data being exported from El-MAVEN (format, which buttons)
- if it's the first session on a new machine
- which import and instrumentation settings are adjusted
- which polly app is used, how many times data is pushed to Polly
- which alignment algorithm is used
- Bookmark or automated peak detection, targeted/untargeted, labeled/unlabeled
- format for project save/load (mzroll/emDB)
- manual integration button on EIC widget
- merge button in bookmark table

**Comment by saifulbkhan** [comment]
Closing this discussion. All queries have been answered.
