### ISSUE TITLE
crash if integrating peak from formula

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#722]
If I put a formula into the search box and then integrate the resulting peak, I get a crash.

I did send the crash reports yesterday. Were they useful in identifying this?

**Comment by chubukov** [comment]
@rish9511 ok, I do customize our builds a little bit, so let's see what we can figure out in the future.

And let's resolve the underlying bug obviously -- it seems quite easily reproducible.

**Comment by rish9511** [comment]
@chubukov 
sure

**Comment by sahil21** [comment]
@chubukov I'm not able to reproduce this crash on current develop. Can you send us the commit id?

**Comment by chubukov** [comment]
@sahil21 sorry I missed this. Did you have isotopes enabled? I think it's only in that case.

**Comment by chubukov** [comment]
@sahil21 this appears to be fixed in the current version

**Comment by sahil21** [comment]
@chubukov This might be the result of this commit https://github.com/ElucidataInc/ElMaven/commit/be89272fbe94e7becd7733778f6fdc7e1b7c90ff

Closing the issue.
