### ISSUE TITLE
slowdown with large peak table

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#723]
I did an untargeted peak picking with a very low threshold, so I ended up with 50k peaks in a table.

I found that as a result of this, interaction with the sample widget (checking/unchecking samples) slowed the app to a crawl (on the order of a minute to check/uncheck a sample). This was with only about 30 samples loaded.

Is there some recalculation or update being done on the entire peak table? Is it obvious this needs to happen?

Not a huge deal, but I found it odd.

**Comment by saifulbkhan** [comment]
This has been investigated, and culprit found (alignment widget, see #809 for discussion). While the existence of current alignment widgets and their behaviour will be discussed eventually, they should no longer slow down the application when samples are selected with a large peak table present (at least not when they are hidden).
