### ISSUE TITLE
debug statements slow down mzML import

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#724]
When I got rid of the debug output in the mzML parser, import speed increased by an order of magnitude. 

Bunch of other debug output could be cleaned up as well.

V

**Comment by shubhra-agrawal** [comment]
@chubukov The sample import speed took a hit in v0.3 but it's back to normal now. We've also done a few optimisations to make it a little faster for bigger datasets.

Irrespective of that, cleaning up debug statements should help. We have removed a few of these. Will clean it up more soon.

**Comment by shubhra-agrawal** [comment]
Merged to develop. Will be available as part of v0.8
