### ISSUE TITLE
order of samples in eic widget

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#73]
I think this must have something to do with the last upgrade, maybe in the group selection.

Maven normally draws the peaks such that the sample with the lowest intensity is drawn on top (that way you can kind of see all the peaks). It looks like in the new version, in the first plot that's shown for the compound, that doesn't happen. However, if I manipulate the plot in some way (e.g. zoom in) the samples are rearranged in the expected order.

I'm guessing it has something to do with which group is selected and which intensities are used to calculate the order? I suspect there is some ambiguity involved, but it does seem like previous versions did a better job of this.

**Comment by GeorgeSabu** [comment]
@chubukov I compared the EIC plots from the master and develop branch. The order they both have are the same. But when I compared develop branch to maven776 order was different. The order maven776 have is better. So it's something we missed during the initial refactoring we did.

**Comment by GeorgeSabu** [comment]
@chubukov At some places EIC plot that is there in the current develop is better, in some others EIC plot from maven 776 is better.

**Comment by GeorgeSabu** [comment]
@chubukov after zooming, getting rearranged in the way that curves with low intensities are on top is there in all version of maven. After the user zooms in the arrangement of the peaks is different than before in all versions of maven.

**Comment by GeorgeSabu** [comment]
@chubukov This issue is fixed on the latest develop.
