### ISSUE TITLE
g key

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#74]
In the latest update, it looks like the functionality of pressing "g" to mark a peak as good and add it to the bookmarks table is gone (it scrolls to the next compound, but doesn't add the peak to the bookmarks table).

**Comment by GeorgeSabu** [comment]
@chubukov I am able to press 'g' and mark peaks as good. For the first compound, the user has to click on the peak and press 'g' to mark it as good. But after that use the arrow key to move down and press 'g' to mark it as good. After the first click, the user doesn't have to click on peak again and mark it as good. This is the exact behavior in all versions of MAVEN.  I have checked this in both windows and ubuntu.

**Comment by GeorgeSabu** [comment]
@chubukov I found another problem related to this. That when you are marking by using g and b then isotopic children are not captured. The same problem as with the integration and double clicking that we had resolved before. This we will resolve and update soon.

**Comment by chubukov** [comment]
@GeorgeSabu I'm sorry, you're right, that part of the behavior is the same. 

I think what threw me off is that if you click on a new compound in the ligand widget, it now makes the circles in the eic widget solid-colored (whereas in previous el-maven they were empty). And somehow the association was "solid circles means that you can hit g to bookmark" (since that was also the change when scrolling through ligand widget). But you're right, in Maven 776 it was also true that the cirlces were solid but hitting g just took you to the letter g in the compounds list.

Happy to take suggestions to make this more consistent. I'll close this issue for now.
