### ISSUE TITLE
new isotopic barplot

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#75]
I don't know how much we want to go into detail about the new isotopic barplot -- I know that you're working on a lot of aspects of it.

For now it hasn't caused any crashes for me, so that's fantastic. That's a big deal, and it sounds like it was a good decision to overhaul it.

Here are some things that I think could be improved.

Functional

- [ ] doesn't update when new compound is selected in ligand widget
- [x] I can't figure out how to enable and disable the widget. It doesn't respond to the old isotope plot button.

Aesthetic
- [ ] legend/colors should update when options are changed (regarding which isotopes to display)
- [x] legend just takes up too much space

It wasn't clear to me if you're planning to work on this immediately, or wait until the update to QT 5.x to enable hoverover text, etc. What would the timeline be for that?

**Comment by chubukov** [comment]
Something we discussed at some point: it would be nice to have a threshold option for the isotopic barplot (e.g. don't show any species that are not >1% in at least 1 sample). That would help a lot to limit the number of legend entries, which will help with layout.

**Comment by chubukov** [comment]
Another aesthetics suggestion: use a qualitative color palette, so that you don't have this problem of adjacent colors being similar. You'll have to cycle through the colors at some point, but honestly, with >8-10 colors or so, it gets hard to tell the adjacent ones apart anyway.

**Comment by GeorgeSabu** [comment]
@chubukov doesn't update when a new compound is selected in ligand widget I haven't updated as this is causing crash because of the multithreading issue when we move compound by compound fast in ligand widget This could be updated in the UI-arch sprint.
enable and disable the isotopic widget: It's working as before. can enable and disable with the same isotopic button. 

No legends are used anymore. Hovering on a sample shows all the isotopic species percentage.

Threshold option for the isotopic barplot this would be added in the next sprint.

**Comment by chubukov** [comment]
@GeorgeSabu great, agree with your decision to disable the update for now. Hover seems to be working pretty well, though we should leave this open as a reminder to improve the aesthetics -- it can be pretty hard to read in some cases.

**Comment by chubukov** [comment]
There are a couple of small annoying behaviors related to the hover legend.

- hovering over the left half of a bar gets the legend for the bar to the left instead of the current one
- the sample name sometimes doesn't get shown. 
- the samples are in reverse order (first one is on the right)

**Comment by GeorgeSabu** [comment]
@chubukov These problems are now fixed on the commit https://github.com/ElucidataInc/ElMaven/commit/434338dfc95d995afd140e666cbbf28d71dce9d3.

**Comment by chubukov** [comment]
I think development of the aesthetics of this plot is going on with low burn still?

Here's an example where the legend is almost unreadable. I think having a solid color background for the text would be good. The problem now is that it would completely obscure any bars in the top left corner. I think the best would be to have it move with the mouse cursor and optionally, have it recognize the vertical position and show only that isotope. I can see that being challenging to implement -- happy to consider alternatives!

![image](https://cloud.githubusercontent.com/assets/13080968/22314873/727b1294-e331-11e6-84de-870f1c916e2e.png)

**Comment by chubukov** [comment]
Regarding the abundance threshold: What it's doing right now is limiting which entries are shown in the hover text. That's pretty useful, but where I was thinking it would be most useful would be in limiting the bars that are shown, so that you wouldn't need so many colors. 

If the abundance threshold is non-zero, one possibility is that the bars just don't stack up to 100%, which seems ok. I guess the really nice way to do it would be to have one bar for "other", containing all the isotopes that didn't get to the threshold, and (if we implement the hover taking into account the vertical position, as per my last comment) when you mouseover this, it would give you all the isotopes that didn't meet the threshold (e.g. "D2-1: 0.01%, N15-3: 0.02%", etc).

This is all a little complicated and none if it absolutely critical -- just sharing my thoughts on what I think a nice UI would be.

**Comment by chubukov** [comment]
@sahil21 fixing up the aesthetics of the barplot could be a nice small project for next sprint? Certainly not high priority, but I do run into the unreadable legend fairly often, and it's pretty annoying.

I know I promised to minimize non-critical QT-related issues, so that's why I say low priority.

The other suggestions in the previous comment could also be reasonable small projects.

**Comment by IpankajI** [comment]
@chubukov 
Now while taking cursor over a column other columns will disappear. Taking the cursor out of isotope plot window will restore colours. This is making it easier to read the text. I have pushed the changes to branch : [ftr_isotopeplote_color](https://github.com/ElucidataInc/ElMaven/tree/ftr_isotopeplote_color)
commit [164c9c2](https://github.com/ElucidataInc/ElMaven/commit/164c9c2)
![screenshot from 2017-08-19 18-59-33](https://user-images.githubusercontent.com/19559785/29487132-2121a4e4-84e4-11e7-9f21-667ba01b38c7.png)

We are also looking at your other comments in this thread and will be addressing those issues in the coming sprints.

**Comment by shubhra-agrawal** [comment]
@chubukov Most of the specified changes have been resolved as part of #529 . The changelog and remaining issues are mentioned in the [comments](https://github.com/ElucidataInc/ElMaven/issues/529#issuecomment-403717357)
