### ISSUE TITLE
Crash in isotopeWidget

### ISSUE THREAD

**Issue by rish9511** [ElucidataInc/ElMaven#757]
steps to reproduce:
1. find peaks(with isotopes)
2. open isotopewidget if it's not open already 
3. change the samples from isotopewidget
4. iterate over the labels in isotopewidget
5. select peaks in eic widget
6. iterate over groups in peaks table
7. repeat steps 3-6 until it crashes

Backtrace report:
https://sentry.io/test-acc/el-maven-logging/issues/592251723/?query=is:unresolved
https://sentry.io/test-acc/el-maven-logging/issues/591248815/?query=is:unresolved

**Comment by shubhra-agrawal** [comment]
Isotope widget has been tested after fixing 1-2 crash points. No crashes reported since then. Closing it. Will reopen if it comes back
