### ISSUE TITLE
Add a link to ElMaven from the Elucidata home page

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#766]
When going to the Elucidata home page, I find it difficult to find the link to ElMaven. For example, there are no links on http://www.elucidata.io/products. Adding links at least to the products page would be very helpful

ElMaven - https://elucidatainc.github.io/ElMaven/
Polly - http://www.elucidata.io/polly

**Comment by sonu-jun3** [comment]
Thanks for the feedback @lparsons
We will take this with few other updates planned for the website. Let us know if you have more of such kind.

**Comment by sonu-jun3** [comment]
@lparsons This issue has been resolved.
