### ISSUE TITLE
bookmark table does not include isotope information

### ISSUE THREAD

**Issue by shefalilathwal** [ElucidataInc/ElMaven#767]
I have an LC-MS labeled dataset that I am processing in version 0.2.4. On double clicking some metabolite groups from EIC window, only a single group appears in the bookmark table and isotopes do not show up. See G6P-F6P in the attached screenshot. The isotope plot clearly shows that there are isotopes present, yet in the bookmark table, G6P-F6P can be seen both including isotopes and without it.

We also see floating peak markers in the EIC window, even though ppm between EIC visualization and peak picking are the same.
![screen shot 2018-07-03 at 7 01 28 pm](https://user-images.githubusercontent.com/27472328/42222974-310573ea-7ec6-11e8-9bc3-b3908a1e8b7b.png)

**Comment by shubhra-agrawal** [comment]
@shefalilathwal This looks similar to a bug we recently noticed. Can you answer a few questions for me?
- Was Report Isotopic Peaks 'on' during bookmarking?
- Was bookmarking done from Peak Table EIC or Compound DB EIC?

**Comment by saifulbkhan** [comment]
I have not seen this happen for a long time now. Probably fixed with #1160.
