### ISSUE TITLE
Compound ID missing in the exported .CSV file

### ISSUE THREAD

**Issue by raaisakuk** [ElucidataInc/ElMaven#769]
@sahil21 Faced this again. It happened with the previous dataset too and I think the issue is deleting bookmarked groups. Is it possible to make this a priority? 

**Describe the bug**
When I export the bookmarked peaks in Peak Detailed csv format, some of the compounds from compound and compoundid column are missing.

**To Reproduce**
1. Go to Yale-Elucidata>Bugtest3july18 folder
2. Upload the .mzroll file
3. Export all groups in the Bookmark table as Peak detailed format.
4. Exported .csv has compound ids missing.

**System (please complete the following information):**
 - OS: Windows 8.1
 - Version v.0.2.4.4

**Additional context**
I deleted a Bookmarked group and compound ids before that are lost I think from the csv. I have seen this behavior previously with another dataset. Then also I had deleted a bookmarked group. Details can be found on Trello. https://trello.com/c/lPG3UDcU/104-compound-id-missing-in-the-exported-csv-file

**Comment by omkarap55** [comment]
@raaisakuk can u please provide compound database?

**Comment by raaisakuk** [comment]
@omkarap55 All details and required files should be on the trello link. https://trello.com/c/lPG3UDcU/104-compound-id-missing-in-the-exported-csv-file

Please let me know if you can't find it there.

**Comment by saifulbkhan** [comment]
This issue is not occurring anymore in the v0.4.1 build.
