### ISSUE TITLE
sorting pivoted peak table by column sorts alphabetically, not numerically

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#773]
-make peak table
-click leftmost button to pivot by sample
-sort by any sample column

resulting sort is alphabetical, not numeric

**Comment by shubhra-agrawal** [comment]
@chubukov Thanks for pointing it out. Just noticed MaxAreaTop sorting is also wrong in group view.

**Comment by danolson1** [comment]
I just came across this issue myself.

**Comment by shubhra-agrawal** [comment]
@chubukov @danolson1 Adding it as a discussion point in [project planning](https://github.com/ElucidataInc/ElMaven/projects/31#card-20540716) for the next few weeks.

**Comment by saifulbkhan** [comment]
No longer an issue. Closing.
