### ISSUE TITLE
Getting Started dialog placement

### ISSUE THREAD

**Issue by shubhra-agrawal** [ElucidataInc/ElMaven#775]
**Describe the bug**
Getting Started dialog opens up behind the mainwindow in some systems

**To Reproduce**
Open a fresh installation of El-MAVEN

**Expected behavior**
Getting Started should open before mainwindow starts and stay on top of the window till the user closes it.

**System (please complete the following information):**
 - OS: MacOS
 - Version: v0.4-beta

**Comment by rish9511** [comment]
@shubhra-agrawal This has been fixed and merged to develop.
