### ISSUE TITLE
Slow calculation of isotopes

### ISSUE THREAD

**Issue by rish9511** [ElucidataInc/ElMaven#776]
**Describe the bug**
Calculation of isotopes has slowed in the newer versions

**To Reproduce**
1. Upload samples
2. perform labeled work flow  

**Expected behavior**
Isotope detection should take less time. 

**System (please complete the following information):**
 - Windows, linux, MacOs
 - v0.4-beta

**Comment by saifulbkhan** [comment]
Since we have not (yet) been able to reliably reproduce this issue in multiple different machines, for now we are removing this from 0.4 release goals.

**Comment by saifulbkhan** [comment]
Isotope calculation is bearable. In fact it is quite fast.
