### ISSUE TITLE
Empty Peak Table shows error and still uploads the table in Polly

### ISSUE THREAD

**Issue by surbhipoddar** [ElucidataInc/ElMaven#777]
**Describe the bug**
while uploading peak table to Polly, user is shown error that table is empty but still gets pushed to Polly.

**To Reproduce**
1. Go to Polly button on El-MAVEN
2. Click on 'Select Table' and select the empty table
3. Upload

**Expected behavior**
The table should not get pushed on Polly.

**Comment by saifulbkhan** [comment]
This was been resolved in v0.4 release.
