### ISSUE TITLE
How does the minimum parent isotope correlation parameter in isotope detection work?

### ISSUE THREAD

**Issue by shefalilathwal** [ElucidataInc/ElMaven#779]
Can someone please explain how the minimum isotope correlation parameter works with an example? 
How should this parameter be set empirically? 
@chubukov what's the value you use and how did you settle on that value?

**Comment by chubukov** [comment]
@shefalilathwal looks like usually 0.2 (I think that's the default now?) That's fairly liberal, I've definitely used higher values than that before. Just depends on how strict you want to be.

In brief, these correlations are the correlations across scans of the intensity for mass X and the intensity for mass slice Y. Perhaps someone can put together a nice graphical example.
