### ISSUE TITLE
compounds without carbon in positive mode

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#78]
I'm running into a bug with some strange properties, but I'm certain it has to do with database compounds that don't have any carbons.

I noticed it when I accidentally loaded the qe3 (negative mode) list with qe1 (positive mode) data and tried to do peak picking. It crashed, and I was curious why. I eventually traced it to the compound pyrophosphate in the qe3 list, which is unique in that it is the only one in the list without carbon. If I get rid of it, it doesn't crash.

Curiously, this only happens in positive mode (negative mode has always worked fine).

Also, I think this has something to do with threading/concurrency. Firstly, it's a little variable in when it crashes (sometimes it gets through a couple of groups, sometimes it's still in "processMassSlices". Secondly, if I make a source file out of only the offending compound, it works fine! But if I add the offending compound to an otherwise normal list of ~200 compounds, it always crashes.

Medium priority because it hasn't come up in normal workflows (but I guess only because we had no carbon-less compounds in our positive mode source file).

**Comment by chubukov** [comment]
At the moment I'm unable to reproduce this bug.

**Comment by sahil21** [comment]
@chubukov closing this one. Please reopen if reproduced.
