### ISSUE TITLE
Option to visualize area being integrated using shift-drag

### ISSUE THREAD

**Issue by sunil20dhakad** [ElucidataInc/ElMaven#782]
Just a suggestion if we can have 'Area' as a default setting instead of 'AreaTop' because most of   the people are using 'Area' for their calculation.
 
@shubhra-agrawal @shefalilathwal @chubukov FYI

**Comment by chubukov** [comment]
@sunil20dhakad what's the basis for the claim that most people are using Area? Actual surveys or just a feeling?

You can do whatever you like, but I would caution against doing this. I think one reason that Maven has given pretty robust results without a particularly detailed peak model is precisely because of the use of AreaTop. If you use Area, you have to be a little more careful in making sure peak bounds and baseline are properly defined. Additionally, it would be good to have a good visualization of the area calculation, which isn't really there.

**Comment by lparsons** [comment]
We use AreaTop as well, and I don't think changing the default is warranted. However, it would make sense to preserve a users setting for this between sessions.

**Comment by shefalilathwal** [comment]
@lparsons @chubukov I think it's the bias from the fact that most of the people we work with use Area. It's fair to say that we don't know what most people in the field are using. I am curious to hear under what conditions you would use Area/AreaTop/Peak Height. To me, area seems to be the most logical measure, especially when the peak shapes are not gaussian and you want to calculate %labels or try to be quantitative.  Also, agreed about visualization of area calculation - we need a better way to see what's being integrated.

**Comment by lparsons** [comment]
Visualization of what is being integrated should be a high priority, IMHO. Also see #476.

**Comment by raaisakuk** [comment]
I have been using Area (unknowingly) because when I do further processing using Polly, it chooses 'Area' from the Peak Detailed format as far as I know. @Raghavdata can confirm
Also, atleast when we use El maven around the lab, we always use shift+drag with carefully selecting the baseline and I was assuming until now that area is being calculated for that region.

**Comment by raaisakuk** [comment]
@shubhra-agrawal I wanted to ask, which one of these columns should be used for further analysis like fractional enrichment calculation or quantification of peaks?
peakArea | peakAreaTop | peakAreaCorrected | peakAreaTopCorrected (I get these in peak detailed format output)
While analysing a data recently, I felt that peakAreaTop reflected my peaks better than peakArea

**Comment by shubhra-agrawal** [comment]
Transparency around the area being integrated seems important, then.

I agree with @chubukov about the benefits of AreaTop. All other quantitation types suffer from baseline issues or are unclear about the peak boundaries at the moment. (We've been trying out different baseline algorithms for some time but haven't found one that works for us yet)

@shefalilathwal In case of non-gaussian peaks, peakArea might be a better measure than peakAreaTop.

@raaisakuk peakArea in the peak detailed format CSV does not account for baseline. If you're setting the baseline yourself, _try peakAreaCorrected, or peakAreaTopCorrected_. As for which of these should be used for quantification/fractional enrichment, my understanding is that it does not really matter. As long as the isotopes and parent group are using the same quantitation type, the relative measures will be the same.

**Comment by shefalilathwal** [comment]
@shubhra-agrawal agree with @lparsons around visualization of whatever metric you are using which is covered under transparency around what metric is being visualized that you mentioned.
@shubhra-agrawal It might also be worth documenting how different metric (area, areaTop, height, areacorrected, areatopcorrected) affect the outcome/quantitation. Maybe someone from your team can take it up and we can write a short technote about it and publish it on the wiki or with documentation.

**Comment by shubhra-agrawal** [comment]
@shefalilathwal Sure. Will update here when it has been added to the wiki.

**Comment by raaisakuk** [comment]
@shubhra-agrawal My concern came from the fact that recently while calculating concentrations for a metabolite I noticed that I got significant concentrations using peakAreaCorrected but there was very less signal which seemed to be better reflected in peakAreaTopCorrected. I will try both these parameters but for me also, visualization would be a priority.

**Comment by saifulbkhan** [comment]
Closing this, since v0.10.0 now has the enhancement being requested here. Please refer to the [description of the PR](https://github.com/ElucidataInc/ElMaven/pull/1218#issue-368919611) for usage, until we add documentation regarding this change.
