### ISSUE TITLE
Tried Alginment with Orbiwarp and the progress bar won't move

### ISSUE THREAD

**Issue by raaisakuk** [ElucidataInc/ElMaven#784]
**Describe the bug**
I tried using the Alignment option but this happened:
1. Orbiwarp - The progress bar kept moving without anything happening.
2. Loess - It started aligning but got stuck at 69% and my comp froze.

**To Reproduce**
Align Succinate with the dataset given on Trello using Orbiwarp

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: Windows 8.1
 - Version: v0.2.4

**Additional context**
This issue has been discussed here: https://trello.com/c/9GQd68c2/62-how-does-el-maven-handles-things-when-rt-is-shifted

**Comment by shubhra-agrawal** [comment]
@raaisakuk We're working on alignment at the moment and I was going through some of alignment related issues (primarily obi-warp) to figure out if these should be part of our development plan. Looks like the data has been moved from the box link since the time this issue was filed.

Have you been running into similar issues in the later versions? It would be great if you could share the data with us again.

**Comment by chubukov** [comment]
It's a major issue still. See also #787, #859, etc. I would consider alignment still not routinely usable.

**Comment by shubhra-agrawal** [comment]
@chubukov Got it. @rish9511 has multi-processed obi-warp alignment as part of #859 but it hasn't been merged to develop yet. He'll be looking into displaying the progress (#787) in the coming week. You should have both of these fixes as part of v0.6.0.

Apart from the speed and unpredictable wait-time, do you face any other issue with the algorithm? Crashes or failure to align data properly, etc.

**Comment by raaisakuk** [comment]
@shubhra-agrawal I also found out that the link has been removed. I am not sure why that happened and forgot which dataset it was exactly. I believe it is [this](https://yale.box.com/s/gxhitmqhwvf6jkrwsfjr8iat3cfe40vu) one. Let me know if that helps!

**Comment by shubhra-agrawal** [comment]
@raaisakuk Will test it out and let you know. @rish9511 Please use this dataset to test your branch.

**Comment by rish9511** [comment]
@shubhra-agrawal  
While trying to access the dataset, Box complains that 'This shared file or folder link has been removed or is unavailable to you.'

@raaisakuk 
Will it be possible for you to share the samples via a new link ?

**Comment by chubukov** [comment]
@shubhra-agrawal 

> Apart from the speed and unpredictable wait-time, do you face any other issue with the algorithm? Crashes or failure to align data properly, etc.

Honestly, it's hard to answer this because it hasn't been possible to use the alignment feature routinely. So we just don't have the data.

**Comment by shubhra-agrawal** [comment]
@chubukov could you share one such lcms dataset with me? Where obi warp gets stuck. We'll test the new version with that data. The dataset Raaisa shared is MRM so that's a separate test for the algorithm.

**Comment by shubhra-agrawal** [comment]
@chubukov We'll be testing the new version of El-MAVEN internally this week. Would be great if you could tell us which data gives you the most trouble with the algo and we'll try to make sure it works for you!

**Comment by saifulbkhan** [comment]
@chubukov We have made improvements to OBI-Warp's run-time yet again and fixed all the crashes that we were able to find. OBI-Warp should be considered stable and we are treating it as our default alignment algorithm.

@raaisakuk We will open a separate issue for MS2 scan alignment. Closing this as resolved now.
