### ISSUE TITLE
better user feedback during alignment

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#787]
Sometimes alignment runs very quickly and sometimes it takes hours. It would be good to have more feedback to the user about the current state and some sort of guess about fractional progress.

**Comment by shubhra-agrawal** [comment]
@chubukov Agreed. Efforts around this are already underway. You should be able to see the percentage progress in the progress bar in the coming release v0.6.0 (tentatively in the 1st week of Dec)

**Comment by shubhra-agrawal** [comment]
@chubukov This has been implemented in v0.6. You can see a progress bar for obi-warp as well.
