### ISSUE TITLE
editing groups in peak table or merging tables

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#79]
Throwing this in as a possible item that could go into the GUI refactoring. Not absolutely necessary -- the workaround is fine for now.

This is (or I imagine will be) a very common workflow: 

- Use automated pick peaking with compound database to generate a table.
- Scroll through (some of) the selected peaks. For the compounds where I judge that the wrong peak was chosen, or poor integration limits were used, I redo the integration manually.

The way that it is set up now, the manually integrated peaks will go into the bookmarked table. Presumably I will always also delete the bad peak from the original table (that's not a big deal). But now if I want to export my final results, I have to export two tables, and then concatenate them in Excel or something like this.

I see a couple of reasonable UI solutions here:
- add a functionality to merge two tables. Then the user would do everything as now, and then merge the bookmarked table and the original table.
- pass to EIC widget the fact that I'm looking at a peak from a peakTable, and if I integrate a region, update the peak in the table instead of creating a new one in the bookmarksTable.

V.

**Comment by GeorgeSabu** [comment]
@chubukov This functionality is now implemented and tested. On the bookmark table, there is a merge dropdown. Using this dropdown contents in the bookmark table can be merged to the desired peaks table.
