### ISSUE TITLE
Clarify text in Getting Started dialog

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#794]
1. Using the term *upload* in steps one (1) and two (2) is confusing. Upload typically means the user will send the data to a remote machine. In this case, the user is *open*ing or *load*ing a file.

2. Add missing articles and remove excessive capitalization, fix comma usage
     * "Upload Compound Database" => "Load **a** compound database"
     * "Store, Collaborate, Analyze and Visualize your omics data on cloud." => "Store, collaborate, analyze **,** and visuzalize your omics data on **the** cloud."
     * "Parameters for labeled/unlabeled **,** LCMS and LCMS/MS data are listed in Documentation" => "Parameters for labeled/unlabeled LCMS and LCMS/MS data are listed in **the [documentation](https://github.com/ElucidataInc/ElMaven/wiki)**"
     * "Check our step by step guide **,** for your workflow" => "Check **out** our step by step guides for common workflows"

![image](https://user-images.githubusercontent.com/645128/42697665-c2e77f54-8689-11e8-8698-e0e3547ef507.png)

**Comment by shubhra-agrawal** [comment]
@lparsons Thanks for the suggestions. Resolved and merged to develop!
