### ISSUE TITLE
Shift + Drag adds the same compound multiple times (same m/z, rt and intensity) in the bookmark table

### ISSUE THREAD

**Issue by surbhipoddar** [ElucidataInc/ElMaven#798]
**Describe the bug**
If you manually curate peaks using Shift+Drag function, the group with the same rt, same m/z and the same intensity gets added to the bookmark table. Moreover, each of this group shows a different maxWidth/maxAreaTop/MaxQuality

**To Reproduce**
Shift+Drag any peak. Repeat.

**Expected behavior**
The same peak should not get added. Also, the challenge where the same group shows different values for maxWidth/maxAreaTop/MaxQuality.

**Screenshots**
![screen shot 2018-07-16 at 2 53 53 pm](https://user-images.githubusercontent.com/39942702/42809045-3ba9c816-89d2-11e8-8fa9-4a6d95567d22.png)

**Comment by chubukov** [comment]
I'm really concerned about the second part that you report. Is there also any difference between the areaTop values for each sample? That would be something we have to sort out asap.

Thanks

**Comment by shubhra-agrawal** [comment]
@chubukov In the screenshot, maxAreaTop seems to be the same for all duplicates. I also checked the Peak Detailed Format CSV from such a table. peakAreaTop was the same for all duplicate peaks. The rt ranges and therefore the peakArea and peakAreaCorrected were different. 

Will look into the issue a bit more to make sure everything is fine with the export and update you guys.

**Comment by chubukov** [comment]
Great, thanks.

**Comment by saifulbkhan** [comment]
If m/z and rt of an incoming bookmark is within a small range of an existing peak-group in the table, the user will be asked whether they want to continue with it or to discard it. This simple logic and prompt replaces the old logic, which checked for various other things but was unreliable.
