### ISSUE TITLE
Some peaks at the end not marked on autosave

### ISSUE THREAD

**Issue by madhuri16** [ElucidataInc/ElMaven#80]
While doing manual peak curation after automatic peak picking, 3-4 peaks, in the end, were not saved. Autosave option was enabled at the beginning of the peak curation.

**Comment by GeorgeSabu** [comment]
@madhuri16 We have resolved this bug. Can you please check it and close the issue if you feel it's resolved?

**Comment by madhuri16** [comment]
@GeorgeSabu Yes, now all the peaks are saved after peak curation is done. I have checked it by running a dataset.
