### ISSUE TITLE
Unable to build v0.3.1-308-gf1a9776

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#801]
Attempting to build `v0.3.1-308-gf1a9776` results in the following:

     genhtml: ERROR: cannot read /home/lparsons/Documents/projects/maven/ElMaven/CrashReporter/src/qs3/qbucket.cpp

**To Reproduce**
1. `git pull develop`
2. `./run.sh`
3. See error

**System (please complete the following information):**
 - OS: Ubuntu 16.04

**Comment by shubhra-agrawal** [comment]
Latest develop is at v0.4.0-beta.1
Can you try
1. Git pull develop
2. ./uninstall.sh
3. ./run.sh

And let us know if this is resolved?

**Comment by lparsons** [comment]
That did the trick, thanks @shubhra-agrawal!
