### ISSUE TITLE
Peak highlights are displaced while doing untargeted analysis

### ISSUE THREAD

**Issue by surbhipoddar** [ElucidataInc/ElMaven#804]
**Describe the bug**
After doing an untargeted analysis, the peak tops highlights are shifted on the EIC. This is because the ppm for the untargeted analysis is different from that displayed on the EIC.

The ppm should get updated on the EIC as per the analysis performed for the selected peak table.

**Comment by chubukov** [comment]
Linked to #237

**Comment by shubhra-agrawal** [comment]
@surbhipoddar We have synced the PPM values between the mainwindow and the Peaks dialog. Any time user performs peak detection, the PPM value used will be updated in the mainwindow so the peaks are displayed correctly. Will be available in 0.7.1
