### ISSUE TITLE
The feedback button launches a crash reporter

### ISSUE THREAD

**Issue by saifulbkhan** [ElucidataInc/ElMaven#806]
A reporter dialog meant for when El Maven has crashed is brought up when feedback button (at the bottom right corner) is clicked. This button, should for the time being be removed since we are not expecting any feedback from our users. Bug reports are still welcome, but that dialog should be provided in the scenario when the application has actually crashed.

**Comment by rish9511** [comment]
@saifulbkhan 
feel free to remove it

**Comment by saifulbkhan** [comment]
The button has been merged and will no longer be available in v0.5
