### ISSUE TITLE
Reversed sample order

### ISSUE THREAD

**Issue by XiaoyangSu** [ElucidataInc/ElMaven#807]
**Describe the bug**
When opening a group of files, the samples are in reverse order.

**To Reproduce**
Load a number of samples in alphabetical order

**Expected behavior**
The samples should appear in the correct alphabetical order, not the reversed order. Alternatively, add a button to reverse the sample order.

**Screenshots**
![image](https://user-images.githubusercontent.com/14297111/42887354-c7357082-8a73-11e8-8d4e-ac4e63440f20.png)

**System (please complete the following information):**
 - OS: Windows 7
 - Version El-MAVEN v0.3.2

**Comment by shubhra-agrawal** [comment]
@XiaoyangSu We can make sure the samples are sorted alphabetically on upload. 

For the time being, you can click on the "Sample" column header to sort the samples. Same goes for other columns in this space. Let me know if you run into any problems.

**Comment by XiaoyangSu** [comment]
I didn't noticed the samples can be sorted. This solves the problem. Thanks!
