### ISSUE TITLE
better feedback during untargeted peak picking

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#81]
Is it possible to provide better status updates during the untargeted peak picking? Right now there is the cyclic sliding bar, but it doesn't give any sense of how far along the process is. Since this process often takes quite a while, some feedback to the user would be nice (maybe a counter of groups found so far, or something to this effect).

**Comment by GeorgeSabu** [comment]
@chubukov cyclic sliding bar happens when it's doing mass slices. Let me see what I can update to the user.  During the cyclic sliding bar, it haven't started finding the groups .
