### ISSUE TITLE
Window size/geometry/location is not saved in subsequent sessions

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#820]
**Describe the bug**
After starting El-MAVEN I move and resize the window to a comfortable setting on my machine. Upon exiting and restarting, the window size and geometry return to some default setting.

**To Reproduce**
1. Start El-MAVEN
2. Move and resize the window
3. Quit El-MAVEN
4. Start El-Maven again, the window will be in the same position as after step 1.

**Expected behavior**
The window size and position will be retained between sessions.

**System (please complete the following information):**
 - OS: Ubuntu 16.04
 - El-MAVEN v0.4.0-beta.1

**Comment by saifulbkhan** [comment]
Window size will, finally, be preserved over sessions, starting v0.9.0. Closing.
