### ISSUE TITLE
ElMaven strange pictures

### ISSUE THREAD

**Issue by MashaNB** [ElucidataInc/ElMaven#822]
Hi guys!

Firstly, ElMaven 2.4 crashed on 
![problem](https://user-images.githubusercontent.com/42024800/43567594-720e8fc4-9632-11e8-8138-b818506f5d93.PNG)
my computer because of the format (mzxml). When I started to convert into mzml, it worked but I got strange images instead of the Gaussian peaks(please see attached). Could you please help me!!
 - OS: Windows 7
And I used this information https://github.com/ElucidataInc/ElMaven/wiki/Labeled-LCMS-Workflow

**Comment by shubhra-agrawal** [comment]
@MashaNB I believe our support team has been able to resolve the conversion issues you've been facing. I'm closing the issue here. Feel free to re-open it if your problem is not resolved.

@Raghavdata FYI
