### ISSUE TITLE
crash with deleted samples.

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#83]
I'm still getting exactly the behavior of #5 (Maybe a sibling of #4 as well), and I guess #36 is relevant.

1. load some samples and bookmark some peaks
2. delete some samples
3. click on one of the bookmarked groups (other than the one currently displayed)

This seems to crash very reproducibly for me.

We had a long discussion of what the right behavior should be in the comments here: #5 . Most of the options outlined there are ok.

**Comment by GeorgeSabu** [comment]
@chubukov We have resolved this in the latest develop. This crash doesn't happen always when the above steps are followed. But always gets a warning invalid scan number. Right now what we have done is, we cleared the peaks related to the sample after the samples are deleted. This no longer giving us a warning, and also we haven't seen it crash with the tests we did.

**Comment by chubukov** [comment]
@GeorgeSabu did you clear the peaks just from the bookmarks table? If I do automated peak picking, and then delete some samples, I do get the crash when I scroll through the peaks.

Not high priority -- I fully admit this is sort of a weird thing to do.

**Comment by GeorgeSabu** [comment]
@chubukov We did clear peaks from automated peak picking and bookmarking. Let me see if I can reproduce this.
