### ISSUE TITLE
Delete peak table

### ISSUE THREAD

**Issue by shubhra-agrawal** [ElucidataInc/ElMaven#831]
**Is your feature request related to a problem? Please describe.**
There is no limit to the number of peak tables a user can create in El-MAVEN. Each table adds an icon on the sidebar panel. After the first few tables, the panel gets full and the additional tables are hidden behind a '>>' sign. This is hard to reach for the user (especially in Mac). 
Memory consumption is also a concern.

**Describe the solution you'd like**
1. Provide an option to delete peak tables
2. Add the side bar panel icon for the latest table on top
3. Maybe display the table number on the icon itself?

**Describe alternatives you've considered**
Users can just close the table to reduce clutter but it still consumes memory and opening a table is hard because of UI

**Comment by saifulbkhan** [comment]
#849 takes care of this issue.
