### ISSUE TITLE
Compound DB display is not updated on changing Ionization Type

### ISSUE THREAD

**Issue by shubhra-agrawal** [ElucidataInc/ElMaven#832]
**Describe the bug**
If user changes the 'Ionization Type' in 'Options'->'Instrumentation' from ESI to EI, the compound DB does not update in real time.

**To Reproduce**
1. Go to Options
2. Change Ionization type to EI
3. Compound db does not update even though EIC shows updated m/z range
4. Change Ionization mode
5. Compound db updates with both changes

**System (please complete the following information):**
 - OS: Ubuntu
 - Version v0.4.1

**Additional context**

**Comment by saifulbkhan** [comment]
Should be fixed with #862.
