### ISSUE TITLE
Better error handling for compound database (stray newline characters etc)

### ISSUE THREAD

**Issue by rickwilliams23** [ElucidataInc/ElMaven#836]
**Describe the bug**
Upon attempting to upload database, I am met with the following message: "Trouble in loading compound database (compound database name)". This issue only occurs when I attempt to use an updated version of the database that I have used previously. After saving the updated version, even going back and changing the cells back to the original database will still result in the same error message being displayed.

**To Reproduce**
1. Go to https://yale.box.com/s/0ztcsn33acyk2inkv4gxwhzi5ytjltz5
2. Click on Bugtest_8Aug18. There should be two .csv files that should be identical, one being kibbeylab_cpd_db_alanine_neg.csv and the other being kibbeylab_cpd_db_alanine_neg (2).csv. I attempted to update the original file with more compounds and now it does not upload to ElMaven, while the redownloaded (2) file uploads normally
3. See error: (2) file uploads normally, original file does not

**Expected behavior**
I removed the changes to the original file, so it should be identical to the redownloaded (2) file. So I expect them both to upload normally.
![screen shot 2018-08-08 at 3 45 31 pm](https://user-images.githubusercontent.com/42219421/43860735-a3ffff46-9b22-11e8-81f9-cfe154fb4a81.png)

**Screenshots**
Attached

**System (please complete the following information):**
 - OS: MacOS
 - Version v0.2.4.4 and v0.4.1

**Additional context**

**Comment by shubhra-agrawal** [comment]
@rickwilliams23 Seems to be an excel issue. There was a missing newline character in the header row, so El-MAVEN was reading the first entry in the next row as one of the headers. I just cleaned up a few of the cells after the last column and I could upload the file then. 

Ideally, something like this should be handled within El-MAVEN. In the meanwhile, the "Show details" button on the error prompt could help you debug such cases.

**Comment by rickwilliams23** [comment]
Hello! Thank you for the response! Yes I checked the "Show details" tab and assumed it was an issue like this, however, I could not figure out how to fix it. How exactly did you "clean up" the cells after the last column? I tried deleting them and clearing their contents, as well as checking in notepad how the file looked and still could not get the original file to work.

I apologize as I realize this is a very minor issue, but I cannot update my compound sheet unless I get this working. Thank you again for the help!

**Comment by shubhra-agrawal** [comment]
@rickwilliams23 It's better to use a spreadsheet when making changes to a CSV file, especially when adding/deleting new rows. You can edit it in Google Sheets (online), Numbers from iWork office suite (Mac), or LibreOffice (Linux). 

To make your file work again, just open it in any of these applications and delete the contents of the cells where the error might be showing up. In this case, I pressed delete for a few empty looking cells after the 'polarity' header and the issue was cleared up.

Let me know if this isn't clear!

**Comment by rickwilliams23** [comment]
Ok yes, it appears my Excel is saving the files incorrectly. It works fine using Google Sheets. Thanks so much for the help!
