### ISSUE TITLE
Crash: Alignment followed by isotope calculation

### ISSUE THREAD

**Issue by shubhra-agrawal** [ElucidataInc/ElMaven#839]
**To Reproduce**
1. Perform alignment for 26 samples 35Mb each
2. Go through the identified peaks
3. El-MAVEN crashes

**Additional context**
Sentry link: https://sentry.io/share/issue/1672c63bdf4a4b3b8f891bbeb7b99eca/

@lparsons FYI

**Comment by lparsons** [comment]
Any updates on this?

**Comment by saifulbkhan** [comment]
The crash log is no longer available. The crash is also not reproducible from what is described. Closing this until further reports.
