### ISSUE TITLE
na correction

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#84]
Something is really screwy with the 13C natural abundance correction. It seems particularly problematic for sulfur-containing compounds.

Seems to happen in both negative and positive mode.

If I disable the checkbox for natural abundance correction in the options, everything looks fine. If I enable it, some compounds (e.g. taurine) get completely blank isotope % plots. There are a few other ones that are incorrect, I can give more examples, but it's not all sulfur compounds (e.g. methionine looks ok).

I see this in Maven 776 also (weird-looking blank isotope plot for taurine) but some of the specifics are different -- again, can get into more detail later.

I think the NA correction was one of the things that we were going to look at more carefully as part of the refactoring process anyway, right? Maybe this can take this up then.

We could actually disable the checkbox for now.

**Comment by GeorgeSabu** [comment]
@chubukov The NA correction is not running for compounds with less than or equal to two carbons. For reasons we do not understand the code uses nc = nc - 2 to do the NA correction. "2" is hard coded.

![png](https://cloud.githubusercontent.com/assets/22674403/21611644/b15baedc-d1f3-11e6-905c-b45c29bb31d1.png)

That is the reason it's showing the odd behavior.

**Comment by chubukov** [comment]
@GeorgeSabu hmm, that's a little weird. I guess we can fix this without completely revamping the NA correction.

**Comment by GeorgeSabu** [comment]
@chubukov I have updated the develop with the refactored NA correction code.
