### ISSUE TITLE
Warning when a compound in the db file is discarded

### ISSUE THREAD

**Issue by shubhra-agrawal** [ElucidataInc/ElMaven#846]
El-MAVEN discards the rows from compound db file if there is no m/z information i.e. no mz, formula or precursorMz (in case of MRM). These compounds do not show up in the GUI and are not used for peak detection.

User should be given a list of compounds that have been ignored by El-MAVEN and the missing fields.

This should also be handled in CLI

**Comment by saifulbkhan** [comment]
The user will now be notified with a list of compounds that were discarded due to absence of necessary information. This will be available in v0.5.
