### ISSUE TITLE
large maxIsotopeScanDiff seems to lead to more crashes

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#85]
There is still something to point 4 in #43. 

One of our users (Dave) was having a lot more crashes than everyone else. I seem to have sort of tracked it down to the fact that he had a large setting for maxIsotopeScanDiff (50 instead of the more typical 10). When I change my setting to 50, I also start seeing a lot more crashes. I don't really have any explanation.

It doesn't happen on every dataset though, and I can't figure out if it's completely deterministic. I'd like to debug it more, but running the debug version of El Maven seems to lead to other problems in my hands. I think I'll wait til we have some of the better tracking mechanisms that we've discussed.

**Comment by shekhjha** [comment]
@chubukov A related question: Did setting maxIsotopeScanDiff to 10 address the issue for Dave?

**Comment by chubukov** [comment]
@shekhjha haven't heard yet. I hope so, but will let you know.

**Comment by GeorgeSabu** [comment]
@chubukov We did also try to reproduce this issue.  But we were not able to reproduce this issue. Can you please point us to the dataset with which we can reproduce this.

**Comment by chubukov** [comment]
@GeorgeSabu yep, will do it tomorrow. I can get it to crash pretty reproducibly.

**Comment by chubukov** [comment]
@GeorgeSabu I was able to reproduce it with the A2587_IL1 set that's already on dropbox. just uploaded a movie. There are three different instances -- in the first one it takes a little while to get the crash.

I wasn't trying to move super quickly, just sort of normal pace. In some cases it just straight up crashes on the first peak anyway.

**Comment by chubukov** [comment]
@GeorgeSabu also there's a weird behavior in the third instance -- when I change the options and it recalculates the EIC, it immediately bookmarks the peak with isotopes. Some stray flag?

**Comment by GeorgeSabu** [comment]
@chubukov I have corrected this in the current develop. Can you please check it.

**Comment by chubukov** [comment]
@GeorgeSabu Did you merge it in? I don't see any recent commits. Am I missing something?

**Comment by GeorgeSabu** [comment]
@chubukov This was solved before the last meeting we had.
