### ISSUE TITLE
Optimize Obi-warp

### ISSUE THREAD

**Issue by rish9511** [ElucidataInc/ElMaven#859]
**Is your feature request related to a problem? Please describe.**
Obi-Warp takes a huge amount of time to perform Alignment, especially in the case of large sample files.
Many times it also leads to the UI getting freezed which ultimately forces the users to quit the application.
It will be of great help if the algorithm is optimized 
  

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
**Misc Todo**
1. Add all settings of alignment dialog in default_settings.xml
2. Give the option to restore to  default alignment settings.

**Comment by shubhra-agrawal** [comment]
Obi-warp alignment is multiprocessed in v0.6.0 and above leading to ~3-4x increase in speed. Next step will be to resolve the known crash points and optimization for further speed improvement.

**Comment by saifulbkhan** [comment]
More improvement has been made to improve run-time of OBI-Warp (sparse OBI-Warp followed by segmented interpolation) in release v0.8.0.

**Comment by saifulbkhan** [comment]
OBI-Warp is fast enough now. Closing this.
