### ISSUE TITLE
C12 PARENT not being detected for certain compounds

### ISSUE THREAD

**Issue by saifulbkhan** [ElucidataInc/ElMaven#861]
This is a rare but reproducible bug (with certain datasets) where some compounds do not have a C12 PARENT subgroup after successful isotope detection.

**To Reproduce**
1. Load samples (this was reproducible for Masha dataset, sample [neg C12] 1).
2. Do peak detection with default settings and isotope reporting enabled
3. The generated peak table will have some groups that have no isotope children, often at the lower end of the peak table.

**Expected behavior**
Every group in a labelled workflow should at least have a C12 PARENT isotope entry as its child group. The absence of a C12 PARENT would mean that the compound was not present in the sample at all and should not have been populated into the peak table in the first.

**Screenshots**
![image](https://user-images.githubusercontent.com/10397162/45142807-14cf1200-b1d7-11e8-93f7-c86897720cd7.png)

**System**
 - OS: MacOS
 - Version: 0.4.1

**Additional context**
We tried looking into this issue but haven't been able to get to the root of it yet. For now, we know that the peak that should be tagged as C12 PARENT and has the closest resemblance to parent group (ideally it should be the same as parent group) is being filtered out during isotope detection.

**Comment by chubukov** [comment]
@saifulbkhan I know it's probably causing all sorts of issues now, but I think it would be great if the underlying solution was to allow metagroups that have no parent peak. (see tangentially related discussion in #336)

**Comment by shubhra-agrawal** [comment]
@saifulbkhan @chubukov Tracked down the issue to isotope-parent correlation. The EIC pulled for the parent was based on the group->meanMz instead of the compoundMz and therefore the correlation was not accurate leading to the C12 parent being filtered out at times. Raising a PR for this.

**Comment by saifulbkhan** [comment]
Fixed and merged. Available in v0.9.0.
