### ISSUE TITLE
extra column headers in database file cause file not to be loaded

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#88]
If I put an additional column in a source file that's not one of the normal fields, Maven refuses to read the file. I glanced at the code and I have absolutely no idea why this is happening, but it's easy to reproduce. Just take any working source file and add an extra column and call it something random.

It would be good to have some more feedback to the user during this process, even if it's just printed on the console (e.g. print fields read from the file, number of compounds loaded, number of compounds failed (or something like this))

**Comment by GeorgeSabu** [comment]
@chubukov I guess this could be solved alongside with #68.

**Comment by GeorgeSabu** [comment]
@chubukov This issue is now resolved. And I have updated on the branch ftr_CompoundLoadMsg. In the same branch, I have added message pop-up on the failure of upload of a compound database.

I have to add more check on the compound database when to tell when db upload has failed when not.

**Comment by chubukov** [comment]
@GeorgeSabu Cool, thanks. There was actually already a message on the bottom status bar, but I think it was only for the case when the initial compound DB could not be loaded when Maven opens.

**Comment by chubukov** [comment]
@GeorgeSabu this is fine, but I think at some point (low priority) it would be good to make it so that when there is an unrecognized column

either
a) (my preference) accept the file, ignoring the column (and probably give a warning message, since it may be a typo and the user will be surprised the data is not read in)
b) if we decide to reject the file, at least provide the information on what the offending column was, so that the user knows what to fix

**Comment by GeorgeSabu** [comment]
@chubukov Now when the user uploads a compound db it will show a popup if not loaded properly. In the popup I can add give a button called more information which would give information why it failed.

**Comment by chubukov** [comment]
@GeorgeSabu We're in the weeds of ui/ux design but to me it seems clear to not even bother with the button. If you know why something failed, let the user know asap!
