### ISSUE TITLE
BUG - Unable to bookmark peak group with isotopes (MacOS)

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#887]
**Describe the bug**
When bookmarking a peak on MacOS, no isotope information is saved. The isotopes are found and displayed in the Isotope Plot widget. Also, automatically detected peak groups are stored with their isotope children. In addition, when exporting the CSV file, there is no isotope information exported. I have checked and the isotope options are checked in the Options window.

**To Reproduce**
1. Double click on a peak group to add to the bookmark table

**Expected behavior**
I expect to see the peak group added to the bookmark table with an arrow next to it to allow me to expand and see the isotopes. Also, when exporting the bookmarks table, I expect to get values for the various detected isotopes in the exported table.

**System (please complete the following information):**
 - OS: MacOS
 - Version: 0.4.1

**Comment by shubhra-agrawal** [comment]
@lparsons I've reopened #453. Re-opening an issue helps us identify which fixes are not sticking. 
 I'll close and mark this one as a duplicate.
