### ISSUE TITLE
Exporting CSV doesn't include Isotopic peaks

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#9]
When CSV is exported after isotopic peak-picking, only the parent ion is present in the output CSV. There is no information of Isotopes of the parent ions.

**Comment by chubukov** [comment]
@sahil21 

We went over this a lot when working on Maven 776, so there is a lot of useful info on the old Trello board. A couple of key points:

- sample._C13labeled etc have to be set, and those are only set during peak picking (this is the infamous "Feng addition" that is the source of most of these problems).
- there is actually a typo -- one of the export/peak generation functions uses "D-labeled" and the other uses "D2-labeled". Deuterium labeled peaks have never been properly exported

For the Agios use, I made a 776 version that always exported all isotopic peaks regardless of the internal options/variable settings.

**Comment by sahil21** [comment]
@chubukov Yes, I also believe that the reason behind this is Feng Addition. We'll work on it and find a better alternative instead of Feng Addition.

**Comment by chubukov** [comment]
I've made a temporary fix for this (https://github.com/ElucidataInc/ElMaven/tree/tempfix_fulloutput) just so that we can continue testing the other parts of El Maven (this bug is sort of a deal breaker). I expect that the resolution of #43 will render it moot.

**Comment by GeorgeSabu** [comment]
@chubukov In the Isotopic refactoring branch is working fine.

**Comment by GeorgeSabu** [comment]
#43 This is working fine

**Comment by chubukov** [comment]
Confirming that this appears to be resolved.
