### ISSUE TITLE
Exporting only Good Groups to Polly

### ISSUE THREAD

**Issue by surbhipoddar** [ElucidataInc/ElMaven#904]
**Is your feature request related to a problem? Please describe.**
Currently, I spent significant time marking my groups good or bad within my peak table, but I cannot send only my good groups to Polly.

**Describe the solution you'd like**
I should be able to send only good groups or exclude bad groups from the data being sent to Polly on the GUI. By default, all the groups should be exported irrespective of the last selection.

![export 1](https://user-images.githubusercontent.com/39942702/47429369-d1932780-d7b3-11e8-9632-6432a687828a.png)

![export 2](https://user-images.githubusercontent.com/39942702/47429159-179bbb80-d7b3-11e8-9b8e-082c414c0314.png)

**Comment by saifulbkhan** [comment]
On develop. Will be available in v0.7.1.
