### ISSUE TITLE
new widget idea: overlapping peaks

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#91]
After doing automated compound database search, it would be really useful to narrow down the peaks so that multiple compounds are not annotated to the same peak. This is particularly critical if doing automatic isotope picking.

The idea would be to have a widget with a table that looks like this

Compound 1 | Compound 2 | mzRT overlap | correlation 
------------ | -------------|-----|---
Succinate | Fumarate-13C-2 | 0.56 | 0.98
Glutamate-13C-1 | Glutamate-15N-1 | 1.00 | 1.00 

(second line indicates too large ppm window)

etc. only pairs with >min_corr or >min_overlap would be shown. Probably best if each pair appears twice.

this would be linked to a peak table, so there would need to be some way to manage that interaction (this is already in place for things like the scatter plot, so doesn't seem too bad)

- correlation is correlation of intensities across samples
- mzrt is defined as something like the fraction of rt window for peak 1 (from rtmin to rtmax) that's within the rt window of peak 2, multiplied by the same thing for the mz window. Maybe adjust it to make it symmetric? Not sure; this will need some fine-tuning. If the data is MS/MS data, then the mz window is not used, but only consider pairs with the same srmIDs. (honestly, this is mostly only useful for full-scan).
- should be able to select either compound 1 or compound 2 to show its EIC. Should be able to delete one or the other to delete it from the linked peak table and refresh both that table as well as the widget. 

Let me know if it makes sense.

**Comment by chubukov** [comment]
Maybe even better than the overlap calculations is just to do correlation of the intensities across the scans (correlations of the peaks). The code to do this already exists -- it's the "isotope-parent" correlation.

**Comment by chubukov** [comment]
Hm, actually a big piece of this already exists in the form of the covariants widget. That's in fact almost exactly what I had in mind, though it could be improved in a few ways (a few hard-set constants should be parametrized, and it could be more integrated with the peak-table-oriented workflow)

**Comment by chubukov** [comment]
This issue can really be turned into "Update covariants widget". That widget is actually quite useful, and it could use a little sprucing up.

**Comment by saifulbkhan** [comment]
@chubukov Closing this, since #295 exists. Your comments here can be revisited from that issue, when we take it up (hopefully sometime in the near future).
