### ISSUE TITLE
El-MAVEN crashes when samples are removed and added

### ISSUE THREAD

**Issue by hemenboro123** [ElucidataInc/ElMaven#910]
**Describe the bug**
if the user adds some samples in El-MAVEN and did peak picking, it will show peak picking table 1. if in same session users remove those samples and added some samples and did peak picking. if this process continues, El-MAVEN crashes suddenly.

**To Reproduce**
1. Go to El-MAVEN and add some samples
2. Click on peak picking 
3. Repeat those steps and at some point it causes El-MAVEN to crash.

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - windows server 2016
 - Version [v0.4.1 and 0.5]

**Additional context**

**Comment by saifulbkhan** [comment]
Fixed in v0.7.0. Closing.
