### ISSUE TITLE
Better control of sample order

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#913]
Several members of our lab have been frustrated that they are not able to control the order of the samples. While they can sort, they have a particular order that they prefer. In previous versions of Maven, they could load the samples in the appropriate order, or manually rearrange them if necessary.

**Describe the solution you'd like**
1. Put the samples in the order that they were loaded.
2. Allow manual sample rearrangement.

**Describe alternatives you've considered**
Renaming samples so that a sort puts them in order is a possible workaround, but doesn't allow for easy rearrangement in different contexts and is an annoyance.

**Comment by shubhra-agrawal** [comment]
@lparsons This feature has been implemented and merged to develop. El-MAVEN will now load samples in the order it receives them, and allow drag and drop to reorder. 

Will be available in v0.7.1 soon. Feel free to re-open the thread if there are any issues.
