### ISSUE TITLE
Performance improvement for baseline correction

### ISSUE THREAD

**Issue by surbhipoddar** [ElucidataInc/ElMaven#924]
**Describe the bug**
Currently, the whole EIC is pulled to detect the baseline. This lowers the performance of the algorithm.

**Expected behavior**
We can limit the number of relevant points around the peak we detect while baseline correction instead of detecting the whole EIC. This will help improve the performance of the algorithm.

**Comment by saifulbkhan** [comment]
Since we have started using optimization flags on all three platforms, we should see a fair bit of performance increase. There can still be some improvements such as the one suggested above.

**Comment by saifulbkhan** [comment]
An attempt has been made (available from release v0.8.0) to downsample a signal before calculating its baseline. This should increase browsing and peak detection performance while AsLS Smoothing is turned on.

**Comment by shubhra-agrawal** [comment]
@chubukov FYI. Since the major critique for AsLSS was around its performance, we have optimized it in v0.8.0. Please let us know if you see an improvement for your datasets.

**Comment by saifulbkhan** [comment]
Nobody seems to notice any significant slowdown while detecting peaks using AsLS as the baseline algo. We did benchmarks too, it is only a little slower than the default (thresholding as I call it) for smaller number of scans and even outperforms it when the scan density increases.
