### ISSUE TITLE
Getting rid of existing peak alignment

### ISSUE THREAD

**Issue by danolson1** [ElucidataInc/ElMaven#938]
I'm playing around with the peak alignment parameters. I want to compare the results of one set of parameters with another set, but it looks like each alignment uses the results of the previous alignment. I'm not 100% sure that this is how things work, but I made this assumption since the "AlignmentVisualization" window is still showing something.

I would like to be able to reset the alignment. I see that there's an "undo alignment" button, but clicking it doesn't seem to do anything. My workaround is to restart El-Maven each time I want to change the alignment conditions, but that's cumbersome.

Let me know if you have any suggestions.

-Dan

**Comment by shubhra-agrawal** [comment]
Yes, running alignment multiple times uses the RTs from the previous
alignment.

At the moment, 'Undo Alignment' works in case of PolyFit alignment. We're
currently working on fixing the 'Undo Alignment' button for Obi-warp as
well. It should be out within the next 10-15 days as part of the v0.6.1
release.

**Comment by shubhra-agrawal** [comment]
In the latest v0.6.0, the undo button is disabled once you click on it to signify that the retention times have been reset to their original values. The widgets are not cleared at the moment. That's something we can look into as part of our pre- and post- alignment visualization designs (#550 #551 #552). 

We're planning to have those finalized and available to the users as part of v0.7.0 (~end of Jan 2019)

**Comment by shubhra-agrawal** [comment]
@danolson1 Undo alignment has been implemented for all present algorithms in v0.6.1. Clicking on the button will restore original RTs for all samples. The button is yet to be renamed.

> but it looks like each alignment uses the results of the previous alignment

A clarification, here. Loess and Poly fit use the retention times from the previous state. Obi-warp uses original retention times for alignment every time.
