### ISSUE TITLE
Whatever happened to the "Export Peaks to Spreadsheet" option?

### ISSUE THREAD

**Issue by danolson1** [ElucidataInc/ElMaven#939]
This feature was part of MAVEN as of version 2011.6.17. Do you know when it got removed and why?

**Comment by shubhra-agrawal** [comment]
We have retained that feature from MAVEN. You can export your peaks to a
spreadsheet in the following two ways:

1. Curate peaks in a Peak Table (bookmark or auto detected peaks)->Click on
the CSV button from the Peak Table header. It looks like a save button with
'CSV' written on it, right next to the 'JSON' button.
In the save dialog, you will have the option to export group sunmary
information or peak detailed information in the file Type drop-down.

2. Go to Peaks dialog->Method Summary tab->Click on 'Export Peaks to
CSV->Enter filename->Click Find Peaks

The 2nd method hasn't been tested in a while and will probably be
deprecated soon. I would suggest using the 1st method to export your peaks.
Let me know if there are any issues with it.

**Comment by danolson1** [comment]
Method 1 worked great. Thanks for letting me know!

I never would have thought to look there without you explaining this to me. One way to make this clearer would be to change the tool tip text to "Export Groups or Peaks to Spreadsheet," and in the small dropdown menu that opens when you click on the 'CSV' button, change the "Export All Groups" text to "Export All" (Which would fit better with the other options, "Export Good, Export Bad, Export All, etc.)

-Dan

**Comment by shubhra-agrawal** [comment]
Noted.

We're currently working on redesigning the UI to make it more intuitive.
Suggestions like this are more than welcome. Thanks!

**Comment by danolson1** [comment]
Great. Another UI improvement would be an easier way to close widgets I'm not using. I spend a lot of time hunting around to figure out which button toggles each widget. 

Possible solutions:
1. An 'x' in the corner of each widget to close it. Right now the only button in the corner of the widgets allows you to pop the widget out of the window, which is a feature I never use.
2. Show the widget icon in the widget title bar. Then I could match up the widget icon with the correct widget toggle button.

**Comment by shubhra-agrawal** [comment]
@surbhipoddar Could you communicate these to the design team? I will add this issue to the new project

**Comment by saifulbkhan** [comment]
I think most of the user concerns mentioned in this thread are now taken care of with the latest release (v0.10.0). Closing this.
