### ISSUE TITLE
Restoring defaults does not work for file import settings

### ISSUE THREAD

**Issue by saifulbkhan** [ElucidataInc/ElMaven#946]
The "Use Default Parameters" button in settings dialog does not reset any of the control elements in "File Import" tab. It is not clear whether the settings are actually getting reset internally. Additionally, upon restarting El-MAVEN the settings for file import are reset to their defaults regardless of whether the user had clicked a reset button in the previous session.

**To Reproduce**
1. Open "Settings" dialog.
2. Click on "File Import" tab.
3. Change any of the settings from their default.
4. Click on "Use Default Parameters" button. The changed settings will not reset.
5. Restart El-MAVEN.
6. Open "Settings" dialog.
7. Navigate to "File Import" tab. Settings are now set to their default values.

**Expected behavior**
All settings should be reset every time the user clicks on "Use Default Parameters" button. Also restarting should not reset any settings set from previous session.

**System (please complete the following information):**
 - OS: MacOS - High Sierra
 - Version: v0.5.0

**Comment by saifulbkhan** [comment]
Will be shipped with v0.7.0.

**Comment by saifulbkhan** [comment]
We missed this in v0.7.0. #1066 should take care of it this time.

**Comment by shubhra-agrawal** [comment]
Merged to develop. Will be available as part of v0.7.1
