### ISSUE TITLE
Crash while deleting peaks

### ISSUE THREAD

**Issue by MyaSteadman** [ElucidataInc/ElMaven#95]
I used Shift-Click-Drag function to populate isotopic forms of succinate. but maven crashed when i tried to delete some of the forms from the bookmarked peaks table. Maven also did not Auto-save.

**Comment by GeorgeSabu** [comment]
@MyaSteadman We have resolved the crash you have reported.

**Comment by chubukov** [comment]
I believe that this case has been resolved. Please contribute new issues if you have new crashes.
