### ISSUE TITLE
feature suggestion: mark peaks with keyboard shortcut in automatic peak table

### ISSUE THREAD

**Issue by MyaSteadman** [ElucidataInc/ElMaven#96]
Here's a common workflow:

1. do automated pick peaking
2. filter peaks by manual curation

It would be nice to be able to do the filtering but instead of deleting peaks, simply mark them good/bad so that you can correct mistakes. It would also be great to do this with keyboard only (i.e. hit g/b instead of clicking on the checkmark) for speed.

It would also be nice to be able to "export good" in addition to "export all" and "export selected" from the peaks table.

**Comment by GeorgeSabu** [comment]
@MyaSteadman We have implemented,
1) marking good or bad using a keyboard on bookmarks and peak table( we have also added a keyboard shortcut to open and close the isotopic parent peak to see its children).
2) export to CSV as good or bad.
After some amount of testing, we will make it available.

**Comment by chubukov** [comment]
Awesome.

> we have also added a keyboard shortcut to open and close the isotopic parent peak to see its children

This was actually already available with the left and right arrow keys (at least on windows).

**Comment by GeorgeSabu** [comment]
@chubukov Yes, it's available. We have reimplemented it a little bit. With key "o" we can close and open the isotopic parent. But in addition to that if you are at one of the children and want to collapse its parent that can also be done by pressing "o".

**Comment by chubukov** [comment]
I am not certain, but I suspect it was as a result of some of these change: the left/right keys actually no longer work to open/close. I found them slightly more convenient than the new "o" feature, so it would be nice if both worked.

**Comment by GeorgeSabu** [comment]
@chubukov Yes. It was because of the changes we did. So if we overwrite keypress events in a QT widget all the default functionality of the widget would disappear. So we had to reimplement all the keypress functionalities that were there for the peaks table widget.

In the current develop branch user should be able to open and collapse the tree dock widget with the left and right arrow.
