### ISSUE TITLE
Interchanged values saved in emDB peakgroups table

### ISSUE THREAD

**Issue by saifulbkhan** [ElucidataInc/ElMaven#962]
**Describe the bug**
emDB file is saving `expectedRtDiff` attribute in place of `expectedAbundance` and vice-versa. This bug was caught while writing tests for the `projectDB` module.

The major issue that this causes is that `expectedRtDiff` values exported in a CSV file from an emDB loaded table will have its `expectedAbundance` values in that column instead of the correct values.

Thankfully, isotope plot widget calculates abundance values everytime before displaying so this bug should not effect the plot.

**Expected behavior**
The obvious expected behavior is to save group properties in their correct column.

**Comment by shubhra-agrawal** [comment]
Done. Will be part of v0.7.0
