### ISSUE TITLE
Repair code for reading MSP files

### ISSUE THREAD

**Issue by saifulbkhan** [ElucidataInc/ElMaven#965]
**Description**
MSP (NIST's Mass spectral transfer) files can be used to read in MS/MS metabolites along with mz and intensity profiles of fragments arising from them. El-MAVEN has a function to allow reading these files but it does not read in as many fields as available and even when loaded is not used best used by the application (at least its not very evident how this information is used) for analyzing PRM datasets. Moreover, MSP files can be large in size and it blocks the GUI for the entire duration of load.

**Solution to the issues involving MSP load**
- [x] Add checks for more fields commonly available in MSP files.
- [x] Check for end of data stream and make sure the last compound in file is not missed.
- [x] Run load operation in a different thread from main thread to avoid UI freeze.
- [x] Add a status-bar elements informing the user about the load progress.
- [x] Do not save MSP filenames to be loaded automatically in the next session.
- [x] Figure out a way to load multiple compounds with the same name and ID but having different fragmentation profiles.
- [x] Show a prompt to the user about mismatched polarity of selected library and  loaded dataset.

**Comment by shubhra-agrawal** [comment]
These changes have been merged to develop and will be part of v0.7 release.
