### ISSUE TITLE
Save settings for a session in emDB

### ISSUE THREAD

**Issue by saifulbkhan** [ElucidataInc/ElMaven#969]
The "emDB" format has been introduced as a way to restore user sessions as completely as possible, but at the moment only is [able to restore user data](https://github.com/ElucidataInc/ElMaven/wiki/Session-restore-in-El-MAVEN). It cannot be used to truly restore a session until it can load back the settings that were used for analysis in that session.

Some preparatory work and refactoring might be needed, before settings can be saved in emDB files.

**Here is the current plan to achieve this**
- [x] Add versioning to `projectDB` module.
- [x] Set up automatic upgrades when creating a `ProjectDatabase` instance.
- [x] Bump database version, since the DB schema will have to be changed to accommodate settings table.
- [x] Write migration script(s) for updating/downgrading a given DB instance to one that can be used in current release. We want to be completely backwards compatible with previous versions of emDB.
- [x] Create a table for storing settings from options, peak filtering and alignment dialogs of the application.
- [x] Add methods in `projectDB` module to write/read settings to/from database. Write tests for these methods as well.
- [x] Implement methods to load settings before loading other data-related information from emDB.
- [x] Possibly add UI elements to notify user about save/load operation.
- [x] Warn user when they attempt to load a project file created in a future version of El-MAVEN.

**Comment by shubhra-agrawal** [comment]
These changes have been merged to develop and will be part of the v0.7.0 release.
