### ISSUE TITLE
show splines sometimes shows intensities that are way off

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#97]
It seems like if you enable show splines in the eic window, it often shows a spline fit where the intensity is way higher than the actual peak. However, if you scroll to another compound and then scroll back, usually it then shows a normal-looking curve. I haven't figured out exactly what causes it to reset the state or when exactly it happens, but it happens a lot.

I can record a video if you're unable to reproduce.

**Comment by chubukov** [comment]
@sahil21 is this on-hold because of inability to reproduce or because it's too messy/not worth the effort to fix? If the second, no problem, but if it's the first, let me try to see if I can create a good example.

**Comment by chubukov** [comment]
There's still something screwy here, and it's actually something stochastic or path-dependent -- I'll often click on compound A, get a weird looking spline, then click on compound B, and then back to compound A, and now it looks normal.

It doesn't happen that often, and I don't care about it enough. Happy to leave it on-hold.

**Comment by shubhra-agrawal** [comment]
@chubukov @sahil21 I'm guessing this is also related to the static variable fix. Can we close it?
