### ISSUE TITLE
No peak values when CSV exported from emDB loaded session.

### ISSUE THREAD

**Issue by saifulbkhan** [ElucidataInc/ElMaven#976]
**Describe the bug**
CSV reports exported from a session that was reloaded from an emDB file, do not have intensity values (of selected quantitation type) of peaks from each of the samples.

**To Reproduce**
1. Curate peaks and save project as an emDB file.
2. Quit El-MAVEN
3. Start new El-MAVEN session.
3. Load emDB project file.
4. Export peak table as a CSV report.
5. CSV report has missing peak values.

**Expected behavior**
For each sample, the CSV file should contain the correct peak quantity values of the selected type.

**System (please complete the following information):**
 - OS: MacOS 10.14
 - Version: v0.6.1

**Comment by shubhra-agrawal** [comment]
Will be part of v0.7.0
