### ISSUE TITLE
Support GA "label" for tracking detail

### ISSUE THREAD

**Issue by saifulbkhan** [ElucidataInc/ElMaven#981]
Google Analytics measurement API supports "event labels" that can be used to differentiate between "event actions" taken under different contexts or results. El-MAVEN's analytics does not have support for this detail, and it would be very helpful to have it. It will also be way more helpful than the "event value" parameter that is currently being used for the same effect.

**Comment by shubhra-agrawal** [comment]
Merged to develop. Will be part of v0.7.0.
