### ISSUE TITLE
Disable 'align' button once Alignment starts

### ISSUE THREAD

**Issue by rish9511** [ElucidataInc/ElMaven#993]
**Describe the bug**
The 'align' button present in Alignment Dialog does not get disabled after Alignment is started. 
This allows the user to click on the button infinitely leading to opening of multiple threads in the background with each set of threads performing the same alignment operation.

**Expected behavior**
The align button should be disabled once Alignment is started

**Comment by saifulbkhan** [comment]
The UX will be corrected in upcoming release v0.8.0.
